### ISSUE TITLE
unable to trigger a button via nodeRed

### ISSUE THREAD

**Issue by volkerrichert** [ioBroker/ioBroker.node-red#105]
If you try to trigger a button in ioBroker from within nodeRed using ioBroker Out you'll receive a "state does not exists in ioBoker".

see: https://github.com/ioBroker/ioBroker.node-red/blob/8b1d164015820522513ae19b6585dc2876429add/nodes/ioBroker.js#L414 ff

**Comment by volkerrichert** [comment]
Ok, I'll update to 4.5.1 first.

**Comment by volkerrichert** [comment]
ok, 4.5.1 was ioBroker.javascript. Controller is at 2.2.9

**Comment by volkerrichert** [comment]
I also test js-controler 3.0.18. Same error message

**Comment by Apollon77** [comment]
What do you use as name? A complete state is or a „local“ nodered instance name?

**Comment by volkerrichert** [comment]
The complete name like "denon.0.zoneMain.volumeUp"

**Comment by Apollon77** [comment]
It seems that the state has no value ... and this is checked - why ever. Try to set once  value via admin so that the state is defined ... does it work then?

**Comment by Apollon77** [comment]
Formally ioBroker.node-red/nodes/ioBroker.js L414 should be getForeignObject to check if the object exists

**Comment by volkerrichert** [comment]
Yeap, after clicking the button in ioBroker, node red was able to send a state

**Comment by Apollon77** [comment]
Thenit should be fixed in next node.red plugin version in any case

**Comment by volkerrichert** [comment]
I've seen your fix. THX.
