### ISSUE TITLE
Allocation error

### ISSUE THREAD

**Issue by SaimenSays** [ioBroker/ioBroker.node-red#106]
From time to time Node-Red adapter restarts unexpected. There is 1GB RAM free as long as it runs normally, so I don't think it is a hardware limitation. But of course I can't tell usage in the moment of crash. Can someone skilled please have a look at the attached log and tell me if it is a Node-Red problem or ioBroker related?

Adapter Node-Red is on v1.17.2

Thanks in advance!

[Log.txt](https://github.com/ioBroker/ioBroker.node-red/files/4560862/Log.txt)

**Comment by jwiesel** [comment]
Hi @SaimenSays,
two things come to my mind:
1. Does increasing the Node-Red memory in the ioBroker.Node-Red instance settings change the behavior? Default in ioBroker is 128MB for Node-Red. (startup parameter --max-old-space-size=128)
2. Did you post the issue in the node-red repository as well?
The ioBroker integration (this repo) basically just installs Node-Red, configures it (e.g. auth, max-memory) and adds some ioBroker related nodes to it.

**Comment by SaimenSays** [comment]
@jwiesel,
thanks for suggestion, will try with 256MB and see what happens.
I don't post at Node-RED, because I only have the iobroker log and so I thought they will tell me that it is an ioBroker issue, as it was done in other posts ;)

**Comment by SaimenSays** [comment]
Again thanks for advice. Since I changed Node-Red to max 256MB, there is no restart anymore. However, I can't understand why so much ram is needed yust for a few flows only handling some lightweight homeautomation tasks...

**Comment by jwiesel** [comment]
I'm glad it helped. You're welcome.
Unfortunately Node.js applications seem to consume quite a bit of memory. If I'm not wrong by default every process would be allowed to even allocate 1.5GB memory (which rarely happens, but gives an indication about the situation). Hence the max-memory parameter has been added for smaller systems (like the raspberry pi).
I guess debugging the memory use of your node-red instance would have a learning curve with unclear outcoume. If you run low on memory, maybe that is a place to look at.
