### ISSUE TITLE
Topic Value

### ISSUE THREAD

**Issue by bergjet** [ioBroker/ioBroker.node-red#107]
The Topic Value is not always displayed.
[show](https://www.dropbox.com/s/3ik9ssao0fbqm1e/show.png?dl=0)
[not show](https://www.dropbox.com/s/hlz9gqxq7ws7pzj/no%20show.png?dl=0)

**Comment by Apollon77** [comment]
The out nodes now show the last stored value ... if no value was triggered then is shows "connected" without value
