### ISSUE TITLE
Palette Manager gone from UI

### ISSUE THREAD

**Issue by ReaverPhoenix** [ioBroker/ioBroker.node-red#109]
Hej :)

What's the reason for removing the palette manager from the UI?

Thanks and cheers!

**Comment by bergjet** [comment]
The same. ?

**Comment by thost96** [comment]
Hi, 

as mentioned in https://github.com/ioBroker/ioBroker.node-red/releases/tag/2.0.0 the palette manager was removed so packages are managed via iobroker. 

But I'm now asking how the packages or modules are now updated easily? Rebooting node-red on every package update isn't a good idea and you don't get any update notifications for that.... So this isn't a good idea in my opinion.

**Comment by bergjet** [comment]
Where can I find Nodes, where do I look? How can I install them? Which commands?

**Comment by ReaverPhoenix** [comment]
Yeah, I know .. but what is the benefit by managing the packages through iobroker?

BTW: I reenabled it in the settings.js (/opt/iobroker/node_modules/iobroker.node-red/) .

`palette: {
            editable: true
        }`

**Comment by thost96** [comment]
> Yeah, I know .. but what is the benefit by managing the packages through iobroker?
> 
> BTW: I reenabled it in the settings.js (/opt/iobroker/node_modules/iobroker.node-red/) .
> 
> `palette: { editable: true }`

I personalty see no benefit for that, so maybe some of the developers can answer here?

**Comment by Apollon77** [comment]
The problem when we have it as dependency of the adapter is that we need to update the whole adapter to update the package and if users need different versions it is not really possible. And not any user need the package. 

Additionally there is the confusion which package is automatically available and which needs to be installs by users manually. 

So we decided to streamline this. 

Ok if a package needs an adjustment in the settings file this becomes interesting ...

**Comment by ReaverPhoenix** [comment]
So, checking available updates should look like this?

1. node red user directory
`cd /opt/iobroker/iobroker-data/node-red/node_modules`

2. update command
`npm outdated`

3. install available update
`npm install <name-of-module>`

What about this [Command-line Administration](https://nodered.org/docs/user-guide/node-red-admin)?

**Comment by WolfspiritM** [comment]
I don't like that aswell.
How do I manage packages that are installed right now?

For example I don't want a package anymore that I've installed via pallet manager. I don't see any way to disable or remove it right now? As it seems to be still available. So there was no migration between pallet manager and iobroker.

Also there is no way to search for packets for node-red easily without the pallet manager...

It makes configuring and setting up node red way more complicated in my opinion instead of making things more "streamline".

**Comment by GermanBluefox** [comment]
> Where can I find Nodes, where do I look? How can I install them? Which commands?

![image](https://user-images.githubusercontent.com/4582016/85234274-742dfe80-b40c-11ea-9948-76d0592c788d.png)

**Comment by GermanBluefox** [comment]
> I don't like that aswell.
> How do I manage packages that are installed right now?
 
Will the modules, that are managed via node-red automatically installed if I update the node-red?
If I restore the node-red on the empty system from backup?

**Comment by WolfspiritM** [comment]
> Will the modules, that are managed via node-red automatically installed if I update the node-red?
Yes. I've no idea where they're stored but for me the modules that I've installed via the pallet manager are still there after updating the node-red adapter.

> If I restore the node-red on the empty system from backup?
I'm not sure about that. I've never needed to restore a backup.

**Comment by bergjet** [comment]
If you install an ioBroker backup, the modules must be reinstalled. (experience from 1 week ago).

**Comment by Apollon77** [comment]
... and exactly because of thisthe change was done ... because packages stored with adapter configuration are back and reinstalled after restore

**Comment by WolfspiritM** [comment]
> ... and exactly because of thisthe change was done ... because packages stored with adapter configuration are back and reinstalled after restore

In my case it has been backed up cause I was using total backup from backitup (which seems to not be supported anymore). I noticed that the normal backup from iobroker doesn't contain the data directory.

In my opinion it would be a better way to handle it similar to the flows. Currently flows are stored in iobroker aswell via the saveObjects function. Can't we just save the package.json (and probably the lock aswell) as an object and restore it on launch as it is already done for flows and flows-cred? 
According to https://github.com/node-red/cookbook.nodered.org/wiki/How-to-backup-flows-and-related-configuration it just requires an "npm install" afterwards so we can check if node_modules exists and if not do an npm install after restoring the package.json

**Comment by vepman** [comment]
Also muss ich jetzt auf die Kommandozeile, um zu updaten?
Ich muss in der Adapter-Konfiguration manuell einen pfad zum neuen node eingeben?
Leute, das ist aber nicht komfortabel.

**Comment by bergjet** [comment]
> Leute, das ist aber nicht komfortabel, eher kompliziert.

Ich bin zurück auf die 1.17.2 Denn ohne Palette ist der Adapter nicht zu gebrauchen.

**Comment by vepman** [comment]
mach ich wohl auch. 

Am 22. Juni 2020 16:10:27 MESZ schrieb bergjet <notifications@github.com>:

**Comment by vepman** [comment]
> Ich bin zurück auf die 1.17.2 Denn ohne Palette ist der Adapter nicht zu gebrauchen.

Vor allem, wenn man auf bestimmte nodes angewiesen ist.

**Comment by GermanBluefox** [comment]
> Adapter nicht zu gebrauchen

Bitte bei solchen Ausdrücken immer acht geben. Ja du kannst damit nicht nicht die Nase putzen, du kannst nicht damit keine Freundin finden, aber .... du kannst trotzdem damit automatisieren.  Und bei diesem Punkt ist deine Behauptung schon falsch.
Wie ist dein Vorschlag, außer "alles ist schlecht"?

**Comment by bergjet** [comment]
Es gibt hier mehrer Raspberry. Die Systeme werden öfters umgestellt und haben je Pi verschiedene Node-Red Module. Ich müsste ohne Pallettenansicht für jeden Pi die jeweils dort installierten Node-Red Module aufschreiben, damit ich wieder die richtigen Module am jeweiligen Pi installieren kann.
Aber so lange der 1.17.2 funktioniert ist es ja egal.

**Comment by vepman** [comment]
> Wie ist dein Vorschlag, außer "alles ist schlecht"?

Bitte einfach nur den Paletten-Manager aktivieren.
Oder in den Einstellungen muss explizit der Paletten-Manager aktiviert werden.
Und nicht böse sein, für manche ist dieser Punkt eben wichtig.  ;-)

**Comment by WolfspiritM** [comment]
> Oder in den Einstellungen muss explizit der Paletten-Manager aktiviert werden.

I also think a configuration option is the right way for now instead of removing it completly.
I made a pull request to add that configuration and display a warning about backups if either the palletmanager or the projects feature is enabled.

**Comment by GermanBluefox** [comment]
> > ... and exactly because of thisthe change was done ... because packages stored with adapter configuration are back and reinstalled after restore
> 
> In my case it has been backed up cause I was using total backup from backitup (which seems to not be supported anymore). I noticed that the normal backup from iobroker doesn't contain the data directory.
> 
> In my opinion it would be a better way to handle it similar to the flows. Currently flows are stored in iobroker aswell via the saveObjects function. Can't we just save the package.json (from the iobroker-data/node-red folder) (and probably the lock aswell) as an object and restore it on launch as it is already done for flows and flows-cred?
> Or even better I think just use
> 
> ```
>         "dataFolder": "node-red"
> ```
> 
> as a common property for the instance? Even so that would include "node_modules" and make the backup very big. Maybe some kind of "dataIgnoreRegex" can be introduce to ignore the node_modules folder in backups?
> According to https://github.com/node-red/cookbook.nodered.org/wiki/How-to-backup-flows-and-related-configuration it just requires an "npm install" afterwards so we can check if node_modules exists and if not do an npm install after restoring the package.json
> 
> Edit:
> Also: There are way more things for a complete backup so I think we also need ".config.json" to keep things working as that contains the nodes and other configs like git credentials and projects! Actually if you really want a backup that works out of the box then the whole projects folder should be included aswell...
> 
> It's also good to know that as far as I can see currently projects are NOT backed up aswell. Only flows that are not part of a project. Projects do have a way to sync it with git but that's not required so right now iobroker backups don't contain projects aswell which should be considered to be backed up as the project feature is supported with this adapter.
> 
> Also if you use projects then dependencies ARE backed up with the project/git as dependencies and can be installed with a single click IF the pallet is enabled.
> 
> ![image](https://user-images.githubusercontent.com/5904171/85237449-40140700-b427-11ea-89ae-662f2889fda9.png)

I want to implement some custom scripts for backup.
Do all the modules are stored in node_modules/iobroker.node-red/package.json=>"dependencies"? 
Must we by every update of node-red to update this direactory anew?

**Comment by GermanBluefox** [comment]
> > Wie ist dein Vorschlag, außer "alles ist schlecht"?
> 
> Bitte einfach nur den Paletten-Manager aktivieren.
> Oder in den Einstellungen muss explizit der Paletten-Manager aktiviert werden.
> Und nicht böse sein, für manche ist dieser Punkt eben wichtig. ;-)

Ich verstehe nicht warum du nicht iobroker.node-red Konfig benutzen kannst? Vielleicht verstehe ich was nicht?
Wo kommt diese Information her? 
![image](https://user-images.githubusercontent.com/4582016/85331489-85dbd880-b4d6-11ea-8e91-8c1b83d44a4e.png)

**Comment by WolfspiritM** [comment]
> Do all the modules are stored in node_modules/iobroker.node-red/package.json=>"dependencies"?
> Must we by every update of node-red to update this direactory anew?

The modules installed by the pallet manager are not stored in that package json at all. The adapter creates a folder in ibroker-data called "node-red" (userDataDir) and in there is the package.json that contains the modules.

> Wo kommt diese Information her?
That information is stored with a project. A rather new feature of node-red that allows to create different projects with flows that can be synced with git for backup and restore. It's not available for "normal" oldschool flows without projects.
The projects are stored in iobroker-data/node-red/projects/[Projectname]/. In there is a "package.json" which seems to be used by node red to figure out the "dependent" modules. It doesn't do a npm install in that folder so but seems to add that dependencies to the "main" package.json in the iobroker-data/node-red folder.

**Comment by GermanBluefox** [comment]
> > Do all the modules are stored in node_modules/iobroker.node-red/package.json=>"dependencies"?
> > Must we by every update of node-red to update this direactory anew?
> 
> The modules installed by the pallet manager are not stored in that package json at all. The adapter creates a folder in iobroker-data called "node-red" (userDataDir) and in there is the package.json that contains the modules.
> 
> That also means that updates to the adapter and updates to node-red don't nuke the currently installed modules. The ONLY time modules get lost is when using backup and restore IF the iobroker-data folder is not backed up aswell.
> 
> > Wo kommt diese Information her?
> 
> That information is stored with a project. A rather new feature of node-red that allows to create different projects with flows that can be synced with git for backup and restore. It's not available for "normal" oldschool flows without projects.
> The projects are stored in iobroker-data/node-red/projects/[Projectname]/. In there is a "package.json" which seems to be used by node red to figure out the "dependent" modules. It doesn't do a npm install in that folder so but seems to add that dependencies to the "main" package.json in the iobroker-data/node-red folder.
> 
> According to node red the way to backup and restore is to just store the whole "node-red" folder except the node_modules folder. That way .config.json and all projects are included as they're not always synced with git.
> 
> > Ich verstehe nicht warum du nicht iobroker.node-red Konfig benutzen kannst
> 
> The problem is that the pallet manager is doing way more then that. It allows to search and filter node-red packages and often doesn't even require a whole restart of node red and all flows. Also it allows an easy way to update packages with a single click.
> 
> I think it's comparable to removing the Adapter tab from iobroker.admin and requiring users to add adapters by entering their name into a textbox followed by a whole iobroker restart.

Do you have an Idea, how we could implement it like:
- iobroker checks before the start if all npm modules from palette installed?

It will solve the problem with backup and we do not need add modules in iobroker configuration any more....

**Comment by WolfspiritM** [comment]
> Do you have an Idea, how we could implement it like:
> 
> * iobroker checks before the start if all npm modules from palette installed?

That depends. If we can backup and restore all required files (especially the package.json file, but I think even more files should be backed up for example the projects folder) from the userDataDir then all that needs to be done is to check if "node_modules" exists in userDataDir. If that's not the case then an npm i should be run in that folder.

https://github.com/node-red/cookbook.nodered.org/wiki/How-to-backup-flows-and-related-configuration
Here is also a list of important files and how to backup and restore them manually.

**Comment by Apollon77** [comment]
Side node: We need to make sure the node_modules is not backed up! Else symlinks will be killed and this will give problems after restore

**Comment by WolfspiritM** [comment]
> Side node: We need to make sure the node_modules is not backed up! Else symlinks will be killed and this will give problems after restore

I agree that node_modules shouldn't be backed up. Node-red even suggest excluding that folder from backup and doing an npm i after restore. However I wonder: What can create symlinks in that specific node_modules directory? I know that iobroker does some symlinking under the hood, but that iobroker-data/node-red/node_modules isn't connected to iobroker at all.

**Comment by ArchGithub** [comment]
> Ja, ich weiß ... aber was bringt es, die Pakete über iobroker zu verwalten?
> 
> Übrigens: Ich habe es in der settings.js (/opt/iobroker/node_modules/iobroker.node-red/) wieder aktiviert.
> 
> `palette: { editable: true }`

Leider kommt bei mir keine Berechtigung!

**Comment by vepman** [comment]
> 
> 
> Leider kommt bei mir keine Berechtigung!
>
Ich kann die settings.js zwar editieren, aber nach dem ersten Neustart von node-red wird "palette" wieder auf false gesetzt.
Wenn das nicht wäre, könnte man sich ja damit behelfen.

**Comment by bergjet** [comment]
> > Leider kommt bei mir keine Berechtigung!
> 
> Ich kann die settings.js zwar editieren, aber nach dem ersten Neustart von node-red wird "palette" wieder auf false gesetzt.
> Wenn das nicht wäre, könnte man sich ja damit behelfen.

Frage mal ReaverPhoenix, der dürfte das hinbekommen haben. Wenn es geht, sag Bescheid.

**Comment by MattL0** [comment]
Here , went back to Upgrade to 1.17.2 because I wanted the palette back, and not having to restart node red every time i add a package :P

**Comment by ReaverPhoenix** [comment]
> 
> 
> > Leider kommt bei mir keine Berechtigung!
> 
> Ich kann die settings.js zwar editieren, aber nach dem ersten Neustart von node-red wird "palette" wieder auf false gesetzt.
> Wenn das nicht wäre, könnte man sich ja damit behelfen.

Hej, ohja, das stimmt, dass er dann die Einstellung wieder auf 'false" setzt.

Daher muss auch im Pfad `/opt/iobroker/node_modules/iobroker.node-red/` die settings.js angepasst werden.

So funktioniert es bei mir:
1. `palette: { editable: true }`
 - `/opt/iobroker/iobroker-data/node-red/`
 - `/opt/iobroker/node_modules/iobroker.node-red/`

**Comment by MattL0** [comment]
What needs to be changed is settings.js in /iobroker/node_modules/iobroker.node-red

**Comment by ReaverPhoenix** [comment]
> 
> 
> What needs to be changed is settings.js in /iobroker/node_modules/iobroker.node-red

`palette: { editable: true }`

**Comment by jakolion** [comment]
Ich möchte an dieser Stelle noch erwähnen, dass die Installation von Modulen aktuellö nicht über die oben beschriebene Konfiguration über das UI funktioniert. Ein Issue dazu gibt es schon länger: #52

**Comment by thatso** [comment]
Nicht wirklich ... nach rund einem Jahr(!) ohne irgendeine Lösung wurde das Issue #52 einfach geschlossen und ich habe weiterhin genau das getan, was ich vorher tat: die Palette benutzen, weil die Installation übers UI schlicht nicht funktioniert.
Wie man hier sieht, funktioniert es weiterhin nicht, die Situation wurde aber durch den letzten unüberlegten Schnellschuß noch verschlimmert. Der Spottkommentar beim Schließen lautete übrigens "Please reopen if still exists", obwohl während der ganzen Zeit abolut NICHTS geändert oder gar verbessert wurde.
Überhaupt muß ich bei der Gelegenheit feststellen, daß ich mit ioBroker abgeschlossen habe. Meine persönliche Erfahrung nach zwei Jahren: miese, fehlende oder falsche Dokumentationen, horrende Rechtschreibfehler, überhebliches, selbstgefälliges oder herablassendes Benehmen der Programmierer, sofern Bug Tickets nicht gleich vollständig ignoriert werden - kurz: keinerlei Bezug zum Anwender.
Das Motto "Open Source lebt vom Mitmachen" scheint hier absolut nicht angekommen zu sein.

**Comment by WolfspiritM** [comment]
> Der Spottkommentar beim Schließen lautete übrigens "Please reopen if still exists", obwohl während der ganzen Zeit abolut NICHTS geändert oder gar verbessert wurde.

Das ist überhaupt kein Spottkommentar. Diese art von Kommentare sind auf Github sehr normal wenn ein Ticker länger offen ist und sich seit dem viel geändert hat. Es ist eine "Bitte" zu überprüfen ob das Problem noch existiert. Vorallem da 2 Monate vorher im Ticket gefragt wurde ob das Problem immernoch besteht und keine Antwort darauf kam.

> horrende Rechtschreibfehler

Es ist das kleinste einen Rechtschreibfehler ggf. selbst zu lösen. Das geht allein über Github ohne überhaupt irgendetwas auschecken zu müssen. ioBroker hat eine Übersetzung für 10 Sprachen. Da kann es einfach mal zu einem Übersetzungs- bzw. Rechtschreibproblem kommen. "Open Source lebt vom Mitmachen"

> selbstgefälliges oder herablassendes Benehmen der Programmierer, sofern Bug Tickets nicht gleich vollständig ignoriert werden - kurz: keinerlei Bezug zum Anwender.

Ich hab in letzter Zeit sehr viele Tickets aufgemacht in unterschiedlichen Adaptern mit Dingen die mich stören oder nicht funktionieren. So gut wie überall wurde innerhalb 24 Stunden geantwortet bzw. eine sinnvolle Diskussion gestartet. Ich kenne andere Projekte da wartet man über eine Woche auf Antwort die dann nur heißt "Bitte reproduzieren".

> Das Motto "Open Source lebt vom Mitmachen" scheint hier absolut nicht angekommen zu sein.

Wer oder Was hindert dich denn daran einen Merge Request aufzumachen wenn du "mitmachst" und Fehler behebst? Das mitmachen bei Open Source bezieht sich immerhin auf das selbst Fehler beheben. Fehler melden kann man in Closed Source Projekten genauso.

**Comment by Apollon77** [comment]
>  Ein Issue dazu gibt es schon länger und wurde geschlossen, weil sich der Ersteller des Issues entschieden hat die Palette stattdessen zu verwenden: #52

Ich habe das Ticket wieder geöffnet, da der Fehler ja wohl scheinbar noch besteht. Ein Kommentar in dem Thread damit hätte dies genauso gebracht

**Comment by Apollon77** [comment]
@thatso 
>  Das Motto "Open Source lebt vom Mitmachen" scheint hier absolut nicht angekommen zu sein.

Ich sehe das wie @WolfspiritM . Ich glaube DU hast das Motto falsch verstanden. Alle die hier mitarbeiten tun das in Ihrer Freizeit und betreuen teils mehrere Projekte.
Der Adapter hat 7800 Installationen, das Issue #52 hat 4 Kommentierer und KEINEN EINZIGEN "thumbs up" (so kennzeichnet man üblicherweise auf Github das man auch betroffen ist von einem Problem).

Wie würdest Du als Entwickler, der ggf nicht vom Problem betroffen ist und noch viele andere Projekt betreut, die Priorität dieses Issues bestimmen?

"Mitmachen" bedeutet im Open Soure Umfeld das auch die Nutzer mitmachen, wenn Sie können. Und selbst wenn Du nicht programmieren kannst sind, wie bereits gesagt, Rechtschreibfehler die Auffallen doch einfach zu beheben oder ?!
JEDER kann mitarbeiten das Projekt voranzubringen und zu unterstützen.

**Comment by jakolion** [comment]
> > Ein Issue dazu gibt es schon länger und wurde geschlossen, weil sich der Ersteller des Issues entschieden hat die Palette stattdessen zu verwenden: #52
> 
> Ich habe das Ticket wieder geöffnet, da der Fehler ja wohl scheinbar noch besteht. Ein Kommentar in dem Thread damit hätte dies genauso gebracht

Kurze Verständnisfrage: Gilt das nur für den Ersteller des Issues? Denn wie man sieht habe ich es heute kommentiert, aber es ist geschlossen geblieben.

**Comment by Apollon77** [comment]
> Kurze Verständnisfrage: Gilt das nur für den Ersteller des Issues? Denn wie man sieht habe ich es heute kommentiert, aber es ist geschlossen geblieben.

Das ist nichts automatisches. Wenn jemand von uns es gesehen hätte (wie jetzt passiert) können wir das wiederfänden oder der Ersteller manuell. Alternativ hilf das öffnen eines neuen issues immer ;-)
