### ISSUE TITLE
system.adapter.xxx.yyy  objects not working

### ISSUE THREAD

**Issue by cyberax17** [ioBroker/ioBroker.node-red#111]
Unfortunately in NR the use of system.adapter.xxx.yyy does not work any more. It is possible to pick the object as an input from ioBroker, but NR does not get any status information from ioB. This worked in the past but since some time not any more. 
"Normal" objects like adapterxy.xxx  work fine.

Nodered Adapter 2.0.0

**Comment by Apollon77** [comment]
Reason is this check for a validId:

https://github.com/ioBroker/ioBroker.node-red/blob/master/nodes/ioBroker.js#L42

**Comment by cyberax17** [comment]
Anything I can do to fix? Is it an ioB or NR issue?

**Comment by Apollon77** [comment]
It is in ioBroker code. I just had a short look and noted it down for reference ... We need to think about the solution ...

**Comment by mickym2** [comment]
I found out that for the system objects there will be a prefix added which creates a wrong path:

node-red/0/system/adapter/admin/0/alive

This is in my opinion the problem

**Comment by Apollon77** [comment]
Yes and the reason is the state id check referenced above ... this check interpret a system.adapter.* state as "local to node-red instance". So which "special states" are relevant?
* system.adapter.name.X
* system.host.name too?

What else?

**Comment by mickym2** [comment]
If you are asking which special states are relevant - I used all system.adapter.name.X, but may be the others which are accessible would be interessting in the future as well.
So the interpretation that a system.adapter.* state as "local to node-red instance". is new - as in Version 1.13. this was not the case and I had no problem to access these states. 

I do not know why this mapping is necessary in the newer versions - but may be that with an additional flag  all iobroker objects which are visible in iobroker expert mode could be made accessible as an exception.

**Comment by mickym2** [comment]
Any news?

**Comment by cyberax17** [comment]
Has this been solved in the meantime?

**Comment by mickym2** [comment]
No - status is still open. Why do you think - something has changed if status has not changed. 

You can test very easily: 

![image](https://user-images.githubusercontent.com/58858526/114705245-d05d6880-9d27-11eb-9511-66fdc2421edc.png)

There is still no output.

**Comment by cyberax17** [comment]
What a pity. Thought there would be a workaround or something... Thanks

**Comment by mickym2** [comment]
I have a workaround: Create aliases of your system.adapter datapoints you want to subscribe. This is what I do at this moment.

**Comment by cyberax17** [comment]
This is a good one - Thank you @mickym2 ! :-)

**Comment by Apollon77** [comment]
Will be fixed in upcoming version

**Comment by Apollon77** [comment]
Released in 3.0.0
