### ISSUE TITLE
Palette verwalten fehlt in 2.0.0

### ISSUE THREAD

**Issue by ihavenonick** [ioBroker/ioBroker.node-red#113]
In der Liste rechts oben fehlt "Palette verwalten", somit kann ich mit der Version 2.0.0 keine Nodes nach installieren, was unter 1.17.2 sehr einfach über diesen Weg möglich war.
1.17.2
![grafik](https://user-images.githubusercontent.com/36501310/86327877-3d45bd00-bc44-11ea-8c4c-d9cb36cbc47c.png)

2.0.0
![grafik](https://user-images.githubusercontent.com/36501310/86328222-c4933080-bc44-11ea-95c9-1530595e71af.png)

**Comment by thost96** [comment]
Duplikat von #109 , schau mal dort rein. Dort wird auch ein Workaround definiert.

**Comment by ihavenonick** [comment]
Alles klar, hat geklappt und hier noch mal die Lösung bevor der nächste sich dort dusselig sucht :-)
Also recht einfach, es müssen zwei Dateien wie folgt angepasst werden:

    palette: { editable: true }        (false nach true ist am Ende der Datei)

    /opt/iobroker/iobroker-data/node-red/
    /opt/iobroker/node_modules/iobroker.node-red/

**Comment by dnalyalp** [comment]
> Alles klar, hat geklappt und hier noch mal die Lösung bevor der nächste sich dort dusselig sucht :-)
> Also recht einfach, es müssen zwei Dateien wie folgt angepasst werden:
> 
> ```
> palette: { editable: true }        (false nach true ist am Ende der Datei)
> 
> /opt/iobroker/iobroker-data/node-red/
> /opt/iobroker/node_modules/iobroker.node-red/
> ```

Wenn du jetzt noch dazu schreiben würdest, dass es die settings.js ist, wäre es perfekt :) Ist nämlich so ziemlich der erste Treffer, wenn man über google kommt. Danke für die Hilfe!

**Comment by ihavenonick** [comment]
Oh, hatte ich vergessen und Google weiß das mittlerweile ja auch, nur im Juli nach der Umstellung, war das leider noch nicht der Fall ;-)
