### ISSUE TITLE
NOdered 1.1 is out!!

### ISSUE THREAD

**Issue by MattL0** [ioBroker/ioBroker.node-red#114]
There are some significative change to the ui here. Hope it’ll not be to hard to update iobroker package to it.

**Comment by Apollon77** [comment]
Are there any details for compatibility? Is any configuration update needed?

**Comment by MattL0** [comment]
I have updated it on another machine. Didn't have to touch anything

**Comment by mickym2** [comment]
Some nodes are no longer working with version 1.1.x - i already updated issues I found in git hub [Light Scheduler](https://github.com/niklaswall/node-red-contrib-light-scheduler/issues/52)

**Comment by MattL0** [comment]
Seems to be fixed now
