### ISSUE TITLE
Sense Hat Node benötigt root um Python Skript zu starten

### ISSUE THREAD

**Issue by lcars79** [ioBroker/ioBroker.node-red#119]
Ich habe ein Problem mit dem ioBroker.node-red. Ich möchte die Node https://github.com/node-red/node-red-nodes/tree/master/hardware/sensehat verwenden um meinen Sense Hat auszulesen. Wenn ich Node-Red normal außerhalb von ioBroker installiere klappt alles ohne Probleme. Wenn ich das gleiche innerhalb von ioBroker machen will dann bekomme ich Fehler im Log: 

node-red.0 | 2020-08-04 20:27:46.427 | error | (31155) 4 Aug 19:27:46 - [error] err: sudo: no tty present and no askpass program specified :
-- | -- | -- | --
node-red.0 | 2020-08-04 20:27:46.424 | error | (31155) 4 Aug 19:27:46 - [error] err: We trust you have received the usual lecture from the local System Administrator. It usually boils down to these three things: #1) Respect the privacy of ot
node-red.0 | 2020-08-04 20:27:41.315 | error | (31155) 4 Aug 19:27:41 - [error] err: sudo: no tty present and no askpass program specified :
node-red.0 | 2020-08-04 20:27:41.313 | error | (31155) 4 Aug 19:27:41 - [error] err: We trust you have received the usual lecture from the local System Administrator. It usually boils down to these three things: #1) Respect the privacy of ot
node-red.0 | 2020-08-04 20:27:36.230 | error | (31155) 4 Aug 19:27:36 - [error] err: sudo: no tty present and no askpass program specified :
node-red.0 | 2020-08-04 20:27:36.229 | error | (31155) 4 Aug 19:27:36 - [error] err: We trust you have received the usual lecture from the local System Administrator. It usually boils down to these three things: #1) Respect the privacy of ot
...

Ich konnte das Problem soweit eingrenzen, dass es an diesem File in der Node liegt: https://github.com/node-red/node-red-nodes/blob/master/hardware/sensehat/sensehat
Im Prinzip wird da per sudo ein Python Skript gestartet was den Zugriff auf die Hardware macht. Der ioBroker User kann hier aber nicht wohl kein sudo machen.

Wie kann ich das am Besten lösen damit es läuft?

**Comment by Apollon77** [comment]
AM besten melde dich mal im Forum .. da gibt es mehrere Experten die die sagen können wir du die sudo konfig erweitern kannst das der iobroker user das darf - bzw es gab schon solche Fälle, vllt hilft die Suche dort auch.
Gern hier das Ergebnis posten

**Comment by lcars79** [comment]
Hallo @Apollon77 ,

die Suche im Forum hat mich auf den richtigen Pfad gebracht. Die sudo Erlaubnisse werden ja in der /etc/sudoers.d/iobroker Datei gespeichert. Hier muss dem iobroker User erlaubt werden python mit sudo auszuführen da das das sense-hat Node benötigt. D.h. man muss hier diese Zeile einfügen:

iobroker ALL=(ALL) NOPASSWD: /usr/bin/python

Ggf. könnt ihr das ja beim nächsten Update vielleicht mit einbauen dann geht bei alles dann falls da auch andere Python Skripte so gestartet werden müssen.

Gruß
Frank Zimmermann

**Comment by Apollon77** [comment]
Das wäre ggf ein Issue im ioBroker/ioBroker GitHub Projekt ... da muss man mal diskutieren welche Sicherheitslöcher man da reisst
