### ISSUE TITLE
MaxListenersExceededWarning in einem größeren Projekt

### ISSUE THREAD

**Issue by gregor-samosir** [ioBroker/ioBroker.node-red#123]
Beim jedem deploy eines etwas größeren NR Projektes mit > 500 nodes verteilt auf 15 flow-tabs erhalte ich folgende Warnung im Log des IOBroker:

(22226) (node:22241) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 101 stateChange listeners added to [Adapter]. Use emitter.setMaxListeners() to increase limit

**Comment by Apollon77** [comment]
Also an sich sollte das Limit 1000 sein für den nodejs prozess

https://github.com/ioBroker/ioBroker.node-red/blob/master/nodes/ioBroker.js#L20

**Comment by gregor-samosir** [comment]
Ja, gesehen habe ich das auch. Ich bin noch unter dem Limit von 1000.

Ich versuche das einzugrenzen und einzelne Flow-Tabs auf disabled zu schalten.

**Comment by gregor-samosir** [comment]
Es sieht für mich so aus, als würde ich sogar über das Limit von 1000 kommen. Wenn ich einzelne Tabs auf disable stelle, dann ist die Warnung weg. Es ist aber kein bestimmtes Tab, sodaß ich annehmen kann das hier kein Fehler auf einem einzelnen Tab ist.
Kann ich das an der gezeigten Stelle testhalber einfach mal auf 2000 stellen?

**Comment by Apollon77** [comment]
Versuch mal. Wenn es hilft dann sehe ich es noch höher im nächsten Update

**Comment by gregor-samosir** [comment]
> Versuch mal. Wenn es hilft dann sehe ich es noch höher im nächsten Update

Habe das limit auf 2000 gesetzt und alles neu gestartet.
Hat nichts geändert, die Warnung bleibt.

**Comment by Apollon77** [comment]
hast Du mal das ganze log? die Frage ost ob das vllt der Adapter prozess ist obwohl es da eigentlich nicht sein sollte ...

**Comment by gregor-samosir** [comment]
Ein Log mit NR auf silly log gibt nicht viel her:

`

node-red.0 | 2020-09-23 23:10:03.625 | debug | (27299) 23 Sep 23:10:03 - [info] [inject:Trigger 15 sec] Wiederholen = 15000
-- | -- | -- | --
node-red.0 | 2020-09-23 23:10:03.537 | warn | (27299) (node:27314) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 101 stateChange listeners added to [Adapter]. Use emitter.setMaxListeners() to increase limit
node-red.0 | 2020-09-23 23:10:03.512 | debug | (27299) 23 Sep 23:10:03 - [info] Flows gestartet

`

Das System hat folgende Config:

`

node-red.0 | 2020-09-23 23:05:53.720 | debug | (27299) 23 Sep 23:05:53 - [info] Aktives Projekt: HeishaKaskade
-- | -- | -- | --
node-red.0 | 2020-09-23 23:05:53.409 | silly | (27299) States system redis pmessage io.system.adapter.node-red.0.logLevel/io.system.adapter.node-red.0.logLevel:{"val":"silly","ack":true,"ts":1600895153397,"q":0,"from":"system.adapter.node-red.0","
node-red.0 | 2020-09-23 23:05:53.409 | silly | (27314) States system redis pmessage io.system.adapter.node-red.0.logLevel/io.system.adapter.node-red.0.logLevel:{"val":"silly","ack":true,"ts":1600895153397,"q":0,"from":"system.adapter.node-red.0","
node-red.0 | 2020-09-23 23:05:53.345 | debug | (27314) statesDB connected
node-red.0 | 2020-09-23 23:05:53.343 | debug | (27314) States connected to redis: host.docker.internal:6379
node-red.0 | 2020-09-23 23:05:53.191 | debug | (27299) 23 Sep 23:05:53 - [info] Server wird jetzt auf http://127.0.0.1:1880/ ausgeführt.
node-red.0 | 2020-09-23 23:05:53.100 | debug | (27299) 23 Sep 23:05:53 - [info] Benutzerverzeichnis: /opt/iobroker/iobroker-data/node-red/
node-red.0 | 2020-09-23 23:05:53.098 | debug | (27299) 23 Sep 23:05:53 - [info] Einstellungsdatei: /opt/iobroker/iobroker-data/node-red/settings.js 23 Sep 23:05:53 - [info] Kontextspeicher: 'default' [ module=memory]
node-red.0 | 2020-09-23 23:05:51.226 | debug | (27299) 23 Sep 23:05:51 - [info] Dashboard version 2.23.3 started at /ui
node-red.0 | 2020-09-23 23:05:46.659 | debug | (27299) 23 Sep 23:05:46 - [info] Polymer started at /polymer
node-red.0 | 2020-09-23 23:05:33.924 | debug | (27299) 23 Sep 23:05:33 - [info] Paletten-Nodes werden geladen
node-red.0 | 2020-09-23 23:05:33.650 | debug | (27299) 23 Sep 23:05:33 - [info] Linux 4.19.76-linuxkit x64 LE
node-red.0 | 2020-09-23 23:05:33.644 | debug | (27299) 23 Sep 23:05:33 - [info] Node.js Version: v12.18.4
node-red.0 | 2020-09-23 23:05:33.641 | debug | (27299) 23 Sep 23:05:33 - [info] Node-RED Version: v1.1.3
node-red.0 | 2020-09-23 23:05:33.635 | debug | (27299) 23 Sep 23:05:33 - [info] Willkommen bei Node-RED! ===================
node-red.0 | 2020-09-23 23:05:27.349 | info | (27299) Starting node-red: --max-old-space-size=1024 /opt/iobroker/node_modules/node-red/red.js -v --settings /opt/iobroker/iobroker-data/node-red/settings.js
node-red.0 | 2020-09-23 23:05:26.343 | silly | (27299) States system redis pmessage io.system.adapter.node-red.0.logLevel/io.system.adapter.node-red.0.logLevel:{"val":"silly","ack":true,"ts":1600895126293,"q":0,"from":"system.adapter.node-red.0","
node-red.0 | 2020-09-23 23:05:26.251 | info | (27299) starting. Version 2.0.1 in /opt/iobroker/node_modules/iobroker.node-red, node: v12.18.4, js-controller: 3.1.6
host.iobroker_neu | 2020-09-23 23:05:23.388 | info | instance system.adapter.node-red.0 started with pid 27299

`

**Comment by gregor-samosir** [comment]
Das Problem besteht leider immer noch.

**Comment by mickym2** [comment]
Mit der neuesten Version (aus GitHub) - Adapter 2.0.4. scheint es bei mir nun behoben zu sein.

**Comment by Apollon77** [comment]
2.1.0 kommt jetzt

**Comment by gregor-samosir** [comment]
Konnte es leider wegen Krankheit nach nicht testen.

**Comment by gregor-samosir** [comment]
Alles bestens, mit 2.1.0 tritt das Problem nicht mehr auf.
