### ISSUE TITLE
error on startup nodered

### ISSUE THREAD

**Issue by koburg** [ioBroker/ioBroker.node-red#126]
I got this from the log when nodered try start. 
it worked and then it do not.

got the newest version installed of nodered.

`

node-red.0 | 2020-10-28 18:53:59.361 | info | (13353) node-red exited with 6
-- | -- | -- | --
node-red.0 | 2020-10-28 18:53:58.781 | warn | (17024) Terminated (UNCAUGHT_EXCEPTION): Without reason
node-red.0 | 2020-10-28 18:53:56.754 | warn | (13353) 28 Oct 18:53:56 - [warn] Projects disabled : editorTheme.projects.enabled=false
node-red.0 | 2020-10-28 18:53:35.704 | info | (13353) Starting node-red: --max-old-space-size=128 /opt/iobroker/node_modules/node-red/red.js -v --settings /opt/iobroker/iobroker-data/node-red/settings.js
node-red.0 | 2020-10-28 18:53:30.702 | info | (13353) node-red exited with 6
node-red.0 | 2020-10-28 18:53:30.065 | warn | (16752) Terminated (UNCAUGHT_EXCEPTION): Without reason
node-red.0 | 2020-10-28 18:53:29.062 | error | at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1145:16)
node-red.0 | 2020-10-28 18:53:29.062 | error | (16752) Error: connect ECONNREFUSED 127.0.0.1:1400
node-red.0 | 2020-10-28 18:53:29.061 | error | (16752) unhandled promise rejection: connect ECONNREFUSED 127.0.0.1:1400
Unhandled | 2020-10-28 18:53:29.059 | error | promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

`

**Comment by Apollon77** [comment]
DO you maybe use any block or such that does "connect ECONNREFUSED 127.0.0.1:1400" ?! and maybe that block is not corectly handling errors? Nothing in iobroker or node-red core is doing this ...
