### ISSUE TITLE
Dashboard /ui/ no basicAuth anymore

### ISSUE THREAD

**Issue by SliX185** [ioBroker/ioBroker.node-red#127]
Is there a way, to get back any authentification in version 2.0.1? 
usually the dashboard /ui was secured bei basicAuth like the NodeRed Admin panel.
Like mentioned in issue #58 and PR #99 the authentification was changed, 
but why there is no longer a chance to secure the dashboard?

Thanks in advance

**Comment by jwiesel** [comment]
Hi @SliX185 ,
Node-Red separated authentication between the admin panel and the Dashboard/"HTTP In Nodes".
See also the discussion here: https://discourse.nodered.org/t/login-and-password-in-dashboard-localhost-1880-ui/2132/17
One option would be setting httpNodeAuth in settings.js, which could have different credentials than adminAuth.
Consequence would be, that HTTP In nodes would only be accessible using authentication as well.

**Comment by SliX185** [comment]
@jwiesel 
thank you for answering!

...well, my solution was / is ... 
I already have a different virtualisation in place. I don't use Node Red UI anymore.

@Apollon77 Close?
