### ISSUE TITLE
Input node not firing at start

### ISSUE THREAD

**Issue by SaimenSays** [ioBroker/ioBroker.node-red#131]
Hello,

I have a problem with input node. There is the option "Fire by start: Send message by start" available on input node. But on restart of node-red adapter in ioBroker, there is no message. The status says "connected" as long as there is no update of data. After first update, the input node works as expected.

I'm using some input nodes to enable dashboard elements. When the connected device in ioBroker does not update its online state cyclic, my dashboard ui stays disabled, because there is no input on restart of node-red. If I use the ioBroker get node with a repeating inject node my flow works. But of course polling should not be the way to go.

**Comment by frankyboy1973** [comment]
Hi, same problem here. The Nodes only fire on deploy or when use "Restart Flows" in menü "Deploy".
@SaimenSays I am using the injekt node with "Started!" then it only fires once after an adapter restart
`[
    {
        "id": "9ecda82e.404638",
        "type": "inject",
        "z": "7770b3ac.936ecc",
        "name": "",
        "props": [
            {
                "p": "payload",
                "v": "Started!",
                "vt": "str"
            },
            {
                "p": "topic",
                "v": "",
                "vt": "string"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": true,
        "topic": "",
        "payload": "Started!",
        "payloadType": "str",
        "x": 180,
        "y": 160,
        "wires": [
            [
                "5687ae64.2e548"
            ]
        ]
    }
]`

**Comment by Apollon77** [comment]
How the nodes are condifured? The "fire on start" will NOT work if you use wilfcards in the string. it only is done when a concrete ID is set

**Comment by frankyboy1973** [comment]
Hi, i am not using wildcards with inject nodes, here an example.
Hallo, ich benutze keine Wildcards bei meinen Injekt Nodes. Hier ein Beispiel dazu.
Wenn ich eine Injekt Node neu erstelle oder ändere, feuert sie nach dem Deploy. Bei Adapter Neustart oder System reboot kommt da aber nichts. Erst wenn der Wert aktualisiert oder geändert wird, gibts ne Ausgabe von Injekt Node. Und das ist bei allen Injekt Nodes bei mir so. Und ich habe da einige in Benutzung, wobei ich den Fire On Start nicht für alle brauche, aber bei einigen wäre es schon schön, wenn sie nach einem Neustart ihren Status feuern.
Ich hoffe es ist OK wenn ich in Deutsch schreibe, sonst können wir auch auf Englisch weitermachen, da bin ich aber leider nicht so gut drin.
![Start1](https://user-images.githubusercontent.com/46169800/110240871-364b1900-7f4e-11eb-8053-a02fa371cc65.jpg)
![Start2](https://user-images.githubusercontent.com/46169800/110240885-3e0abd80-7f4e-11eb-96a2-cdbcea1985e7.jpg)

**Comment by Apollon77** [comment]
Bitte Github version installieren, manuell adapter neu starten und versuchen

**Comment by frankyboy1973** [comment]
Wow, das ging ja fix. Es funktioniert, die Injekt Nodes (wenn so konfiguriert) feuern jetzt bei Adapter bzw. System Neustart. Vielen Dank.
