### ISSUE TITLE
iobroker out - "/" is replaced by "."

### ISSUE THREAD

**Issue by TiDO2k** [ioBroker/ioBroker.node-red#133]
i use the "iobroker out" node
the TOPIC includes a "/" in the varible name.

Node-Red replaces the "/" by an "."

TOPIC: state 0.volvo.abc.preclimatazation/start 

node-red will transform it to:
state 0.volvo.abc.preclimatazation.start 

Can this be fixed?

**Comment by Apollon77** [comment]
No, a "/" is not a valid character in an object in iobroker and thats why the"." is kind of the same separater in iobroker
