### ISSUE TITLE
msg.stateRole wird nicht in den Datenpunkt übernommen

### ISSUE THREAD

**Issue by BerndAllgaeu** [ioBroker/ioBroker.node-red#134]
Hallo zusammen!

Ich habe das Problem das die "Rolle" aus Node Red heraus nicht in den Datenpunkten eingetragen wird, wenn diese über die Message definiert sind. Mittlerweile habe ich herausgefunden, dass der Fehler nur auftritt, wenn in der Message das "Array" (siehe unten) mit enthalten ist.
Also mit "Aufgeräumter" Message funktioniert es... 

> {
> 	"payload": 0,
> 	"_msgid": "baf7045e.976118",
> 	"split": ["KG.Waschküche.Waschküche","switch.light","0",""],
> 	"topic": "KG.Waschküche.Waschküche",
> 	"stateRole": "switch.light"
> }

Vielen Dank!

Gruß Bernd

**Comment by Apollon77** [comment]
Bitte mehr Infos. wie ist der flow? Node konfig?  Das split sollte egal sein
