### ISSUE TITLE
iobroker Out - Nodestatus wird nur bei "deploy" aktualisiert - danach nicht mehr

### ISSUE THREAD

**Issue by MacPro-de** [ioBroker/ioBroker.node-red#138]
Hallo,

wie bereits im Subject angegeben habe ich ein Problem mit der iobroker Out Node.

Der Nodestatus (der kleine Wert, der unter der Node erscheint, wenn man das in den Einstellungen aktiviert hat) wird bei mir nur direkt nach "deploy" aktualisiert - danach jedoch nicht mehr. Das ist zwar eher ein kosmetisches Problem, denn man kann den Wert ja auch über eine Debug-Node ausgeben lassen, aber es ist doch zumindest unschön und es hat mich doch etwas Zeit gekostet, herauszufinden, dass die iobroker Objekte zwar alle korrekt aktualisiert wurden, aber eben nur unter der Node selbst der "alte" Wert stehen blieb. Das scheint in der Tat auch nur bei der Node "iobroker Out" zu passieren. Hat noch jemand dieses Problem oder bin ich da der einzige?

Direkt nach "deploy":

![nachDeploy](https://user-images.githubusercontent.com/77443523/105376196-c97ff780-5c09-11eb-9340-e68c47d0572f.png)

Nach der Aktualisierung eines Ausgangswerts:

![nachAktualisierungderAusgangswerte](https://user-images.githubusercontent.com/77443523/105376305-e4eb0280-5c09-11eb-9ab1-94f4ff242a75.png)

**Comment by Apollon77** [comment]
Please try GitHub version afte rthe issue got closed by next commit
