### ISSUE TITLE
http-Static in Adapterkonfiguration

### ISSUE THREAD

**Issue by mickym2** [ioBroker/ioBroker.node-red#142]
Kann man aus der settings.js den Parameter: 

// When httpAdminRoot is used to move the UI to a different root path, the
// following property can be used to identify a directory of static content
// that should be served at http://localhost:1880/.
//**httpStatic**: '/home/nol/node-red-dashboard/',

Also Parameter in die Adapterkonfiguration aufnehmen, so dass man nicht nach jedem Update, die settings.js manuell anpassen muss?

**Comment by jwiesel** [comment]
Hi @mickym2 ,
I just checked your requirement. There are two different parameters in settings.js in Node-Red 2.x going in a similar direction. 
1. ui: { path: "ui" }, // Used for Node-Red-Dashboard
2. httpStatic: '/home/nol/node-red-static/', //Used for static contents

Which one of them would you like to set in the instance settings?

**Comment by mickym2** [comment]
I think these are 2 complete different settings. The path ui is how the dashboard is addressed. The httpStatic however is used to store and that the dashboard finds external resources. **However the path to the dashboard remains the same and will not change with httpStatic path.**

As I kept the ui path always at it is - and if you ask me which I personally would prefer then I would prefer the http-Static path - otherwise I have to modify this in settings.js each time I have updated the adapter. 

But in my opinion both adapters have different meanings.

**Comment by jwiesel** [comment]
Fully agree.
My idea was to put httpAdmin to "/admin" and instead ui to "/" to have a shorter URL for the dashboard. In that case both settings would point to the base-url of NodeRed.
Thanks for clarifying. Adding a new parameter for httpStatic should not be an issue. A similar implementation has been done for SSL. If the field is empty, it would get commented out in settings.js, otherwise the value entered in the instance settings would get set.
https://github.com/ioBroker/ioBroker.node-red/blob/c09acb7cb7384dd8659142664726572b316acedf/settings.js#L158

**Comment by mickym2** [comment]
As already mentioned - I would keep the ui path as it is and using / for the admin. When i use the standalone NodeRed version - I have the same behaviour and I think it can be confusing to change this behaviour. In addition the node-red dashboard is not part of the core nodes and may be that some users have not even installed the dashboard and are using NodeRed only as logic machine. - 

So for me adding the httpStatic parameter exactly how you described it in addition, would be sufficient.

**Comment by jwiesel** [comment]
Please test via install URL in #252

**Comment by mickym2** [comment]
So I test it and in principle it is working. 

2 comments:

1. It seems that the existing settings of an exiting settings.js is not taken over. It would be no problem, if in future versions this is part of an adapter configuration parameter is kept for future updates.

2. I do not know if the comment from setting.js is confusing. For a normal iobroker user - the term "_when http root is changed,_ ...". I know that users may think they have to do something in addition, which is not the case.
I would use the explanation part of the settings.js: "_the http-static parameter can be used to identify a directory of static content on local host_"

**Comment by jwiesel** [comment]
Thanks for testing @mickym2 !
In the meantime the other enhancements (value convert and NodeRed 2.1.4) have been merged. Therefore the install link in #252 now contains all 3 features.
Regarding your comments:

1. Not sure, if I understand your point correctly. We introduce a new setting into the adapter (in this case httpStatic). Other settings should not be impacted by that. Do you have a concrete example what gets lost?
2. I updated the help-text per your suggestion.

**Comment by Apollon77** [comment]
Released in 3.0.0
