### ISSUE TITLE
Wildcards are not supported in a consitent way

### ISSUE THREAD

**Issue by mickym2** [ioBroker/ioBroker.node-red#143]
I am not able to get any messages when I use wildcards in the iobroker in nodes. Only in iobroker list nodes the wildcards are working as expected. However I saw from other users that they are able to use wildcards in iobroker in nodes as well. I have no idea what the problem is - I saw nothing strange in the logs or in the adapter configuration.

**Comment by thost96** [comment]
Hi, I'm also using wildcards, e.g. this one: 0_userdata.0.tv-philips.* , which is working fine. 
Which format do you use in the iobroker-in nodes?

**Comment by mickym2** [comment]
I am using the same format - not only at the end (e.g. **mqtt.1.shellies.*.relay.0.energy**). Here I know that the objects will be updated every minute. And its working fine in the iobroker-in node without wildcards like mqtt.1.shellies.shelly1pm-123456.relay.0.energy. The wildcards are also working fine in the iobroker-list nodes. When I use the same string  **mqtt.1.shellies.*.relay.0.energy**, I get also all values - the problem is I have to trigger this node - so I am polling and cannot subscribe to topics with wildcards as it is working for iobroker-in nodes without wildcards.

**Comment by mickym2** [comment]
So meanwhile I found out - that wildcards (*) at the end of an object path in iobroker-IN node works fine. But not within a path. In the list it works always - in getNodes never. 

![screen](https://user-images.githubusercontent.com/58858526/107674803-a6d88000-6c97-11eb-928b-793b7344232c.png)

**Comment by Apollon77** [comment]
I think I found the issue ... the conversion of "wildcard inside the text" to regex was wrong. Please try Github version once the issue gets closed by my next commit

**Comment by mickym2** [comment]
Hallo Ingo, 

ich kann das leider nicht testen – von GitHub installiert über iobroker Dialog. Taucht aber nichts im LOG auf.

Im Update Fenster keine Fehler: 

$ ./iobroker url "https://github.com/ioBroker/ioBroker.node-red/tarball/master" node-red --debug
install ioBroker/ioBroker.node-red#master
NPM version: 6.14.11
npm install ioBroker/ioBroker.node-red#master --loglevel error --prefix "/opt/iobroker" (System call)
+ iobroker.node-red@2.1.0updated 1 package in 68.104s

74 packages are looking for funding  run `npm fund` for details
upload [4] node-red.admin /opt/iobroker/node_modules/iobroker.node-red/admin/words.js words.js application/javascript
upload [3] node-red.admin /opt/iobroker/node_modules/iobroker.node-red/admin/node-red.png node-red.png image/png
upload [2] node-red.admin /opt/iobroker/node_modules/iobroker.node-red/admin/index_m.html index_m.html text/html
upload [1] node-red.admin /opt/iobroker/node_modules/iobroker.node-red/admin/index.html index.html text/html
upload [0] node-red.admin /opt/iobroker/node_modules/iobroker.node-red/admin/bcrypt.min.js bcrypt.min.js application/javascript
process exited with code 0


Kein verändertes Verhalten bislang feststellbar. 

Gruß Michael

Von: Ingo Fischer
Gesendet: Sonntag, 7. März 2021 13:43
An: ioBroker/ioBroker.node-red
Cc: mickym2; Author
Betreff: Re: [ioBroker/ioBroker.node-red] Wildcards are not supported in aconsitent way (#143)

Closed #143 via 4aee6f8.

**Comment by Apollon77** [comment]
Bitte den adapter einmal manuell neu starten danach!

**Comment by mickym2** [comment]
Na ich habe es nun ein drittes Mal installiert und iobroker nochmal komplett neu gestartet und nun funktioniert es für die 2 Issues (bis auf eine Kleinigkeit 😉 ).

Vielen lieben Dank!!!

Bei den Wildcards funktioniert nun alles bis auf die get-Nodes – da ist wohl die Verwendung von Wildcards generell nicht vorgesehen?
Damit kann man aber leben, da man dafür die list Nodes nehmen kann mit value nehmen kann. Ansonsten schreibe ich nochmal zu den anderen Problemen, wobei ich die Anmerkungen teilweise nicht nachvollziehen kann. 😉

Also Danke nochmals für die Behebung das mit den Wildcards bei den in-Nodes ist eine Riesenverbesserung.

Gruß Michael 


Von: Ingo Fischer
Gesendet: Sonntag, 7. März 2021 14:10
An: ioBroker/ioBroker.node-red
Cc: mickym2; Author
Betreff: Re: [ioBroker/ioBroker.node-red] Wildcards are not supported in aconsitent way (#143)

Bitte den adapter einmal manuell neu starten danach!

**Comment by Apollon77** [comment]
Exakt "get node" geht nur mit einem echtenstate. Du wolltest einen Fehler im Log sehen wenn du was anderes abfragst

**Comment by mickym2** [comment]
OK! Fehler im Log sehe ich zwar keine, wenn ich die getNodes mit Wildcards füttere, aber man muss es ja nur wissen. 😉

Gesendet von Mail für Windows 10

Von: Ingo Fischer
Gesendet: Sonntag, 7. März 2021 14:43
An: ioBroker/ioBroker.node-red
Cc: mickym2; Author
Betreff: Re: [ioBroker/ioBroker.node-red] Wildcards are not supported in aconsitent way (#143)

Exakt "get node" geht nur mit einem echtenstate. Du wolltest einen Fehler im Log sehen wenn du was anderes abfragst

**Comment by thohoj** [comment]
I'm using the adapters 
hm-rpc v1.15.12
node-red v3.3.1

This topic works for an ioBroker in node:
`hm-rpc/0/*/1/STATE`

This does not work:
`hm-rpc/*/*/1/STATE`

**Comment by Apollon77** [comment]
@thohoj commenting to an issue that is closed since over a year is not visible, so most likely ignored ...

In fact this is a limitation because having the wildcard in the "adapter namespace" itself (hm-rpc.X) breaks the detection if an state from a provided namespace is subscribed or "the own node-red namespace".

If you want to have that checked and pot covered please open a new feature request issue
