### ISSUE TITLE
Alexa Smart Home devices trigger by themselves (switching without Alexa command)

### ISSUE THREAD

**Issue by Domi920** [ioBroker/ioBroker.node-red#151]
Hi,
Since I'm not sure whether this problem belongs here, I created it in the node-red palette (node-red-contrib-amazon-echo) in Github:
https://github.com/datech/node-red-contrib-amazon-echo/issues/167

Thanks in advance!

Greetings Dominik

**Comment by Apollon77** [comment]
lets see the outcome in the other issue. if it triggers in alexa nodes then iobroker is out
