### ISSUE TITLE
Naming of msg.stateReadonly is wrong

### ISSUE THREAD

**Issue by mickym2** [ioBroker/ioBroker.node-red#153]
In the newer versions it is possible to create objects via the iobroker out node. The type and other parameters can be specified by different message properties in the msg object which will be send to the iobroker out node. One of this parameters ist msg.stateReadonly as boolean. This defines the state ob the object in common.write and has therefore the opposite meaning. 

Currently you have to set msg.stateReadonly to true to get a writable object and false to get a readonly object.

**Comment by Apollon77** [comment]
hm ... the code looks ok:

```
            common.write = !(msg.stateReadonly === false || msg.stateReadonly === 'false');
```

**Comment by Apollon77** [comment]
The part that looks wrong is indeed:

```
            write: node.objectPreDefinedReadonly,
```

**Comment by mickym2** [comment]
No - it is exactly wrong if I look to this code.
So if i set stateReadOnly to true, I would expect that common write =  false and I am not able to write!

However if I look to this code - the comparision would result in a false, which will be negated therefore with not would mean the result is  true and therefore common.write= true, which I would expect as false; 

If i set stateReadOnly to false, I would expect that I am able to write and common.write = true.

However if I look to this code - the comparison would result in true which will be negated and therefore common.write = false.

It is a naming problem or should work in the opposite direction or the rename stateReadOnly in stateWritable

**Comment by Apollon77** [comment]
äähhmm ... yes ... I think it was simply too late yesterday ;-))

**Comment by Apollon77** [comment]
Please try Github version once the issue gets closed by my next commit
