### ISSUE TITLE
Setup fails on freebsd

### ISSUE THREAD

**Issue by dotbanana** [ioBroker/ioBroker.node-red#154]
$ ./iobroker add node-red  --host ioBroker
NPM version: 6.14.8
npm install iobroker.node-red@2.1.0 --loglevel error --unsafe-perm --prefix "/opt/iobroker" (System call)
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for node-disk-info@1.1.0: wanted {"os":"linux,win32,darwin","arch":"any"} (current: {"os":"freebsd","arch":"x64"})
npm ERR! notsup Valid OS:    linux,win32,darwinnpm ERR! notsup Valid Arch:  anynpm ERR! notsup Actual OS:   freebsdnpm ERR! notsup Actual Arch: x64

npm ERR! A complete log of this run can be found in:npm ERR!     /home/iobroker/.npm/_logs/2021-03-06T14_18_38_490Z-debug.log
ERROR: host.ioBroker Cannot install iobroker.node-red@2.1.0: 1
ERROR: process exited with code 25

**Comment by Apollon77** [comment]
very interesting ... it is a sub dependency ... https://github.com/Argonne-National-Laboratory/node-red-contrib-os/issues/11 ... only idea would be to add that lib as optionalDependency ...

**Comment by Apollon77** [comment]
@dotbanana Could you try  to "npm install @ekristoffe/node-red-contrib-os" ... does that work on your system? best execute that in /opt/iobroker/node_modules/iobroker.node-red
