### ISSUE TITLE
Node red Gui freezes during loading nodes

### ISSUE THREAD

**Issue by lighthousehh** [ioBroker/ioBroker.node-red#157]
I have a problem with the adapter 
The GUI is freezing during loading:     <Loading Nodes 34/81>
Adapter version is 2.20
Node.js: v12.16.3
JS-Controler: 3.2.16
![image](https://user-images.githubusercontent.com/7841787/111025580-52830600-83e5-11eb-8db9-28feae521738.jpeg)

**Comment by Apollon77** [comment]
But this is then more an node.red issue? We are "Just" using node-red under the hood

**Comment by lighthousehh** [comment]
A separate node-red installation is working. Only the node-red Iobroker Adapter (including the node-red instance causes this error.)

**Comment by Apollon77** [comment]
Then we need logging or any other infos ... is your browser console showing an error? No othe rreports of that so far from other users

**Comment by lighthousehh** [comment]
the browser console shows this during accessing the node-red GUI
<img width="2560" alt="image" src="https://user-images.githubusercontent.com/7841787/111076324-2e5e1c80-84ec-11eb-85eb-a8923758aa91.png">

**Comment by Apollon77** [comment]
jetzt ist die Frage ob das die Ursache ist oder immer kommt :-)

Wie ist dein setup? Irgendein reverse proxy davor? Mal anderen Browser versucht?

**Comment by lighthousehh** [comment]
iobroker auf DEBIAN
kein reverse proxy 
Ja auch mit anderen Browsern funktioniert es nicht (gleiche Meldung)
Adapter version is 2.20
Node.js: v12.16.3
JS-Controler: 3.2.16
Was hilft dir noch?
Habe node-red schonmal versucht zu deinstallieren.
Es gab folgende Fehlermeldung: 
npm uninstall iobroker.node-red --loglevel error --prefix "/opt/iobroker" (System call)
npm ERR! code ELOOP
npm ERR! syscall open
npm ERR! path /opt/iobroker/node_modules/iobroker-react-components/package.json
npm ERR! errno -40
npm ERR! ELOOP: too many symbolic links encountered, open '/opt/iobroker/node_modules/iobroker-react-components/package.json'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/iobroker/.npm/_logs/2021-03-15T20_25_45_671Z-debug.log
Error deleting adapter node-red from disk: Error: host.iobroker: Cannot uninstall iobroker.node-red: 216
You might have to delete it yourself!

Ich denke das liegt eher an der iobroker installation oder?

**Comment by Apollon77** [comment]
Hm ... das sollte an sich nichts mit dem issue zu tun haben aber ja ist strange. ich wäre ja bei: backup erstellen, iobroekr frisch installieren und backup einspielen. Dann schauen

**Comment by lighthousehh** [comment]
Hi issue can be closed.
After node.US update and iobroker rebuild node-red --install everything is working again

**Comment by Dreamdancer100** [comment]
what exactly did you install and where via ssh!? if yes, what have you updated!? I have the same problem and can't get any further
