### ISSUE TITLE
ioBroker out nodes are not recognized by complete nodes

### ISSUE THREAD

**Issue by mickym2** [ioBroker/ioBroker.node-red#167]
Either node.done is not set when iobroker out node has completed its task (node.done()) or there are other reasons why the complete node does not recognize when the iobroker out node has completed its task. 

![screen](https://user-images.githubusercontent.com/58858526/114791324-9a030600-9d86-11eb-9f66-a9e2965ce3fb.png)

**Comment by Apollon77** [comment]
I think till now noone wanted to contine the flow after the "set" (aka OutNode) ... and yes this is not implemented right now.

Try GitHub version please

**Comment by Apollon77** [comment]
BTW: if you tried before 0:07 ... please update github again :-)

**Comment by mickym2** [comment]
Node Red does not start with this version: 

2021-04-16 00:24:00.610 - info: host.MWHome instance system.adapter.node-red.0 started with pid 3712
2021-04-16 00:24:02.102 - info: node-red.0 (3712) starting. Version 2.2.0 in /opt/iobroker/node_modules/iobroker.node-red, node: v14.16.1, js-controller: 3.2.16
2021-04-16 00:24:03.066 - info: node-red.0 (3712) Starting node-red: --max-old-space-size=512 /opt/iobroker/node_modules/iobroker.node-red/node_modules/node-red/red.js -v --settings /opt/iobroker/iobroker-data/node-red/settings.js
2021-04-16 00:24:04.641 - warn: node-red.0 (3712) 16 Apr 00:24:04 - [warn] Die Verwendung von editorTheme.palette.editable ist abgekündigt. Stattdessen externalModules.palette.allowInstall verwenden.
2021-04-16 00:24:20.833 - info: node-red.0 (3712) node-red exited with 1
2021-04-16 00:24:25.835 - info: node-red.0 (3712) Starting node-red: --max-old-space-size=512 /opt/iobroker/node_modules/iobroker.node-red/node_modules/node-red/red.js -v --settings /opt/iobroker/iobroker-data/node-red/settings.js
2021-04-16 00:24:27.414 - warn: node-red.0 (3712) 16 Apr 00:24:27 - [warn] Die Verwendung von editorTheme.palette.editable ist abgekündigt. Stattdessen externalModules.palette.allowInstall verwenden.
2021-04-16 00:24:42.523 - info: node-red.0 (3712) node-red exited with 1
2021-04-16 00:24:47.524 - info: node-red.0 (3712) Starting node-red: --max-old-space-size=512 /opt/iobroker/node_modules/iobroker.node-red/node_modules/node-red/red.js -v --settings /opt/iobroker/iobroker-data/node-red/settings.js
2021-04-16 00:24:49.021 - warn: node-red.0 (3712) 16 Apr 00:24:49 - [warn] Die Verwendung von editorTheme.palette.editable ist abgekündigt. Stattdessen externalModules.palette.allowInstall verwenden.
2021-04-16 00:25:03.584 - info: node-red.0 (3712) node-red exited with 1
2021-04-16 00:25:08.585 - info: node-red.0 (3712) Starting node-red: --max-old-space-size=512 /opt/iobroker/node_modules/iobroker.node-red/node_modules/node-red/red.js -v --settings /opt/iobroker/iobroker-data/node-red/settings.js
2021-04-16 00:25:10.027 - warn: node-red.0 (3712) 16 Apr 00:25:10 - [warn] Die Verwendung von editorTheme.palette.editable ist abgekündigt. Stattdessen externalModules.palette.allowInstall verwenden.

**Comment by mickym2** [comment]
node-red.0 | 2021-04-16 00:27:38.697 | warn | (3712) 16 Apr 00:27:38 - [warn] Die Verwendung von editorTheme.palette.editable ist abgekündigt. Stattdessen externalModules.palette.allowInstall verwenden.
-- | -- | -- | --
node-red.0 | 2021-04-16 00:27:37.183 | info | (3712) Starting node-red: --max-old-space-size=512 /opt/iobroker/node_modules/iobroker.node-red/node_modules/node-red/red.js -v --settings /opt/iobroker/iobroker-data/node-red/settings.js
node-red.0 | 2021-04-16 00:27:32.181 | info | (3712) node-red exited with 1
node-red.0 | 2021-04-16 00:27:17.588 | warn | (3712) 16 Apr 00:27:17 - [warn] Die Verwendung von editorTheme.palette.editable ist abgekündigt. Stattdessen externalModules.palette.allowInstall verwenden.
node-red.0 | 2021-04-16 00:27:16.110 | info | (3712) Starting node-red: --max-old-space-size=512 /opt/iobroker/node_modules/iobroker.node-red/node_modules/node-red/red.js -v --settings /opt/iobroker/iobroker-data/node-red/settings.js
node-red.0 | 2021-04-16 00:27:11.107 | info | (3712) node-red exited with 1
node-red.0 | 2021-04-16 00:26:56.364 | warn | (3712) 16 Apr 00:26:56 - [warn] Die Verwendung von editorTheme.palette.editable ist abgekündigt. Stattdessen externalModules.palette.allowInstall verwenden.
node-red.0 | 2021-04-16 00:26:54.842 | info | (3712) Starting node-red: --max-old-space-size=512 /opt/iobroker/node_modules/iobroker.node-red/node_modules/node-red/red.js -v --settings /opt/iobroker/iobroker-data/node-red/settings.js
node-red.0 | 2021-04-16 00:26:49.841 | info | (3712) node-red exited with 1
node-red.0 | 2021-04-16 00:26:35.505 | warn | (3712) 16 Apr 00:26:35 - [warn] Die Verwendung von editorTheme.palette.editable ist abgekündigt. Stattdessen externalModules.palette.allowInstall verwenden.
node-red.0 | 2021-04-16 00:26:33.935 | info | (3712) Starting node-red: --max-old-space-size=512 /opt/iobroker/node_modules/iobroker.node-red/node_modules/node-red/red.js -v --settings /opt/iobroker/iobroker-data/node-red/settings.js
node-red.0 | 2021-04-16 00:26:28.929 | info | (3712) node-red exited with 1
node-red.0 | 2021-04-16 00:26:13.955 | warn | (3712) 16 Apr 00:26:13 - [warn] Die Verwendung von editorTheme.palette.editable ist abgekündigt. Stattdessen externalModules.palette.allowInstall verwenden.
node-red.0 | 2021-04-16 00:26:11.617 | info | (3712) Starting node-red: --max-old-space-size=512 /opt/iobroker/node_modules/iobroker.node-red/node_modules/node-red/red.js -v --settings /opt/iobroker/iobroker-data/node-red/settings.js
node-red.0 | 2021-04-16 00:26:06.615 | info | (3712) node-red exited with 1
node-red.0 | 2021-04-16 00:25:52.029 | warn | (3712) 16 Apr 00:25:52 - [warn] Die Verwendung von editorTheme.palette.editable ist abgekündigt. Stattdessen externalModules.palette.allowInstall verwenden.
node-red.0 | 2021-04-16 00:25:50.500 | info | (3712) Starting node-red: --max-old-space-size=512 /opt/iobroker/node_modules/iobroker.node-red/node_modules/node-red/red.js -v --settings /opt/iobroker/iobroker-data/node-red/settings.js
node-red.0 | 2021-04-16 00:25:45.498 | info | (3712) node-red exited with 1
node-red.0 | 2021-04-16 00:25:30.745 | warn | (3712) 16 Apr 00:25:30 - [warn] Die Verwendung von editorTheme.palette.editable ist abgekündigt. Stattdessen externalModules.palette.allowInstall verwenden.
node-red.0 | 2021-04-16 00:25:29.251 | info | (3712) Starting node-red: --max-old-space-size=512 /opt/iobroker/node_modules/iobroker.node-red/node_modules/node-red/red.js -v --settings /opt/iobroker/iobroker-data/node-red/settings.js
node-red.0 | 2021-04-16 00:25:24.251 | info | (3712) node-red exited with 1
node-red.0 | 2021-04-16 00:25:10.027 | warn | (3712) 16 Apr 00:25:10 - [warn] Die Verwendung von editorTheme.palette.editable ist abgekündigt. Stattdessen externalModules.palette.allowInstall verwenden.
node-red.0 | 2021-04-16 00:25:08.585 | info | (3712) Starting node-red: --max-old-space-size=512 /opt/iobroker/node_modules/iobroker.node-red/node_modules/node-red/red.js -v --settings /opt/iobroker/iobroker-data/node-red/settings.js
node-red.0 | 2021-04-16 00:25:03.584 | info | (3712) node-red exited with 1
node-red.0 | 2021-04-16 00:24:49.021 | warn | (3712) 16 Apr 00:24:49 - [warn] Die Verwendung von editorTheme.palette.editable ist abgekündigt. Stattdessen externalModules.palette.allowInstall verwenden.
node-red.0 | 2021-04-16 00:24:47.524 | info | (3712) Starting node-red: --max-old-space-size=512 /opt/iobroker/node_modules/iobroker.node-red/node_modules/node-red/red.js -v --settings /opt/iobroker/iobroker-data/node-red/settings.js
node-red.0 | 2021-04-16 00:24:42.523 | info | (3712) node-red exited with 1
node-red.0 | 2021-04-16 00:24:27.414 | warn | (3712) 16 Apr 00:24:27 - [warn] Die Verwendung von editorTheme.palette.editable ist abgekündigt. Stattdessen externalModules.palette.allowInstall verwenden.
node-red.0 | 2021-04-16 00:24:25.835 | info | (3712) Starting node-red: --max-old-space-size=512 /opt/iobroker/node_modules/iobroker.node-red/node_modules/node-red/red.js -v --settings /opt/iobroker/iobroker-data/node-red/settings.js
node-red.0 | 2021-04-16 00:24:20.833 | info | (3712) node-red exited with 1
node-red.0 | 2021-04-16 00:24:04.641 | warn | (3712) 16 Apr 00:24:04 - [warn] Die Verwendung von editorTheme.palette.editable ist abgekündigt. Stattdessen externalModules.palette.allowInstall verwenden.

**Comment by Apollon77** [comment]
Hm ... very helpful  (not against you ... the log says basically nothign as hint) ... is there any logfile from node-red?

Ok, I not removed it on two other nodes beside OutNode where I thought it makes sense ... so please try again ... now only done in OutNode

**Comment by mickym2** [comment]
No logfile - and still the same - with this version the adapter remains in a loop. 

It looks like the adapter is running (green), but you can't open node-red and no flows are active. 

This entries are in end endlos loop:


  |   |   |  
-- | -- | -- | --
node-red.0 | 2021-04-16 11:55:42.911 | warn | (6295) 16 Apr 11:55:42 - [warn] Die Verwendung von editorTheme.palette.editable ist abgekündigt. Stattdessen externalModules.palette.allowInstall verwenden.
node-red.0 | 2021-04-16 11:55:41.234 | info | (6295) Starting node-red: --max-old-space-size=512 /opt/iobroker/node_modules/iobroker.node-red/node_modules/node-red/red.js -v --settings /opt/iobroker/iobroker-data/node-red/settings.js
node-red.0 | 2021-04-16 11:55:36.234 | info | (6295) node-red exited with 1
node-red.0 | 2021-04-16 11:55:15.663 | warn | (6295) 16 Apr 11:55:15 - [warn] Die Verwendung von editorTheme.palette.editable ist abgekündigt. Stattdessen externalModules.palette.allowInstall verwenden.
node-red.0 | 2021-04-16 11:55:14.070 | info | (6295) Starting node-red: --max-old-space-size=512 /opt/iobroker/node_modules/iobroker.node-red/node_modules/node-red/red.js -v --settings /opt/iobroker/iobroker-data/node-red/settings.js
node-red.0 | 2021-04-16 11:55:09.068 | info | (6295) node-red exited with 1
node-red.0 | 2021-04-16 11:54:48.897 | warn | (6295) 16 Apr 11:54:48 - [warn] Die Verwendung von editorTheme.palette.editable ist abgekündigt. Stattdessen externalModules.palette.allowInstall verwenden.
node-red.0 | 2021-04-16 11:54:47.287 | info | (6295) Starting node-red: --max-old-space-size=512 /opt/iobroker/node_modules/iobroker.node-red/node_modules/node-red/red.js -v --settings /opt/iobroker/iobroker-data/node-red/settings.js
node-red.0 | 2021-04-16 11:54:42.285 | info | (6295) node-red exited with 1

**Comment by mickym2** [comment]
I switched to debug level - I do not know if this is helpful - but I think I found something. node.done is not a function - may be this is not the correct way to implement it or it is a syntax error!
 (see entry - 2021-04-16 12:02:41.101). 

node-red.0 | 2021-04-16 12:02:53.668 | info | (12520) Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason
-- | -- | -- | --
host.MWHome | 2021-04-16 12:02:53.649 | info | stopInstance timeout 1000 system.adapter.node-red.0 killing pid 12520
node-red.0 | 2021-04-16 12:02:53.447 | debug | (12520) 16 Apr 12:02:53 - [info] Dashboard version 2.28.2 started at /ui
node-red.0 | 2021-04-16 12:02:52.983 | debug | (12520) Initializing HAP-NodeJS v0.9.4...
node-red.0 | 2021-04-16 12:02:52.654 | info | (12520) kill node-red task
host.MWHome | 2021-04-16 12:02:52.646 | info | stopInstance system.adapter.node-red.0 (force=false, process=true)
host.MWHome | 2021-04-16 12:02:52.639 | info | "system.adapter.node-red.0" disabled
node-red.0 | 2021-04-16 12:02:48.749 | debug | (12520) 16 Apr 12:02:48 - [info] Paletten-Nodes werden geladen
node-red.0 | 2021-04-16 12:02:47.910 | warn | (12520) 16 Apr 12:02:47 - [warn] Die Verwendung von editorTheme.palette.editable ist abgekündigt. Stattdessen externalModules.palette.allowInstall verwenden.
node-red.0 | 2021-04-16 12:02:47.895 | debug | 16 Apr 12:02:47 - [info] Linux 5.10.17-v7l+ arm LE
node-red.0 | 2021-04-16 12:02:47.895 | debug | (12520) 16 Apr 12:02:47 - [info] Node.js Version: v14.16.1
node-red.0 | 2021-04-16 12:02:47.892 | debug | (12520) 16 Apr 12:02:47 - [info] Node-RED Version: v1.3.2
node-red.0 | 2021-04-16 12:02:47.890 | debug | ===================
node-red.0 | 2021-04-16 12:02:47.890 | debug | Willkommen bei Node-RED!
node-red.0 | 2021-04-16 12:02:47.890 | debug | (12520) 16 Apr 12:02:47 - [info]
node-red.0 | 2021-04-16 12:02:46.327 | info | (12520) Starting node-red: --max-old-space-size=512 /opt/iobroker/node_modules/iobroker.node-red/node_modules/node-red/red.js -v --settings /opt/iobroker/iobroker-data/node-red/settings.js
node-red.0 | 2021-04-16 12:02:41.325 | info | (12520) node-red exited with 1
node-red.0 | 2021-04-16 12:02:41.101 | debug | at processImmediate (internal/timers.js:463:21)
node-red.0 | 2021-04-16 12:02:41.101 | debug | at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.node-red/nodes/ioBroker.js:446:34)
**node-red.0 | 2021-04-16 12:02:41.101 | debug | (12520) 16 Apr 12:02:41 - TypeError: node.done is not a function**
node-red.0 | 2021-04-16 12:02:41.099 | debug | (12520) 16 Apr 12:02:41 - [red] Uncaught Exception:

**Comment by Apollon77** [comment]
> (12520) 16 Apr 12:02:41 - TypeError: node.done is not a function**

seems it was not thaaat easy ...

please check github version again ...

**Comment by mickym2** [comment]
Hi Ingo, 

**it is working now.**  Great. 

![image](https://user-images.githubusercontent.com/58858526/115056812-9042e500-9ee3-11eb-8026-1e1c515ffea7.png)

But the node does not really give additional value. I thought that that all nodes you selected in the complete node have to be completed that you are able to automatically synchronize flows, but this is not the case. So the additional value for the iobroker out nodes does not really bring an additional value as this can be achieved with the iobroker in node instead of a complete node as well. 

However with this version you get always this error message (warning message). I hope there are no side effects with this version


node-red.0 | 2021-04-16 18:34:44.371 | warn | (5896) 16 Apr 18:34:44 - [warn] Die Verwendung von editorTheme.palette.editable ist abgekündigt. Stattdessen externalModules.palette.allowInstall verwenden.
-- | -- | -- | --
node-red.0 | 2021-04-16 18:34:42.626 | info | (5896) Starting node-red: --max-old-space-size=512 /opt/iobroker/node_modules/iobroker.node-red/node_modules/node-red/red.js -v --settings /opt/iobroker/iobroker-data/node-red/settings.js

**Comment by mickym2** [comment]
It is working - but does not really bring additional value. I thought originally that all node you have selected in this complete node have to be completed before a message is created, but this is not the case.

**Comment by Apollon77** [comment]
Ok, I updated dependencies and also node-red and the settings ... can yu check again if anything still works?

**Comment by mickym2** [comment]
Can not say - if everything works - but I have no errors and flows seems to work as well. 
The warning disappeared and the instance started properly.


node-red.0 | 2021-04-16 21:56:14.297 | info | (25919) Automatic objects creation is not enabled. You can enable it in the node configuration
-- | -- | -- | --
node-red.0 | 2021-04-16 21:55:11.961 | info | (25896) Starting node-red: --max-old-space-size=512 /opt/iobroker/node_modules/iobroker.node-red/node_modules/node-red/red.js -v --settings /opt/iobroker/iobroker-data/node-red/settings.js
node-red.0 | 2021-04-16 21:55:11.113 | info | (25896) starting. Version 2.2.0 in /opt/iobroker/node_modules/iobroker.node-red, node: v14.16.1, js-controller: 3.2.16
host.MWHome | 2021-04-16 21:55:09.540 | info | instance system.adapter.node-red.0 started with pid 25896
host.MWHome | 2021-04-16 21:55:07.118 | info | instance system.adapter.node-red.0 terminated with code 156 (START_IMMEDIATELY_AFTER_STOP)
node-red.0 | 2021-04-16 21:55:06.473 | info | (9888) Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason
host.MWHome | 2021-04-16 21:55:06.444 | info | stopInstance timeout 1000 system.adapter.node-red.0 killing pid 9888
node-red.0 | 2021-04-16 21:55:05.990 | info | (9888) node-red exited with 0

It seems that a new version of Node-Red (1.3.2) is installed as there is a further translatations ;) - i.e. the deploy button.

![image](https://user-images.githubusercontent.com/58858526/115079158-099d0080-9f01-11eb-8ed0-88df921a4f48.png)


So many thanks - your support is great!!!!

**Comment by Apollon77** [comment]
release comes as 2.3.0
