### ISSUE TITLE
External node RED server

### ISSUE THREAD

**Issue by hamdanfadi** [ioBroker/ioBroker.node-red#168]
Hi there,
May I know where to install iobroker pallet? in other word how I can connect my Node-RED server to iobroker server?

Cheers,

**Comment by Apollon77** [comment]
duplictae https://github.com/ioBroker/ioBroker.node-red/issues/124

**Comment by hamdanfadi** [comment]
Hi,
There is no answer for my question my dear in this issue!! Can I have a straight answer please?

Cheers,


Hamdan, Fadi
24B Carrick Glen Avenue, Flat Bush, Auckland 2019
New Zealand
***@***.******@***.***>
M +64 21 066 0088

**Comment by Apollon77** [comment]
There is corrently no package of the iobroker nodes "standalone" to be added to a standalone node-red. Only the integrated adapter is existing.

**Comment by mirotrex** [comment]
any updates on this?

**Comment by Apollon77** [comment]
Hm... The issue is closed since 1,5 years ... I do not know that someone built an ioBroker Nodered Plugin that works standalone - in fact mtt and other tech could work ... If you like to develop one we are happy to support.
