### ISSUE TITLE
Installing additional nodes

### ISSUE THREAD

**Issue by Sineos** [ioBroker/ioBroker.node-red#17]
I have been trying to install an additional node in node-red.

According to the docs I installed it into `/opt/iobroker/node_modules/iobroker.node-red/node_modules`
This did not work, i.e. the node was not showing up in node-red.
After installing it to `/opt/iobroker/node_modules` it worked.

Anyway, thanks a lot for this great contribution.

**Comment by GermanBluefox** [comment]
Normally you should not install the packages yourself. You must write desired packages in the configuration node-red adapter and all packets will be installed automatically.

**Comment by Sineos** [comment]
I did try this first. It also installed the node into /opt/iobroker/node_modules/iobroker.node-red/node_modules with the same result. 
Not a big deal for me, just thought I mention it, in case other folks stumble across the same topic

**Comment by Sineos** [comment]
On a side-note:
The node I was installing is: https://www.npmjs.com/package/node-red-contrib-aggregator
This one might even be worth to be installed by default into iobroker, since imo, this is one of the most useful nodes ever, when dealing with sensor data.

**Comment by GermanBluefox** [comment]
I will check it. Thank you.
I think to include node-red-contrib-os and node-red-dashboard too.

and now node-red-contrib-aggregator
<https://www.npmjs.com/package/node-red-contrib-aggregator>.

Greetings,



2017-02-12 22:45 GMT+01:00 Sineos <notifications@github.com>:
