### ISSUE TITLE
Verlinkung zur Node-red Webseite ist falsch

### ISSUE THREAD

**Issue by JBSullivan** [ioBroker/ioBroker.node-red#180]
Die Verlinkung vom Adapter zur node-red Seite ist falsch adressiert.

![image](https://user-images.githubusercontent.com/44617472/118798155-9f7bd080-b89d-11eb-86a6-0e9d1ba84f36.png)

![image](https://user-images.githubusercontent.com/44617472/118798221-aefb1980-b89d-11eb-875e-e4980c5024ef.png)

**Comment by Apollon77** [comment]
Welcvhe Adapter-Version, sollte schon länge gefixt sein dachte ich

**Comment by JBSullivan** [comment]
Sorry, war mein Fehler - ich hatte sowohl die node-red Standalone Version installiert, als auch den ioBroker Adapter. Wenn beides auf dem gleichen Rechner läuft, kommt es zu dem Phänomen das die ioB node-red Kachel auf die Standalone Version von node-red verlinken will.
Wenn die Standalone node-red Version gestoppt ist, klappt der Link und es wird auf die node-red Version verlinkt die in ioBroker installiert ist.

Adapter Version ist im übrigen 2.3.0

**Comment by Apollon77** [comment]
Das verstehe ich aber nicht ... ioBroker weiss nichts von einer stand alone installation ... sttange

**Comment by JBSullivan** [comment]
Das ist richtig - da es aber der gleiche Rechner ist (Localhost) und beide Installationen auf Port 1880 arbeiten, könnte ich mir vorstellen, das der Adapter selbstständig den Link anpasst, wenn er unter der IP/Port keine Verbindung bekommt, weil ja dort schon die Stand Alone node-red Anwendung den Weg blockiert.

Weil es vom ioB Adapter keinen Kontakt gibt, setzt er "möglicherweise" ein undefined in die URL - nur so eine Vermutung.
