### ISSUE TITLE
Wo kann man das Debug Log finden (von installierten Paletten)

### ISSUE THREAD

**Issue by Domi920** [ioBroker/ioBroker.node-red#191]
Hallo,
sorry von Anfang an für die wahrscheinlich blöde Frage.
Habe eine Platte installiert und diese auf Debug geschalten.
Leider weiß ich nicht wo ich das Protokoll Log finden kann?

Danke für die Hilfe!

**Comment by Apollon77** [comment]
An sich sollte Debug log im ioBroker Log landen. ggf dort auch mal auff debug stellen

**Comment by Domi920** [comment]
Danke für die schnelle Antwort!

Stimmt. Ich hatte nur übersehen das ich das vollständige Protokoll öffnen muss um die volle Länge zu sehen!


Gruß Dominik
