### ISSUE TITLE
Link und Lasche

### ISSUE THREAD

**Issue by mimquadrat** [ioBroker/ioBroker.node-red#2]
Node-Red läuft bei mir auf einem 2. Raspi (als slave oder client).
Wenn ich den Link unter Instanzen klicke, komm ich aber auf die IP von der Master-Installation.
Auch auf der Node-Red Lasche die nach der Installation erscheint kommt nichts.

**Comment by GermanBluefox** [comment]
Fast die richtige Stelle :) Es ist aber iobroker.admin schuldig. Las es hier liegen.

**Comment by GermanBluefox** [comment]
Habe doch zu ioBroker.admin verschoben.
