### ISSUE TITLE
ioBroker.node-red - OWL

### ISSUE THREAD

**Issue by mac-d** [ioBroker/ioBroker.node-red#20]
Hallo, bisher hat die Datenübergabe meiner Smartmeter (OWL) aus node-red (0.16.2) perfekt funktioniert.
Mit dem Update von node-red auf V.0.17.5 werden die Daten nicht mehr aktualisiert.

error	setObject id missing!!

Kann mir hier jemand weiterhelfen?

![iobroker admin node-red](https://user-images.githubusercontent.com/13673027/30897606-7dbec100-a357-11e7-8dbf-993e0e5cd842.png)
![iobroker admin zustande](https://user-images.githubusercontent.com/13673027/30897607-7dbec696-a357-11e7-9b36-c94d7df202c6.png)
Version 0.16.2
![log 0 16 2-iobroker admin](https://user-images.githubusercontent.com/13673027/30897608-7dc26026-a357-11e7-9676-f061c90b8d7b.png)
Version 0.17.5
![log 0 17 5-iobroker admin](https://user-images.githubusercontent.com/13673027/30897609-7dcdd050-a357-11e7-9e8b-dc8daaa72c94.png)

Gruss Dieter

**Comment by twonky4** [comment]
Der Fehler wurde in issue #18 bereits behoben und muss released werden.

**Comment by LDSign** [comment]
Wann kommt der Release? Danke :)

**Comment by GermanBluefox** [comment]
Jetzt (latest)

**Comment by mac-d** [comment]
Super, funktioniert wieder alles... :+1:
