### ISSUE TITLE
Unterstützung für das neue Farbschema im ioBroker Admin 5

### ISSUE THREAD

**Issue by Bernd9000** [ioBroker/ioBroker.node-red#207]
Es wäre schön wenn das neue Farbschema/Farbthema unterstüzt wird.

**Comment by Apollon77** [comment]
Where you mean? Node-red opens as extra window/tab, or? If not: is an external software. Or what exactly is meaned?

**Comment by Bernd9000** [comment]
Ich meine die neue Admin Oberfläche im Browser.
Hier kann ich unter dem Punkt "Farbschema ändern" den Hintergrund z.B. in schwarz ändern.
Das passiert allerdings nicht im Adapter von node-red, hier bleibt alles weiß.

Ich beziehe mich auf deiner Nachricht im iobroker Forum:
Zitat apollon77
8 Aug 2021, 13:00

@crunchip Adapter müssen das mit Farbschema und so unterstützen. Das ist nicht bei allen drin. Also ggf GitHub issues bei den Adaptern anlegen das die das nachrüsten.......

**Comment by Apollon77** [comment]
Ja schon klar ... haste mal Screenshot? Weil wenn in dem tab die Node-red anwendung läuft (was ja komplett "iobroker fremde Software" ist dann können wir da nichts tun. DIe haben denke gar nicht sowas

**Comment by Bernd9000** [comment]
![1](https://user-images.githubusercontent.com/77005685/128811694-5712266e-d163-4221-924a-796698bc4ee9.jpg)

**Comment by Apollon77** [comment]
Jupp this is the node-red application ... There is no way to get the farbschema transported, lso because they do not have that by default
