### ISSUE TITLE
Allow creation of foreign objects

### ISSUE THREAD

**Issue by louisvangeldrop** [ioBroker/ioBroker.node-red#208]
Where can I find more documentation about  this functionality. I assumed that this option allows me to use "require" like: 
const OpenAPI = require('@tuyapi/openapi');

Unfortunately this statement is not allowed: TypeError: require is not a function

**Comment by Apollon77** [comment]
I do not understand the scope of your question? Is it a question on "how to do something in node.red" then node-red Forums might be better. This adapter "Just" integrated an node-red with ioBroker.

**Comment by louisvangeldrop** [comment]
I was looking for more documentaion regarding the option: Allow creation of foreign objects

**Comment by Apollon77** [comment]
In fact by default allowCreationOfForeignObjects is off, this means that all objects and states that are created by nodes are created in teh respective node-red.X namespace as iobroker objects.
When you set that to true you can also create objects in other namespaces like 0_userdata.0

It is not about requiring code, it is just where in iobroker objects are created
