### ISSUE TITLE
stateMin is not correctly written in state object

### ISSUE THREAD

**Issue by mickym2** [ioBroker/ioBroker.node-red#209]
stateMin is not correctly assigned when writen in common.min property.

**Comment by mickym2** [comment]
I proposed the changes in the code - but I am not sure if this is correct:

https://github.com/ioBroker/ioBroker.node-red/pulls

**Comment by Apollon77** [comment]
I do not see a PR right now ... maybe yu just committed in your local branch but did not cliked (create PR)?

**Comment by mickym2** [comment]
Ok - I hope created a correct PR now.

I proposed a change - which is in my opinion wrong:

![image](https://user-images.githubusercontent.com/58858526/129463240-af6950e4-15d1-4156-8875-8849a6557dee.png)

**Comment by mickym2** [comment]
Is implemented in version 2.4.1
