### ISSUE TITLE
ioBroker.node-Red -> history.0

### ISSUE THREAD

**Issue by mac-d** [ioBroker/ioBroker.node-red#21]
Hallo, ich bin wirklich immer wieder überrascht, was in der Kombination ioBroker + Node-Red funktioniert.

Ich würde gerne die Chart-Anzeige in Node-Red (Dashboard) mit Daten
aus der ioBroker History.0 kombinieren.

Leider habe ich dazu noch keine Lösung gefunden.

LG Dieter

**Comment by GermanBluefox** [comment]
Bitte im Forum fragen.

**Comment by romgen** [comment]
Hey,
Das Forum wird hier auch nicht weiter helfen, weil es einfach keinen Endpunkt vom iobroker zum History Adapter gibt.
Einzige Möglichkeit ist hier Javascript zu nehmen oder halt anstatt den standard history adapter eine sql datenbank zu nehmen, die als server läuft.

**Comment by Apollon77** [comment]
generell hat der history Adapter die Möglichkeit Daten direkt per Message abzufragen. Es gibt nur meines Wissens nach keinen aktuellen weg dazu aus node-red heraus zu nutzen. Ja da wäre influxdb/sql einfacher
