### ISSUE TITLE
Node-red in version 0.18.2 available

### ISSUE THREAD

**Issue by thelightmaker** [ioBroker/ioBroker.node-red#23]
Please bump up node-red version to 0.18.2

https://github.com/node-red/node-red/blob/master/package.json

**Comment by Apollon77** [comment]
1.5.0 on Github. Please test!

**Comment by thelightmaker** [comment]
The new version looks good for me. I have in two iobroker instances (armhf, amd64) no problems found. Thx a lot.

Regards.

**Comment by tp1de** [comment]
I have installed the new version on 3 instances (armhf,amd64). No problems found and timing problem on adapter start disappeared. Works fine - thanks. See remarks in iobroker forum (tom57)

**Comment by Apollon77** [comment]
released
