### ISSUE TITLE
More control for acknowledged

### ISSUE THREAD

**Issue by holomekc** [ioBroker/ioBroker.node-red#240]
Hi. I like the acknowledged option for input nodes. Would it possible to improve it further:

acknowledged:
- true
- false
- both

This would allow to react on commands only as well. Currently I use a switch node afterwards to acieve that.

Maybe also think about using the same name on input and output. Current situation:
Input: acknowledged
Output: command/value

Thanks for all your effort!

Br
Christopher

**Comment by GermanBluefox** [comment]
Implemented in next version.
![image](https://user-images.githubusercontent.com/4582016/157118099-70f0815c-1dd9-4df5-9bcd-40e0d9e340a2.png)

**Comment by Apollon77** [comment]
Released in 3.0.0
