### ISSUE TITLE
Log error without using "Palletmanager"

### ISSUE THREAD

**Issue by MMeinhardt1** [ioBroker/ioBroker.node-red#244]
Hi,

if you do not use the "Palletmanager" and the field "additional NPM modules" is empty you get an error in the Log.

```
2021-12-29 23:09:14.171  - info:  node-red.0 (783) starting. Version 2.4.1 in  /opt/iobroker/node_modules/iobroker.node-red, node: v14.18.2,  js-controller: 3.3.22
2021-12-29 23:09:14.207  - error: node-red.0 (783) install: [""]
2021-12-29 23:09:15.499  - info:  node-red.0 (783) Starting node-red: --max-old-space-size=128  /opt/iobroker/node_modules/node-red/red.js -v --settings  /opt/iobroker/iobroker-data/node-red/settings.js
2021-12-29 23:09:21.664  - warn:  node-red.0 (783) 29 Dec 23:09:21 - [warn] Projects disabled : editorTheme.projects.enabled=false
```

**Comment by mickym2** [comment]
In my opinion - it should be checked - if the installation of additional modules or nodes in node-red can be standard again, as it was in the previous versions. Additional node-modules over adapter settings has some disadvantages (i.e. no version control). 
My question is why the palette manager is switched off at all?? 

 As additional nodes or node modules are installed under iobroker-data directory - are the additional nodes included in the backup anyway?
.

**Comment by Apollon77** [comment]
> In my opinion - it should be checked - if the installation of additional modules or nodes in node-red can be standard again, as it was in the previous versions.
>  My question is why the palette manager is switched off at all??

@GermanBluefox What was the reason to disable it?

> Additional node-modules over adapter settings has some disadvantages (i.e. no version control).

Ok we could allow entries like name@version there too (if not already possible)

> As additional nodes or node modules are installed under iobroker-data directory - are the additional nodes included in the backup anyway?

No, iobroker-data, especially instance specific directories are not in the backup by default (and a node_modules in backup would be bad because there are symlinks and such used ... this would never be restored correctly).

**Comment by Apollon77** [comment]
@mickym2 WOuld this also be an idea for a Readme addition? What we should write?

**Comment by mickym2** [comment]
In my opinion we can also keep the status as it is, but the error in the log should disappear

`error: node-red.0 (783) install: [""]`

This is an absolute nonsense message, if someone does not use the palette manager and does not need additional modules. I do not know if there are messages when modules installed via adapter settings - but in my opinion - installation of modules are done once but should not be logged each time the adapter starts.

**Comment by Apollon77** [comment]
This "error" is already changed and now says "Requested NPM packages:  ..." as info logging (what it should have state before too) once on start

**Comment by Apollon77** [comment]
And PS: The npm dependencies are checked on each start and if they exist then they are not installed again ...
