### ISSUE TITLE
support node-red on another IP

### ISSUE THREAD

**Issue by robig** [ioBroker/ioBroker.node-red#25]
Please provide support for running Node-Red on another system (IP/hostname).
I'm running ioBroker on a raspberry pi 3, using my nas as SQL and Node-Red instance.

Thank you

**Comment by Apollon77** [comment]
The current way would be to create an ioBroker Slave on the nas and install the node-red adapter there. So it should work.

**Comment by Homoran** [comment]
I Didn't check it today, but on the slave it was not possible to manage node-red from the master's admin.

**Comment by robig** [comment]
OK, managed to install iobroker multihost setup.
But I cant see the ioBroker nodes. 
Meaning I could see them, but after importing my flows from backup (because I only had a empty flow) it' s not there anymore! 

I wonder how the integration actually works, because I did not install anything to the palette.

**Comment by Apollon77** [comment]
Could it be that the nodes are also stored in kind of a config and this also got replacedby importing?!

The Adapter will bring own nodes in it's directory ... don't know if they need to get "registered" somehow specificly ...

**Comment by robig** [comment]
Maybe do node-red and iobroker.node-red need to run with the same user?

**Comment by robig** [comment]
OK, I just found that iobroker.node-red is holding its own flow in /opt/iobroker/iobroker-data/node-red and running a node process ad root (because iobroker is started as root, what I realy don't like!).
But it seems to flush my flows at restart of the adapter!
I was able to see the ioBoker in plug, but only until I rebooted the system. :(

In that case, this adapter is not usable.

**Comment by GermanBluefox** [comment]
node-red runs on other IP, but here is another issue: https://github.com/ioBroker/ioBroker.admin/issues/51

Just open node-red directly in browser: http://slaveIP:1880

**Comment by GermanBluefox** [comment]
No one stops you @robig to run iobroker as specific user. Just do it

**Comment by robig** [comment]
Okay. I think the issue was, that Node-Red by default enables its systemd service. and it was unpredictable which node-red instance would start first.
I'm not trying to save my exsting flow and starting completely fresh. looks promising ;)
