### ISSUE TITLE
Command "node.log" isnt seen in ioBroker log

### ISSUE THREAD

**Issue by MMeinhardt1** [ioBroker/ioBroker.node-red#254]
Hi @Apollon77,

please let through the "node.log" command to the ioBroker Log as [info].
In Log-Level "Debug" it can seen as [info]. In Log-Level "Info" isnt seen, only the command "node.warn" is seen as [warn] in Log. 

Many thanks

**Comment by GermanBluefox** [comment]
I think this is impossible or very complicated to solve
