### ISSUE TITLE
ioBroker get liefert falsche Werte

### ISSUE THREAD

**Issue by Bernd9000** [ioBroker/ioBroker.node-red#258]
Ich möchte über node-red bestimmte Datenpunkte in ioBroker abfragen ob Sie existieren.
Dazu trage ich einfach das Topic in ioBroker-get node ein.
Zwei Topic Beispiele:

1.) mqtt.0.shellies.Shelly_25_Reserve.roller.0.command
2.) mqtt.0.shellies.Shelly_25_Reserve.roller.0.command/pos
3.) mqtt.0.shellies.Shelly_25_Reserve.roller.0.test

Alle drei Topic existieren aktuell nicht.
Der erste und zweite Topic haben einmal existiert.
Als msg.payload erhalte ich beim ersten "null" beim zweiten und dritten NICHTS=keine Ausgabe

Sollte nicht bei allen drei "null" als msg.payload ausgegeben werden?
Gibt es eine andere Möglichkeit ein Topic auf Existenz zu prüfen?

**Comment by Apollon77** [comment]
Bitte logleel des iobroker adaptera auf debug stellen und log posten

**Comment by Apollon77** [comment]
Naja es besteht formal ein unterschied zwischen "einem State der den Wert 'null' hat" und "einem state der nicht existiert aka "keinen" Wert hat ... "keiner" ist nicht gleich "null" ... "Null" ist ein erlaubter Wert eines States. Was sollte denn bei einem "nicht existierenden State" als Wert weitergegeben werden?

**Comment by Bernd9000** [comment]
Aber alle drei States existieren gar nicht, dann sollte doch als payload bei allen drei das selbe kommen ?
Bei einem nicht existierendes Objekt würde ich das nicht im msg.payload ausgeben sondern z.B. auf msg.error ausgeben.
 Dies könnte man als Anwender dann geziehlt abfragen.

**Comment by Apollon77** [comment]
Am Ende wäre meine Vermutung das (aus welchen grund auch immer) bei dem einen zwar vllt das Objekt nicht existsiert aber ein State da ist ... das sollte nicht passieren ... aber :-)
Ich überlege mal ob man ggf doch das Objekt zusätzlich prüft

**Comment by Bernd9000** [comment]
Okay, danke

**Comment by Bernd9000** [comment]
Nachtrag:
Der output vom ioBroker-get sollte bei einem nicht vorhandenen Datenpunkt wenigstens den Topic enthalten und als payload "undefined".So kann man darauf reagieren.

**Comment by Apollon77** [comment]
@mickym2 An error feels too hard because in fact this is still a valid case - especially when states have values with expiry or such ... what about returning undefined? Is this allowed in node-red? This would differentiate is to null vs a value?!

**Comment by Apollon77** [comment]
My proposal would be to return undefined (if return type is object) or empty string (if valueConvert is true). Only question: Add option to choose? Because in fact it will be "breaking" because now the nodes of such states will send out a content which was not the case before. So add a config for "also send payload for not existing state values" with default false?

**Comment by mickym2** [comment]
Undefined is OK - **I would not return an empty string.** "Undefined" states can be handled by a following switch node. An empty string however is a state and will create trouble as you can not longer differentiate between a non existing state and a state with an empty string.

![image](https://user-images.githubusercontent.com/58858526/157435090-c6b79dca-e277-400e-a91c-c367869c80b2.png)

OK -  a new option can be offered - to have a backward compatibility - but in my opinion it is not necessary. If someone want to filter out undefined messages - someone can use a following switch node to filter out this type of messages.

![image](https://user-images.githubusercontent.com/58858526/157436013-85fa3d7c-3a6d-4f85-aac1-d85879eff534.png)

So I do not know - how it was handled in the past and if a change log entry would enough to make users aware of the change. In my opinion an option can be offered - but I would not offer this option.

**Comment by Apollon77** [comment]
GitHub updated

**Comment by Bernd9000** [comment]
Danke, aber ich glaube das funktioniert noch nicht richtig ?

In den Eigenschaften vom ioBroker-get Node wird die Option wohl nicht gespeichert.
Stelle ich auf "Return state value as undefined" und öffne erneut steht es wieder auf "Return error on non existing Object"
![1](https://user-images.githubusercontent.com/77005685/157555627-723a46d3-67af-4e0c-8d77-523092b2131d.jpg)

Stelle ich als Topic ein nicht existierendes Objekt ein wird nur ein Leerstring übergeben.
Node-status wird aber gelb angezeigt
![2](https://user-images.githubusercontent.com/77005685/157556304-3736ca45-a472-46d6-bf8c-678a1415cacc.jpg)

**Comment by mickym2** [comment]
Nun das undefined finde ich nicht so gut - aber funktioniert denn der Error - sprich kannst Du dann mit einer Catch-Node den Fehler abfangen und dann einen neuen Flow anstoßen?

**Comment by Bernd9000** [comment]
Nein, der catch Node liefert gar nichts.

**Comment by mickym2** [comment]
OK - dann muss da wohl nochmal jemand ran. ;)

**Comment by Bernd9000** [comment]
Wie stelle ich den Debug-Node auf Objekt um ?
Wenn ich den ioBroker-get auf Objekt umstelle wird übrigens (null) geliefert.
![1](https://user-images.githubusercontent.com/77005685/157560985-8643b4df-d0d7-4102-8238-75734b077a62.jpg)

**Comment by Bernd9000** [comment]
Okay, ich vermute mal hier wie im Bild, aber da kommt auch nichts
![1](https://user-images.githubusercontent.com/77005685/157561442-42038ffb-46d0-4679-aca2-ed6f87d24bbf.jpg)

**Comment by mickym2** [comment]
OK - I confirm - the error option does not work. 

But I get always undefined for non existing states back.

![image](https://user-images.githubusercontent.com/58858526/157565056-3ae89e62-66d2-4b85-b8af-bae4e6a92bd6.png)

**Comment by Apollon77** [comment]
Please check again ... seems I forgot to define default in the iobroker.html ...

**Comment by Apollon77** [comment]
> Stelle ich als Topic ein nicht existierendes Objekt ein wird nur ein Leerstring übergeben.

Das ist "wie die bisherige Logik", da wollte ich nicht breaken. Wenn man "value" einstellt dann wird undefined und null auf einen leerstring gemapped ... "War schon immer so" ... das undefined kommt zurück wenn man "objekt" wählt anstelle value

**Comment by Bernd9000** [comment]
Hab jetzt nochmal getestet, ioBroker-get ist auf Object eingestellt.
Ergebnis bei einem nicht existierenden Objekt:

1.) "Return state value as undefined"       = null
2.) "Return error on non existing Object" = null

Bei beiden kommt das gleiche Ergebnis.
Ein error kommt nicht, weder beim debug-node noch beim catch-node
Oder mache ich was falsch?

**Comment by Apollon77** [comment]
Ok, try again please ... seems a new settings needed even another line of logic

**Comment by mickym2** [comment]
Na wenn man die bisherige Logik nicht brechen will muss man null zurückgeben, dann wird aber entweder nichts zurückgegeben oder ein Fehler erzeugt.. Undefined eigentlich nie. Und um einen Fehler zu erzeugen muss man die node.error mit einer Fehlerbeschreibung und einem msg Objekt aufrufen

![image](https://user-images.githubusercontent.com/58858526/157661954-11f0f990-2bdc-4b5c-b586-fb83c5685231.png)

https://nodered.org/docs/user-guide/writing-functions#logging-events
Über die catch Node kann man dann so was abfangen und reagieren:

![image](https://user-images.githubusercontent.com/58858526/157662109-7000ebf7-9a0a-4c23-b705-93bcf692bc22.png)

**Comment by mickym2** [comment]
Im Moment bekomme ich weiterhin nur undefined zurück (egal welche Option - die eingestellte Option bleibt auch nicht im Dialog erhalten):

![image](https://user-images.githubusercontent.com/58858526/157671212-b89f0e9d-7b8b-47e9-a87d-01798546f0d7.png)

Kein Rückschluss auf eingestellte Option und Auswahlfenster müsste größer sein

![image](https://user-images.githubusercontent.com/58858526/157671654-24b763e6-d956-48c8-a6d3-4086792d2b96.png)

**Comment by Apollon77** [comment]
Ich kapiers nicht :-( Er ist im korrekten Code-Block, sonst wäre die Markierung am Node nicht "gelb". kann also nur heissen das das setting nicht ankommt

https://github.com/ioBroker/ioBroker.node-red/blob/f7a073e8ee02c2f85a99e849a48dc65e60f62418/nodes/ioBroker.js#L579-L592

But it can only mean thet the value is not set/saved somehow :-( Could you try to add a logline before that block and log node.errOnInvalidState ?

**Comment by Apollon77** [comment]
PS: Ich hab auch das Feld mal "breiter "gemacht ... kannst bitte nochmal GitHub installieren

**Comment by Apollon77** [comment]
> Aber ich bestreite, dass vorher ein undefined zurückgegeben wurde.

Da stimme ich zu. Vorher wurde NICHTS zurückgegeben sondern nur was geloggt.

> Aber wie gesagt backward komptibel ist es nicht. Denn vorher wurde gar nichts zurückgegeben, siehe erstes Posting:

korrekt - hatte dich aber oben so verstanden. :-) ... Wenn wir es backward compatible haben wollen muss ich noch ein "return states without value" true/false setting machen. Kann ich tun. Sag an :-) Andererseits ist es ein Major increase was wir hier machen, wir könnten also hier breaken!

**Comment by mickym2** [comment]
Wenn es nicht zuviel Aufwand bedeutet - eine 3. Option rein zu machen (in der nichts zurückgegeben wird - ignore non existing states) - dann hätte man backward Kompatibilität und die Leute müssten in ihren bisherigen Flows ggf. keine Switch-Node zum herausfiltern anhängen. 

Ich glaube es wird ein tolles Release!!! - Endlich mal alle Dinge bereinigen. Ich danke schon mal dafür.

**Comment by Apollon77** [comment]
Have fun :-)) https://github.com/ioBroker/ioBroker.node-red/commit/38ee79157b5203c7a03e6a96eec382c9e1a4714e

Default ist jetzt das "backward compatible" und das loggt jetzt je nachdem ob objekt oder state empty ist was sinnvolles aber sendet nichts raus

**Comment by mickym2** [comment]
So das arbeitet perfekt, wobei eine Kleinigkeit wäre noch in meinen Augen. Der Fehlertext im error - wäre besser konstant. Durch die ID - kann man die entsprechende Node ja identifizieren. Der Vorteil eines konstanten Fehlertextes ist, dass ich diesen in einer anschließenden Switch-Node besser filtern kann. Im Moment geht es aber auch:
![image](https://user-images.githubusercontent.com/58858526/157700297-83b6f3a2-fabe-4cbe-9539-59e00a580106.png)

![image](https://user-images.githubusercontent.com/58858526/157699912-6cc7036b-3652-4185-baea-e7c5b835d2bf.png)

![image](https://user-images.githubusercontent.com/58858526/157700063-a6b739f8-82eb-4bb3-ab76-142b7834b25c.png)

Also alles gut. Nur für die Zukunft vielleicht noch als Hinweis. ;)

**Comment by Bernd9000** [comment]
Super, Danke
