### ISSUE TITLE
Update Node Red to 2.2.0

### ISSUE THREAD

**Issue by Schmetterfliege** [ioBroker/ioBroker.node-red#268]
A week ago, Node Red was updated to 2.2.0.

The version we're running right now is 1.3.7.
unfortunately I updated all the nodes in my palette, resulting in several nodes getting uninstalled due to version incompatibility.
This basically killed most of my flows, since we're on a version <2.0.0.

@GermanBluefox 
@Apollon77 
Gibt es schon Pläne, wann das Update auf 2.2.0 geplant ist?
Möchte da keinen Druck aufbauen, mich würde nur interessieren ob das zeitnah passieren wird.
Ansonsten würde ich NR vom IoBroker schmeißen und gesondert installieren, um auf der aktuellsten Version zu sein.
Mir hat es nämlich wirklich fast alle Flows zerschossen, weil Nodes nicht mehr existieren aufgrund der älteren NR Version :(

**Comment by Apollon77** [comment]
>  Gibt es schon Pläne, wann das Update auf 2.2.0 geplant ist?

Ja, sobald jemand dazu kommt. Wir arbeiten gerade intensiv an js-controller 4.0 und danach kommen auch andere Themen dran.

>  Mir hat es nämlich wirklich fast alle Flows zerschossen, weil Nodes nicht mehr existieren aufgrund der älteren NR Version :(

Naja ... aufpassen bei updates? Bzw Issues bei node-red und den plugns aufmachen das die mal was einbauen was bei breaking changes updates verhindert ... Sorry, aber DAS sehe ich gerade nicht als Issue vom Adapter :-)

**Comment by Apollon77** [comment]
Released in 3.0.0
