### ISSUE TITLE
create the abillity to use basic Authentification

### ISSUE THREAD

**Issue by simone1999** [ioBroker/ioBroker.node-red#27]
Hello,
Would it be possible to implement some easy authentification for node red?
It seems that your node red Instance ignores or resets the settings.js file from Node red, so it is not possible to use the bild in authentification. Please make the settings.js work like normally or even better add an configuration in ioBroker for adding an Username and Password to node red.

and thanks for the Work you are doing for us!

**Comment by thelightmaker** [comment]
**+1**
(https://nodered.org/docs/security)

**Comment by simone1999** [comment]
you are totally write and i used these methode before in stand alone node red, but installed over ioBroker these option doesn't seem to work, maybe i am doing sth. wrong...

but thanks for your reply!

**Comment by Apollon77** [comment]
We are happy to accept pull requests ;-)

**Comment by simone1999** [comment]
I'm sorry, but i am totaly new to github and don't know the "right" ways of doing things.

**Comment by GermanBluefox** [comment]
Code is welcome too.
