### ISSUE TITLE
ioBorker-out nur Datenpunkt erstellen

### ISSUE THREAD

**Issue by Bernd9000** [ioBroker/ioBroker.node-red#272]
In der Hilfe zu ioBorker-out heißt es:

`If msg.payload contains "__create__", the object will be only created, but no value will be written.`

Also habe ich ein nicht existierenden Topic übergeben und als payload `__create__`.
Der Datenpunkt wird in ioBroker erstellt aber es wird mit dem Wert `__create__` gefüllt.
Das heißt auf diesem Befehl wird nicht reagiert ?
Oder sind weitere Voraussetzungen nötig?

**Comment by Bernd9000** [comment]
Könnte das mit dieser Function zusammenhängen ?
Dort wird, so wie ich das sehe, auf jeden Fall der val Wert geschrieben.

iobroker.js :

 function setState(id, val, ack, callback) {
            if (node.idChecked) {
                if (val !== undefined && val !== '__create__') {
                    // If not this adapter state
                    if (isForeignState(id)) {
                        adapter.setForeignState(id, {val, ack}, callback);
                    } else {
                        adapter.setState(id, {val, ack}, callback);
                    }
                }
            } else {
                checkState(node, id, null, {val, ack}, isOk => callback && callback(!isOk));
            }
        }

**Comment by Apollon77** [comment]
... es sei denn der Wert lautet "create" ... scheinbar sind eie doppel-Unterstiche falsch und waren vllt als formatierung gedacht?

**Comment by Bernd9000** [comment]
Nein, ich glaub schon das die ein nicht alltägliches Schlüsselwort benutzen wollten.
Ich meinte aber viel mehr was auf die Bedingung folgt.
Wenn val vom Typ oder Wert entweder "create" und undefined ist wird der Datenpunkt erstellt und auf jeden Fall als Wert val übergeben.So wird dann ein Datenpunkt erstellt mit dem Inhalt "create".

Das hat mich auf eine schöne Möglichkeit gestoßen Datenpunkte zu erstellen die noch nicht existieren und vorhandene Datenpunkte auf keinen Fall zu überschreiben.

Einfach den payload vor dem ioBroker-out löschen.
Es wird zwar NULL im Datenpunkt eingetragen, aber es funktioniert erstmal.

**Comment by Bernd9000** [comment]
Aber es bleibt natürlich der Fehler bestehen das auf das Zauberwort `__create__` nicht richtig reagiert wird,

**Comment by mickym2** [comment]
Null ist aber genau richtig - da jeder Datenpunkt, der neu erstellt wird ein (null) für undefined enthält. 
Insofern braucht es hier in meinen Augen keine Änderung des Verhaltens, da die Datenpunkte ohne payload korrekt angelegt  werden. Das Einrichten eines leeren Datenpunktes mit dem __create__ Datenpunkt könnte man sich somit sparen, sollte halt den entsprechenden Hilfetext ändern. 

![image](https://user-images.githubusercontent.com/58858526/155861360-e685854c-d143-43e6-abd3-c1093d89a770.png)

So instead help text should be modified similar to:
- if no msg.payload is provided in the msg object - the state provided in topic is created without a value.

**Comment by GermanBluefox** [comment]
Fixed in next version

**Comment by Bernd9000** [comment]
Okay

**Comment by mickym2** [comment]
Der Hilfetext wurde nicht überarbeitet.

**Comment by Bernd9000** [comment]
Das stimmt zwar das der Hilfetext nicht bearbeitet wurde aber der eigentliche Fehler wurde behoben.
Übergibt man das Zauberwort "__create__" wird ein leerer Datenpunkt erstellt, vorher wurde in diesem Datenpunkt "__create__" geschrieben.

**Comment by Apollon77** [comment]
In fact both works ... so "mepty" payload and also "'__create__' so I will update docs for both but would not push new version out directly just because of this

**Comment by Apollon77** [comment]
Siehe commit, ich habe den text erweitert :-)
