### ISSUE TITLE
iobroker-list dynamic regex

### ISSUE THREAD

**Issue by rewegit** [ioBroker/ioBroker.node-red#273]
The iobroker-list can be configured via topic. This is very practical, e.g. if you put it in subflows. 
The output can be filtered with regex. This gives an enormous speed advantage compared to reading out the complete states with external filtering.
 
However, this is only possible statically, as it is not intended to pass the regex expression.
Would it be possible to pass it, for example, in the payload or in a separate key?

**Comment by GermanBluefox** [comment]
Implemented in next version

**Comment by mickym2** [comment]
In current git-hub version it is still not working.

**Comment by mickym2** [comment]
So I tested it and these are my results:

1. Dynamically specifying a string in msg.regex is working and does the same thing in the editor gui, but
2.  this is not working with a regular Expression - in my opinion it just looks like the string is part of the ID (simple string contains)

![image](https://user-images.githubusercontent.com/58858526/157709538-41ae01e8-4e35-4d25-ba22-3217c65365f9.png)

Regular expressions are not working well. 

![image](https://user-images.githubusercontent.com/58858526/157709707-c757adb1-78b4-4c56-9913-590820413688.png)

`.*` is working 

but other types of regular expression will fail - and there is no output at all.

![image](https://user-images.githubusercontent.com/58858526/157710941-55cd81d2-b6ab-4c1b-93d8-9db3524771ee.png)

**Comment by Apollon77** [comment]
lol ... ja ich sehe das Problem ... warte

**Comment by Apollon77** [comment]
Retry please

**Comment by mickym2** [comment]
wird eher schlimmer ;)

aus
`0_userdata\.\d.*`

`process list using regex /0_userdata\\.\\d.*/`

Mit dem doppelten Backslash maskierst Du doch einen Backslash in regulären Ausdrücken?

**Comment by mickym2** [comment]
In welcher Datei:

/opt/iobroker/node_modules/iobroker.node-red/nodes/ioBroker.js

(die ist aber vom Datum her alt)

Gesendet von Mail für Windows

Von: Ingo Fischer
Gesendet: Donnerstag, 10. März 2022 18:33
An: ioBroker/ioBroker.node-red
Cc: mickym2; Mention
Betreff: Re: [ioBroker/ioBroker.node-red] iobroker-list dynamic regex (Issue#273)

Heisst es tut nicht?? hhhmmm ... ok, dann versuch bitte mal eins (sollte an sich nicht gehen aber hey vltt haben wir falsch gedacht)
7be4f94
An den beiden Stellen mach das .replace(/\\/g, '\\\\') weg
Gehts dann?
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mickym2** [comment]
OK - ich habe glaub die richtige Datei gefunden - aber nun habe ich wieder das wie vorher:

`process list using regex /0_userdata\\.\d.*/`

![image](https://user-images.githubusercontent.com/58858526/157725273-94d5f8ba-f58b-4a7e-98c7-4cbb46be2f53.png)

**Comment by Apollon77** [comment]
aahh ... ich meinte mach mal das "replace" komplett weg.

also nur "...new RegExp(node.regex)"

**Comment by mickym2** [comment]
Ja das funktioniert super. ;)

![image](https://user-images.githubusercontent.com/58858526/157763392-3491d2be-c822-4d28-806f-2abb9b93c71f.png)

![image](https://user-images.githubusercontent.com/58858526/157763528-f1eb2563-6eaa-4572-ba51-ff210710c58c.png)


![image](https://user-images.githubusercontent.com/58858526/157763867-c15f5bd2-ceeb-4292-9dd8-7f78df40fa22.png)

Diese Änderung ist approved- 

Gibt aber noch ein anderes Problem mit der List Node - das ist mir erst die Tage aufgefallen - mach da ggf. neues Issue auf.

**Comment by Apollon77** [comment]
Github updated!

And yes ... create issue ... then I check if we can get that in too

**Comment by mickym2** [comment]
Nein fällt mir gerade nicht ein - falls mir was auffällt melde ich es - im Moment ist denke ich von der iobroker list node alles OK. ;)

**Comment by Apollon77** [comment]
Released in 3.0.0
