### ISSUE TITLE
Node module cannot be loaded on this version. Requires: >=2.0.0

### ISSUE THREAD

**Issue by Anzic23** [ioBroker/ioBroker.node-red#275]
can't use [node-red-contrib-alice](https://flows.nodered.org/node/node-red-contrib-alice) because node-ed version 2.0.0 is required
When is the node-red version expected to be upgraded to the current one?
adapter 2.4.2 
js-controller 3.3.22
Node.js v14.19.0
NPM 6.14.16
OS Docker on synology

**Comment by Apollon77** [comment]
soon ...

**Comment by Apollon77** [comment]
Duplicate #268
