### ISSUE TITLE
Help for non existing states in iobroker-IN Nodes.

### ISSUE THREAD

**Issue by mickym2** [ioBroker/ioBroker.node-red#277]
If an iobroker-IN node references a non existing state the following info is logged:

`<html>
<body>

node-red.0 | 2022-02-27 00:04:19.476 | info | Automatic objects creation is not enabled. You can enable it in the node configuration
-- | -- | -- | --

</body>
</html>`

It cost me some time to find out, that this message is created by iobroker-IN nodes referencing non existing states. 

So 2 suggestions:

1. Change the message in the log - as the current message does not give the correct hint on the root cause of the message.
2. The log should mentioned that it is caused by an iobroker-IN Node to an not existing state - and the node-ID that the user is able to search for the iobroker-in node which referenced the non-existing state.

**Comment by GermanBluefox** [comment]
Changed in next version

**Comment by Bernd9000** [comment]
Sehr gut, endlich kann man den Fehlern auf den Grund gehen :-)

![1](https://user-images.githubusercontent.com/77005685/157560264-260a248f-adcb-4011-af11-a269c0411538.jpg)

**Comment by mickym2** [comment]
Na schön wäre noch gewesen. wie ich angeregt hatte dass man die Node-ID in das Log aufgenommen hätte dann hätte man direkt danach suchen können.

**Comment by Apollon77** [comment]
Can be added ... I will try to add node.id to kind of "all" logs now ...

**Comment by Apollon77** [comment]
GitHub updated with logged node-id

**Comment by mickym2** [comment]
Great this is working:

![image](https://user-images.githubusercontent.com/58858526/157667926-9e3501cb-0a28-4a59-9cb6-11101a04c9a6.png)


![image](https://user-images.githubusercontent.com/58858526/157667996-7fb7f9c9-061b-4d04-9f98-91ca2b7caacd.png)

**Comment by Apollon77** [comment]
Cool, learned a lot :-)

**Comment by Apollon77** [comment]
Released in 3.0.0
