### ISSUE TITLE
iobroker get node for state object

### ISSUE THREAD

**Issue by WolfspiritM** [ioBroker/ioBroker.node-red#28]
Hi,

Would it be possible to introduce a new node (or maybe upgrade the existing "get" one) to read out informations about an object (not the state)?

For example I'm trying to set the color of different lights where for some lights hue is 0-360 while others have hue 0-65535. I set the topic at the beginning of my flow and would like to use a function in the end to convert the input payload to the correct format depending on the topic. ioBroker provides a common.min and common.max property but I don't see a way to use that from within node-red.

Maybe a dropdown in the iobroker get node where you can choose between "state" and "object" and then a switch in: https://github.com/ioBroker/ioBroker.node-red/blob/master/nodes/ioBroker.js#L361
to use getForeignObject instead of getForeignState would be enough for that...

**Comment by GermanBluefox** [comment]
I am overloaded :( 
But PRs are welcome :)
