### ISSUE TITLE
node-red-contrib-rfxcom

### ISSUE THREAD

**Issue by mac-d** [ioBroker/ioBroker.node-red#29]
Raspberry 3 / node-red V0.18.4 / ioBroker.js-controller 1.4.2 / node-red-contrib-rfxcom 2.4.0

Hello, after the last update (ioBroker) only one transmitter of my RFXCOM adapter (Power Meter - OWL) is read out (CM119 + CM160). According to the programmer (Maxwell Hadley), nothing was changed on the RFX module. In the node-red debug only one transmitter is displayed.
What can I do?

**Comment by GermanBluefox** [comment]
Contact Rfx com  developer ?
Except version of node-red is everything the same

ср, 16 мая 2018 г., 12:32 mac-d <notifications@github.com>:
