### ISSUE TITLE
Iobroker-IN Node - RBE filter description should be exchanged with/without initial value

### ISSUE THREAD

**Issue by mickym2** [ioBroker/ioBroker.node-red#290]
To have a consistent description of the rbe functionality and the rbe functionality of the filter node, the descriptions have to exchanged - what means initial value is ignored and vice versa.
![screen](https://user-images.githubusercontent.com/58858526/158555149-d86f81b4-a1dc-4ed2-b8c4-3361c267dfe8.png)

When initial value is ignored - no value will be sent and a value is sent when initial value is not ignored.

**Comment by Apollon77** [comment]
@mickym2 so this change? https://github.com/ioBroker/ioBroker.node-red/commit/75442a8dceaa50c1ffb917ecfcbaf65232283b1c

**Comment by Apollon77** [comment]
fixed in 3.1.0
