### ISSUE TITLE
Add "sendTo" Node to send messages to adapters

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.node-red#291]
e.g. for Telegram and other cases where we want request/response like communication and adapter supports it

**Comment by Sineos** [comment]
I'd really appreciate this feature. In my use case it would be valuble for working with homematic methods from within NR, e.g. `putParamset`, `reportValueUsage`, `rssiInfo` etc.

**Comment by setfire2** [comment]
I would also definitely make use of it.

**Comment by setfire2** [comment]
This would allow me to get rid of the Javascript adapter completely.

**Comment by klein0r** [comment]
Like this? FYI @mickym2 

<img width="1612" alt="Screenshot 2023-11-16 at 20 57 16" src="https://github.com/ioBroker/ioBroker.node-red/assets/1959049/68108285-4cbf-4c7f-ba6d-e417f3383316">

**Comment by mickym2** [comment]
No not only to the pushover adapter - General a Node which you can use to use directly the sendTo functionality to any iobroker adapter like the generic sendTo puzzle piece.  
![image](https://github.com/ioBroker/ioBroker.node-red/assets/58858526/a31a8bbd-381e-45c9-9612-84856a94bd87)
So you can decide which and how many parameters you want to send.

Therefore I didn't understand what this new puzzle was created: 

![image](https://github.com/ioBroker/ioBroker.node-red/assets/58858526/ba70d2fa-e28a-4f17-8aaf-5e5b6960887b)

with the generic, existing piece you could send messages to the mqtt adapter as well. 

![image](https://github.com/ioBroker/ioBroker.node-red/assets/58858526/6dc0b348-da1b-412a-b6b7-d975ef4ab5e5)

So within the node the adapter which should be addressed should be selectable, the command should be specified and variable options for parameters as requested by the adapter.  Same functionality as the generic SendTo puzzle in blockly.

**Comment by klein0r** [comment]
> No not only to the pushover adapter

Of course... I've thought the pushover example is self explanatory

<img width="1083" alt="Screenshot 2023-11-16 at 21 33 57" src="https://github.com/ioBroker/ioBroker.node-red/assets/1959049/b83daa83-856c-4d6d-84fe-ae4913747315">

**Comment by mickym2** [comment]
yes and then you need different parameters or objects depending on the receiving adapter.

**Comment by klein0r** [comment]
> and then you need different parameters

At the moment `msg.payload` is used. The example above is the same as this blockly:

<img width="439" alt="Screenshot 2023-11-16 at 21 42 13" src="https://github.com/ioBroker/ioBroker.node-red/assets/1959049/496c24bb-2ea9-4098-9176-a48eda87c383">

Please draw a mockup what do you expect.

**Comment by mickym2** [comment]
No then its fine - so the payload is then an object with different properties as requested by the adapter!

**Comment by klein0r** [comment]
> the payload is then an object with different properties as requested by the adapter

Yes, and the output message object contains the result.

I will add the possibility to set `msg.instance` and `msg.command` also via the msg object for maximum flexibility.

**Comment by mickym2** [comment]
Great
