### ISSUE TITLE
iobroker- In Nodes - block unless value change by more than .. doesn't work

### ISSUE THREAD

**Issue by mickym2** [ioBroker/ioBroker.node-red#293]
There is currently a problem - when a value has changed - the changed value is sent 5 times. (regardless which rbe setting is set).

![image](https://user-images.githubusercontent.com/58858526/159620079-6f5a3423-a075-46bc-83e9-d47d61810440.png)

This error occurs even in version 3.0.0
It looks - like the message was created by 5 different nodes. I marked them in different colors in the screen shot.

**EDIT: This problem cannot be reproduced - so I changed title.**

**Comment by Apollon77** [comment]
Please try Github version. On one hand I preventd subscriping for state changes multiple times for same node.id .. (just to be sure). And I log the initialization of in nodes ... enable debug log please

**Comment by mickym2** [comment]
This version does not run at all:
[current debug log.txt](https://github.com/ioBroker/ioBroker.node-red/files/8332740/current.debug.log.txt)

![image](https://user-images.githubusercontent.com/58858526/159693678-3a3fe20f-85ba-4b6d-ad41-a285cc849baf.png)

**Comment by mickym2** [comment]
In addition - the value input when value changes more than (ignore initial value) is missing:
![screen](https://user-images.githubusercontent.com/58858526/159695155-54e81c68-3d6b-4ae8-9ead-d2dd7c6ba9ac.png)

**Comment by mickym2** [comment]
So original error cannot be followed up, as it can't be reproduced. However the all versions when value changes more than - are not working - so I will change the topic in the title.

**Comment by Apollon77** [comment]
Noth shopud be fixed

**Comment by mickym2** [comment]
Ok - much better - but not completely fixed.

**Comment by mickym2** [comment]
Here is the log -
[current debug log.txt](https://github.com/ioBroker/ioBroker.node-red/files/8335382/current.debug.log.txt)

First problem is restart of the adapter and msg at start is selected:

![image](https://user-images.githubusercontent.com/58858526/159765270-4a7679ef-8e2c-4b4e-a04f-e43bf2bd3c42.png)


The initial value ignored when value changed behaves correct (no msg). The initial value ignored when value changed by xx - sends a msg, which should not the case. 

.... will be continued.

**Comment by Apollon77** [comment]
Ok, I do not get it ... Please try GitHub version. This version now uses "node.log to log all "logic stuff" per node ... mybe this brings some light.
It should log when value is pre-initialized and also for rbe/deadband logic when it is executed and with which values

**Comment by mickym2** [comment]
So there is no change in the behavior of the nodes. I tested change value with a fixed value - i.e. 5 and also with a percentage like 10%. In the log I see the comparison between old and new - but I do not see any reference to the value which defines the deadband,
[current debug log.txt](https://github.com/ioBroker/ioBroker.node-red/files/8336672/current.debug.log.txt)

**Comment by Apollon77** [comment]
The log schould not be in the iobroker log but "with the nodes" .. ok I can also move into iobroker log if easier? Just tell (und wieder deutsch?) :-)

**Comment by Apollon77** [comment]
PS: Aaaahhh ok werte auch da drin geloggt ... ok

**Comment by Apollon77** [comment]
ALso wenn "Deadband" log "false" sagt dann wird nichts getriggert!

**Comment by Apollon77** [comment]
Ok, lass mich log nochmal erweitern um ID und bei deadband um das limit

**Comment by Apollon77** [comment]
More logging added

**Comment by mickym2** [comment]
OK und bislang wurde Nachrichten erzeugt – egal ob Deadband false oder nicht – Ich hatte bislang noch keinen Fall wo keine Nachricht erzeugt wird. Selbst unveränderte Werte werden nicht geblockt bei diesem Deadband.

Gesendet von Mail für Windows

Von: Ingo Fischer
Gesendet: Mittwoch, 23. März 2022 22:09
An: ioBroker/ioBroker.node-red
Cc: mickym2; Author
Betreff: Re: [ioBroker/ioBroker.node-red] iobroker- In Nodes - block unlessvalue change by more than .. doesn't work (Issue #293)

Ok, lass mich log nochmal erweitern um ID und bei deadband um das limit

**Comment by mickym2** [comment]
Ok - only FYI - all deadband checks are not working - even when value is unchanged - those nodes send messages. - So I have to install the next version. ;)

**Comment by Apollon77** [comment]
Ooohh... wait i think I found the error!!!!

**Comment by Apollon77** [comment]
Try github again ... BTW: If it works now then deadband NEVER worked before. The comparism was wrong and I did not changed anything there

**Comment by mickym2** [comment]
May be this hasn't been used so much ... - but then it is even better if we eliminate those bugs as well - I am installing. ...

**Comment by mickym2** [comment]
Looks much better - still testing ... :)

**Comment by mickym2** [comment]
So as I said it looks much better - but at least during initialization I saw some errors - but currently I have somehow a deadlock situation. This happened during the test sometimes. I restarted the flows - and only update a topic with the same value - but get no more a connection to the in Nodes.

I refreshed browser. Nothing happens.
After restarting the adapter - it works again. 

So it looks good now - even if I am not sure - if everything has been tested. 

One problem could probably checked before deploy. So if no value is specified when option if value changed by xx  - the node accept this, instead refusing a deploy.

The description as it working now - should be changed into 

block until changes will by more **or equal** than 
[current debug log.txt](https://github.com/ioBroker/ioBroker.node-red/files/8336952/current.debug.log.txt)

So you did a fantastic job now. The only thing what creates a little headache are these situations when I had to restart the adapter - as the iobroker-In Nodes were disconnected. However - it might be that it will not happen, when there is not a lot of installations in the system. Same as yesterday - I do not know how this could happen - today this error never occurs again.

**Comment by mickym2** [comment]
So in summary - but not knowing if all is tested

1. The general problem is fixed- 
2. Check that in the deadband configuration a value or percentage is specified
3. description as it works now 
![screen2](https://user-images.githubusercontent.com/58858526/159805407-66a4a002-81b5-414d-b662-715247615c40.png)

**Comment by Apollon77** [comment]
> May be an input check would help.

Honestly ... no idea how to do that ... need to read into it ... please create an extra issue. will check when time

> text change ... block until changes will by more or equal than

Done on GitHub ... https://github.com/ioBroker/ioBroker.node-red/commit/bf3ca8a81dd836fabeb735df39af7b2d4f4e42b4

Ok???

Then I remove the logging for the value changes and we are done

**Comment by mickym2** [comment]
Ok - so go ahead with this version

The input check is normally done in the html file of the node. I have not enough knowledge - but it is not so important. ;)

![image](https://user-images.githubusercontent.com/58858526/159808984-abd5f04a-ee30-4045-bb10-b2c1dbde101b.png)
