### ISSUE TITLE
Allow multiple instances

### ISSUE THREAD

**Issue by Stefan592** [ioBroker/ioBroker.node-red#297]
Please allow multiple instances.

Steps for change:

- remove [Line](https://github.com/ioBroker/ioBroker.node-red/blob/master/io-package.json#L133)
![image](https://user-images.githubusercontent.com/14180760/161240553-e424af94-e8a1-4731-81fc-6b66ae2b6919.png)
- adapt userDir from [main](https://github.com/ioBroker/ioBroker.node-red/blob/master/main.js#L84) to  [fork](https://github.com/Stefan592/ioBroker.node-red/blob/master/main.js#L84)
![image](https://user-images.githubusercontent.com/14180760/161240477-9d60eae3-adf7-4563-bef7-44ac53eb7b2e.png)

Result: you can have multiple instances on different ports
![image](https://user-images.githubusercontent.com/14180760/161240726-6cfa325e-d780-49e6-8293-357ed426de7c.png)

@Apollon77

**Comment by dilmash** [comment]
I would also like to vote for such an extension especially because you can create a test environment to check changes before they go live.
