### ISSUE TITLE
Update from 2.4.2. to 3.2 leads to errors with all other updates

### ISSUE THREAD

**Issue by arndth** [ioBroker/ioBroker.node-red#299]
Hi,

after I have installed latest stable version I am not able to do any other installation anymore. I get npm errors ENOTEMPTY errors during any other instance update. It asks me to remove or rename different folders (e.g. acorn or acorn-walk). After I renamed the first folders it continued and I was asked to remove further folders. 

Could it be realted somehow to the newest node-red version? I tried different things, but at the end I saw that I can reproduce this error, when I update node-red to the latest version.

Best,
Arndt

Node.js v14.19.1
NPM 8.6.0
JS-Controller 3.3 and 4.0 (tested it first with 3.x and then updated to 4.x and got the same error)
Admin 5.3.2 and 5.3.8

**Comment by Apollon77** [comment]
This has nothing to do with node-red, this is somethong strangein your npm package tree ... normally when you get a NOEMPTY error from npm then it also tells you which directory or such and instrictions what to manually delete.

If this happens then something is strange and it could be that there are packages just used by node.red and that the update causes it, but noone else reported something like this after the upgrade.

As said, nothing to do with a single adapter ... In fact you need to manually fix all these issues (by removing anything he mentiones one after the other) or do a complete "reinstall" (aka delete node_modules, manually "npm i iobroker.js-controller" and then start it - and iobroker will install each adapter anew ... takes time but then you have a completekly fresh and clean npm tree.
