### ISSUE TITLE
Zusätzliche NPM-Module verhindern Start von node-red

### ISSUE THREAD

**Issue by jotata** [ioBroker/ioBroker.node-red#3]
Hallo!
Zuerst danke für die Integration von Node-Red. Finde es genial, die abläufe optisch zu programmieren un nutze es intensiv...

Nun habe ich damit begonnen, weidere NPM-Module für node-red in der Adapter-Konfiguration einzutragen. Gemäss Log werden die Module auch korrekt installiert. Danach lässt sich aber node-red nicht mehr starten. Im Log erscheint immer wieder 	"node-red exited with 0" und danach "Starting node-red: Pfad zum Modul".

Habe nun die coofnig-Datei von node-red genauer angeschaut. Dort werden automatisch durch die Adapter-Konfiuration folgende Zeilen eingetragen:
functionGlobalContext: {
        "node-red-contrib-moment": require("Pfad zum NPM-Modul")
        // os:require('os'),
        // bonescript:require('bonescript'),
        // arduino:require('duino')
    }

Wenn ich nun mit einem Texteditor die Zeile "node-red-contrib-moment ....." mittels "//" auskommentiere, wird node-red sofort gestartet und ist danach verfügbar. Interessanterweise ist dann auch das Modul "contrib-moment" in node-red vorhanden. 

Es sieht also so aus, wie wenn diese Zeile für das Modul zu eine Fehler beim Staretn von node-red führt und eigentlich gar nicht notwendig wäre.

Wäre toll, wenn ihr das untersuchen und beheben könnt, da ich sonst nach jedem Update wieder die Zeile auskommentieren muss, damit node-red funktioniert.
Danke!
JoTa

**Comment by GermanBluefox** [comment]
Was für ein System ist das? Kann unter Windows und Intel/Debian nicht reproduzieren.

**Comment by jotata** [comment]
Ist Linux (Synology DiskStation DSM 5.2).

**Comment by GermanBluefox** [comment]
Sollte hier gefixt sein: https://github.com/ioBroker/ioBroker.node-red/commit/d2b80c793efc53463f36e6f49956311036131e6a

**Comment by jotata** [comment]
JA, nun funktioniert es einwandfrei.
Vielen Dank!
