### ISSUE TITLE
Version 3.3.0 second instance logs every deploy

### ISSUE THREAD

**Issue by mickym2** [ioBroker/ioBroker.node-red#305]
The multi instance version works fine - and I had now 2 instances node-red.0 and node-red.1. 
The first instance (node-red.0) works as expected, there are no changes. 

The second instance (node-red.1) logs every deploy. In addition with a tail-node it seems that the log-file seems to be blocked somehow. So my request would be to cancel logging of a deploy as it works for the other instance. 

Each time you deploy something in node-red.1 creates the following info:

`<html>
<body>

node-red.1 | 2022-05-16 15:34:48.896 | info | Save /opt/iobroker/iobroker-data/node-red.1/flows.json
-- | -- | -- | --

</body>
</html>`

So it would be nice if this can be cancelled.

**Comment by Apollon77** [comment]
Are you sure you maybe not increased logging in your other node-red instance? I find nothing on opur side

**Comment by mickym2** [comment]
I do not know - where I should have specified this:

![image](https://user-images.githubusercontent.com/58858526/170772513-2d5f211c-279b-48ad-a5c5-fb7c966333f5.png)
![image](https://user-images.githubusercontent.com/58858526/170772665-12c228ef-5c00-4737-877e-293534f68974.png)

Only instance no.1 generates these info messages when I press deploy:

![image](https://user-images.githubusercontent.com/58858526/170772832-18cdd57d-1fe3-49e8-947d-7f4c634fcf10.png)

**Comment by Apollon77** [comment]
maybe in node-red itself?

**Comment by mickym2** [comment]
I do not know where - so here are the settings.js of both instances. The logging part is identical. I also deactivates all flows in instance 1. So my main instance does not log deploys - the new instance 1 does. Even the standalone version does not create these messages.

So here are the settings.js files of both instances - I cant see any setting - which is responsible for theses messages:
[settings_js.zip](https://github.com/ioBroker/ioBroker.node-red/files/8789284/settings_js.zip)

**Comment by Apollon77** [comment]
This is the issue ... also code wise I do not see a difference ... :-(

**Comment by mickym2** [comment]
Does it help to switch to debug for the 2nd instance? (node.red.1) - I also think that normally the output of  the node-red system console is redirected to the iobroker log - so is there a possibility to see where the origin of the message is - from adapter or node-red?

**Comment by mickym2** [comment]
So i changed to debug level
[log.txt](https://github.com/ioBroker/ioBroker.node-red/files/8789410/log.txt)

`2022-05-27 21:44:56.262 - debug: node-red.1 (16354) 27 May 21:44:56 - [info] Geänderte Nodes werden gestoppt

2022-05-27 21:44:56.264 - debug: node-red.1 (16354) 27 May 21:44:56 - [info] Geänderte Nodes sind gestoppt

2022-05-27 21:44:56.279 - debug: node-red.1 (16354) 27 May 21:44:56 - [info] Geänderte Nodes werden gestartet

2022-05-27 21:44:56.280 - debug: node-red.1 (16354) 27 May 21:44:56 - [info] Geänderte Nodes sind gestartet

2022-05-27 21:44:56.833 - info: node-red.1 (16354) Save /opt/iobroker/iobroker-data/node-red.1/flows.json`

The 4 debug messages that Nodes were stop and started - are messages from Node-Red. Those I know also from the standalone version. But the info message must have its origin within the adapter.

**Comment by Apollon77** [comment]
Also ja die Save /opt/iobroker/iobroker-data/node-red.1/flows.json` kommt vom Adapter ... aber ist das gleiche bei der normalen instanz. Gibt es das File bei dir?

Der liest das File regelmäßig und speichert es in einem Objekt. Das sind die flows.json und die flows_cred.json die er da nimmt.
Das Log würde höchstens nicht kommen wenn es kein flows.json gäbe ... Vergleicht da mal die beiden Instanzen.

**Comment by mickym2** [comment]
Klar gibt die Datei - dort werden ja alle Flows gespeichert. Dir flows_cred.json gibts bei mir noch nicht, da ich keine Credentials in der Testinstanz habe. ;)

**Comment by Apollon77** [comment]
hm ... legst DU die cred bitte testweise mal an? SOllte zwar nichts ändern aber als Versuch .... also von daher verstehe ich eher nicht warum es bei dir bei der ersten Instanz nicht auch kommt

**Comment by mickym2** [comment]
Die lege ich nicht selbst an - aber ich kann mal den Zugriff auf den mqtt Broker konfigurieren und dann wird die credential Datei automatisch erstellt.

![image](https://user-images.githubusercontent.com/58858526/170786971-f0b98a24-1ab4-4bd0-bbea-6d46bce8b19d.png)

Macht aber keinen Unterschied - die info Meldung kommt immer noch:

**Comment by Apollon77** [comment]
Ja wie gedacht ... ich wundere mich das sie bei deiner ersten Instanz nicht kommt

**Comment by Apollon77** [comment]
Could it be that you use "warn" as loglevel for your first instance and so just do not see the info logs?

**Comment by mickym2** [comment]
Also bei der 1. Instanz ist das noch nie gekommen. 

> Could it be that you use "warn" as loglevel for your first instance and so just do not see the info logs?
- No it is also info level. 

The difference between the productive instance (node-red.0) is that a project function is used and other directories. Before adapter version 3.3.0 it was not possible to have multiple instances - and I never saw these messages before in any of the adapter versions before - may be as no second instance was possible. 

Here are the same screenshots as above of the productive instance node-red.0

![image](https://user-images.githubusercontent.com/58858526/170790709-f296aab7-0a8e-47e7-9e5f-88d8c9753694.png)
![image](https://user-images.githubusercontent.com/58858526/170790793-645636bf-b4a8-4501-b99e-b11cfd500c04.png)

**Comment by mickym2** [comment]
I also switched on the option "Erstellung von Fremd-Objekten zulassen" - but no difference.

**Comment by Apollon77** [comment]
Das ist es ja ... Also am Ende könnte das nur heissen das das "File Change Detection" Feature bei deiner Haupt-Instanz nicht tut und keine Änderung erkennt ... ... ... wäre höchstens die Frage ob sich bei dir das Objekt aktualisiert wenn du neu deployest in node-red ...also "keine Meldung aber das Objekt bekommt trotzdem nen neuen "ts".

Gemeint ist das "node-red.X.flows" Objekt ...

**Comment by mickym2** [comment]
![image](https://user-images.githubusercontent.com/58858526/170794333-ad04c2cd-7ff2-484f-bfb3-118382443de5.png)

Nun der Unterschied ist vielleicht auch, da ich die Projektfunktion nutze - wird in der Hauptinstanz ja nicht im node-red Verzeichnis direkt geschrieben, sondern in den Projektverzeichnissen unten drunter. 

Das will ich nun auch nicht ändern. Mir geht es ja auch eigentlich nicht darum, diese Meldung zu bekommen, sondern ob man die nicht auf debug level drücken kann. Sie bringt doch keinen Mehrwert und jede Änderung Deines Flows im Log zu dokumentieren, halte ich nicht für sinnvoll. Die Projektfunktion nun bei der Testinstanz einzuschalten, will ich aber auch nicht. Da gibts  ja auch noch ein offenes Issue von mir. Wenns nicht geht, werde ich halt die 2. Instanz auf warn umschalten.

**Comment by Apollon77** [comment]
OPk, das macht sinn, ich ändere auf Debug

**Comment by Apollon77** [comment]
3.3.1 soon

**Comment by mickym2** [comment]
Thanks - it works!
