### ISSUE TITLE
Node-red UI is not loading anymore

### ISSUE THREAD

**Issue by lukiwinti** [ioBroker/ioBroker.node-red#307]
The Node Red "Flow Editor" is Working fine. http://ip:port/ui is an emty response. The Problem starts after a restart from the iobroker system.
<img width="1433" alt="Bildschirmfoto 2022-05-20 um 22 16 13" src="https://user-images.githubusercontent.com/59119861/169604367-06f19ef4-f7b8-4681-9099-c5af3cc3b559.png">
<img width="1433" alt="Bildschirmfoto 2022-05-20 um 22 15 43" src="https://user-images.githubusercontent.com/59119861/169604383-06870aed-c6bc-48a0-aed2-9ebf9349cccb.png">

**Comment by Apollon77** [comment]
What is "/ui"? What should be there?

**Comment by lukiwinti** [comment]
There is the Dashboard. I have Backup my Flows an reinstall Node red. Now the System is Working Fine.
