### ISSUE TITLE
"Lokale" Referenzierung auf node-red.x States geht nur auf erster Ebene

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.node-red#31]
siehe https://forum.iobroker.net/viewtopic.php?t=14306

Der Code behandelt State-Namen mit Punkten anders als ohne Punkte ... warum, unbekannt ...

**Comment by GermanBluefox** [comment]
Unclear reuqest

**Comment by Apollon77** [comment]
Could be that it is fixed with one of the latest changes ... I would close.
