### ISSUE TITLE
Give NodeRED command at startup?

### ISSUE THREAD

**Issue by Typ1er** [ioBroker/ioBroker.node-red#316]
I have a problem with a plugin in NodeRED. I need a command sent with the startup.

Here is a link to it, maybe someone can tell where to insert it, even if I am almost the only user who will use it.

With the plugin you can create your own characteristics in Homekit.
For docker and standalone solution there is the command, where can I add this in iobroker?

https://nrchkb.github.io/wiki/discover-more/experimental/

`In order to be able to use experimental features you have to start Node-RED with NRCHKB_EXPERIMENTAL=true environment variable.`

**Comment by Apollon77** [comment]
Sorry, but without code manipulations right now not possible ... 

could work with adjusting this line https://github.com/ioBroker/ioBroker.node-red/blob/master/main.js#L204

to be 

```
redProcess = spawn('node', args, { env: { ...process.env, NRCHKB_EXPERIMENTAL: 'true' } }});
```

(untested)

**Comment by Typ1er** [comment]
crashes at startup
<img width="955" alt="Bildschirmfoto 2022-07-31 um 14 00 44" src="https://user-images.githubusercontent.com/39628986/182025380-79e954b7-99c6-4dd7-b1ba-c63a98569433.png">

**Comment by Apollon77** [comment]
Oohh ... one ≠ too much at the end

**Comment by Typ1er** [comment]
Thank you, it works 👍

**Comment by GermanBluefox** [comment]
You can now set the envVars in the config
