### ISSUE TITLE
No restore for NodeRed instances with activated project function

### ISSUE THREAD

**Issue by mickym2** [ioBroker/ioBroker.node-red#320]
I do not understand why this is a problem of the Node Red adapter, but as requested - I create an issue here as well:

If someone uses the project function in a NodeRed instance nothing will be restored. As the flows are stored in the project subdirectory - and this folders remain empty - all flows are lost.
All flows are lost. The complete project directory subtree needs to be restored, to have the local github repository back which contains the history of the projects.

In addition all other directories remain empty as well. lib directory for own flow library and data which are stored from specific node types and contain specific informations (like cronplus etc.)

All node_modules should be restored automatically by restoring a package.json with their dependencies and executing a local npm install. (see https://github.com/simatec/ioBroker.backitup/issues/730)

The corresponding issue in the backitup can be found here: https://github.com/simatec/ioBroker.backitup/issues/731

**Comment by Apollon77** [comment]
@mickym2 Please provide details to where what is stored ... I do not use node-red and also so do not know what is special  when projects are used ... The problem also exists with the node_modules ... the default iobroker backup can only backup anything or nothing of a directory ...

**Comment by mickym2** [comment]
So if only all or nothing of a directory can be backuped - then the content of each node-red directory for each instance under iobroker-data should be backuped completely. 
If not all is backuped will lose functionality in each case. In general I am not a NodeRed developer, but I think I roughly understand the structure. So you have always a core installation with the core nodes and base functionality and then this is merged with one or more instances which can run in parallel. So the files of the core installation of the node-red adapter in the iobroker environment are in the node_modules directory under /opt/iobroker, the individual instances are then in the iobroker-data directory which contains also user defined node modules of either additional node types or any other node js library which can be installed and use in function nodes automatically. 

So let me start with the explanation of the files and directories how I meanwhile understood NodeRed.
I will start to explain first a node-red instance without the project functionality is switched on, which will be the case for 95% of users of the NodeRed adapter. In this case the flows.json is restored, which contains the whole logic and all flows, but the all additional nodes should be installed manually or placed in the adapter config - which is not practical and will cut meanwhile of the comfort of NodeRed to install those modules automatically.

 The problem I see, when I restored with the backitup adapter not the whole directory is restored and is mixed with some standard files. In addition all restored directories after restore with backitup adapter were empty. 

Unfortunately since version 2 of the NodeRed adapter there were made so adaptations to the javascript adapter which make things more complicated.  So with version 2 of the node-red adapter it has been introduced to specify additional nodes and npm modules in the adapter config, but it is much more comfortable to either node-red install additional node libraries automatically or via the palette-manager. However after restore with backit-up, not the original package.json is restored- only a standard one without any dependencies for additional modules. 

Part1:
So let me first discuss the Node-Red directory without project function switched on. 

![image](https://user-images.githubusercontent.com/58858526/184042847-4c22ff31-cd14-43cf-bc33-9a3369bba4ac.png)

So the hint the if the palette-manager is used additional nodes are not part of backup is a restriction which is in my opinion absolutely not necessary, if either the node_modules directory and the package.json is part of the backup. To save space of the backup it is only necessary to restore the package.json and execute a npm install in the instance directory of NodeRed. So I did this and everything was restored properly. 

So when backitup restored a node-red instance directory - the files were restore and only empty directories and an empty package.json without any dependencies were found. 
`{
    "name": "node-red-project",
    "description": "A Node-RED Project",
    "version": "0.0.1",
    "private": true
}`
But the flows. json and the credentials were restore as well. I guess the config files are restored as well, as the contain the path to the core nodes of the NodeRed core installation part.

So let me explain the contents of the node-red instance directory without project function:

![image](https://user-images.githubusercontent.com/58858526/184044174-0ce4bd68-54d1-435b-950f-1a435fac74b0.png)

So the files were restored, but overwritten with a standard, empty package.json - as shown above. So the first thing which should be changed is that the original package.json will be backuped and restored.

The settings.js is overwritten with each start of the node-red instance so all instances of node-red with the adapter will share the same settings. 

The config.user.json file contains only adaptations of the NodeRed editor, but becomes more important when the project function is activated. The config.node.json contains information to standard node types and are reference to the core part of the NodeRed installation. 

The flows.json is the most imprtant file as it contains all the logic and flows which are defined in this node-red instance.

**Comment by mickym2** [comment]
Part2:
So  the Node-Red directory with project function switched on.

**Comment by Apollon77** [comment]
The problem is that the current backup mechanism can not correctly backup symlinks and such and they happen in node_modules ... so first of all we need ajs.controller enhancement to exclude content from backup and such ... so not that easy. So yes a"supporting solution" from backitup could help here till this is realized in controller

**Comment by mickym2** [comment]
In my opinion it is fixed with separate NodeRed backup in backitup adapter.
