### ISSUE TITLE
After restarting node-red instance changes to settings.js are reverted

### ISSUE THREAD

**Issue by thohoj** [ioBroker/ioBroker.node-red#327]
Steps to reproduce:
1. Stop the node-red instance
2. Add this line to settings.js (before the last '}'):
´vshConnectionShowSettings: true,´
3. Save settings.js
4. Restart node-red instance

After the instance comes up the changes to settings.js disappears.

node-red adapter v3.3.1
(COMPACT) Starting node-red: --max-old-space-size=256 /opt/iobroker/node_modules/node-red/red.js -v --settings /opt/iobroker/iobroker-data/node-red/settings.js

Is this the right file to change the node-red config?
`/opt/iobroker/iobroker-data/node-red/settings.js`

**Comment by Apollon77** [comment]
This is intended behaviour. manual changes to settings.js are not supported - workaround is that you fo the changes in /opt/iobroker/node_modules/iobroker.node-red/settings.js . Pleaase make sure to not destroy the placeholders when doin changes. This needs to be done again when you update the adapter!

But better is to open feature requests on needed settings and reasons for that
