### ISSUE TITLE
[Question] How to switch back to ace editor?

### ISSUE THREAD

**Issue by thohoj** [ioBroker/ioBroker.node-red#332]
Is there an option in the adapter config UI to switch back to the ace editor? I tried an external node-red 3 instance before upgrading the adapter version, but monaco failed on iOS devices.

**Comment by Apollon77** [comment]
no, there is no option ... after discussion the main opinion was that monaco is stable enough ..

In fact you can edit /opt/iobroker/node_modules/iobroker-node-red/settings.js and adjust it ... You need to do that again once after installing a new version. THis is a workaround

**Comment by thohoj** [comment]
@klein0r Great news, thank you very much!
