### ISSUE TITLE
Wrong path when adding additional NPM modules?

### ISSUE THREAD

**Issue by morres83** [ioBroker/ioBroker.node-red#339]
Hello,

I was adding an additional packages via Iobroker (e.g. 'ws') like this:

![2022-10-27 08_16_09-Window](https://user-images.githubusercontent.com/10619650/198206122-3dadabb8-4252-4e04-bbea-47ec2766cb04.png)

By saving these settings, the `setttings.js` file in path `/opt/iobroker/iobroker-data/node-red`  gets modified like this:

![2022-10-27 08_20_21-Window](https://user-images.githubusercontent.com/10619650/198206556-bfc4196d-6017-42b1-9968-e6169782c9ac.png)

But the path `/opt/iobroker/node_modules/iobroker.node-red/node_modules/` does not even exist in the current Iobroker/Node Red installation. Instead, all the modules are saved in `/opt/iobroker/iobroker-data/node-red/node_modules`

Does Iobroker put the wrong path into the `settings.js` file?

**Comment by mickym2** [comment]
In my opinion this should be closed - as in standard NodeRed additional modules are always installed in "user" context and not in core installation.
