### ISSUE TITLE
"Rebuild Tree" aktuallisiert die Datenstruktur nicht

### ISSUE THREAD

**Issue by simone1999** [ioBroker/ioBroker.node-red#34]
Hallo,
nachdem ein neues Objekt in IoBroker angelegt wurde muss man immer den NodeRed Adapter neu starten, damit der die neuen Objekte/Datenpunkte in dem Select Dialog findet.

Es ist möglich den Pfad zu dem neuen Objekt direkt aus IoBroker zu kopieren und in den IoBroker NodeRed Nodes direkt einzufügen, jedoch finde ich den Select dialog teilweiße wesentlich Praktischer, starte aber Node Red nur sehr ungern neu, da jede Node, welche auf änderungen reagiert die erste Nachricht immer durchlässt auch wenn der Wert sich nicht geändert hat.

wäre echt super, wenn mit dem Butten "Rebuild Tree" die komplette Struktur neu eingelesen werden würde, damit man den select Dialog auch ohne neustarten nutzen kann.

Ps: Ich bin total begeistert von den Möglichkeiten die sich durch IoBroker und die ganzen Adapter ergeben, also echt klasse Arbeit!

**Comment by mobilutz** [comment]
It seems, that the button in the adapter settings is broken :|

**Comment by GermanBluefox** [comment]
I just checked the behavior and could see new variable after the button in config was pressed and refresh ob node-red browser (F5). No new restart of node-red.
