### ISSUE TITLE
https, ip address and localLink

### ISSUE THREAD

**Issue by crocri** [ioBroker/ioBroker.node-red#359]
Hello!
https secure = on makes no sense for ip addresses. If https, host name should be choosable (same as for homematic rpc adapters)
Workaround here is to set ip to name via "iob set node-red.0 --bind my.domain.com"

Further on,
"localLink": "http%s%://%ip%:%port%%httpAdminRoot%" doesn't work correct (https protocol is missing in overview/not set). So link in admin overview never works...

best regards
Crocri

**Comment by Apollon77** [comment]
Hhmmm ... yes and no ... "bind" is always going to a network interface and has nothingn to do with HTTPS ... But yes in fact then bind can not be used for creating the link ...

**Comment by crocri** [comment]
yes and no ;-)
If bind = IP -> no https possible, because https://IP:Port will never ever has a certificate (not allowed)
If bind = hostname, then certificate is possible: https://my.domain.com
So bind should be an interface, but with name, not ip address (esspecially for https)

In my opinion if bind = ip and https = on -> bug, not enhancement, because https never works
ok?

**Comment by Apollon77** [comment]
We say exactly the same ... The "general" topic is that iobroker do not know anything about "how the system is accessed as domain" ... admin since some versions has such support ... In fact we would need a new setting to set the "https domain to use" or such

**Comment by GermanBluefox** [comment]
> yes and no ;-) If bind = IP -> no https possible, because https://IP:Port will never ever has a certificate (not allowed) If bind = hostname, then certificate is possible: https://my.domain.com So bind should be an interface, but with name, not ip address (esspecially for https)
> 
> In my opinion if bind = ip and https = on -> bug, not enhancement, because https never works ok?

Wrong. If HTTPS is on, ioBroker still can start the interface on some IP address. How this IP address will be accessed, it is your task.
