### ISSUE TITLE
Wrong userDir on non-Zero instaces in 4.0.1

### ISSUE THREAD

**Issue by volkerrichert** [ioBroker/ioBroker.node-red#366]
in Line 81 of main js

`userDataDir += path.join(utils.getAbsoluteDefaultDataDir(),`node-red.${adapter.instance}`) + path.sep;`

the dir ist added a second time, which will result in an crash. the "+=" hast to be "="

Volker

**Comment by Apollon77** [comment]
Thank you! v4.0.2 on it's way with the fix

**Comment by volkerrichert** [comment]
Danke
