### ISSUE TITLE
Better German "save mode" Translation.

### ISSUE THREAD

**Issue by dekatWin** [ioBroker/ioBroker.node-red#367]
At the moment, save mode is translated in German as "Sicherheitsmodus".
More logical and better would be "Abgesicherter Modus".
*

![Screenshot 2023-03-25 09 43 31](https://user-images.githubusercontent.com/111662370/227708363-92aa1a2a-209c-4ded-bdcd-e86b00011003.png)
![Screenshot 2023-03-25 09 45 50](https://user-images.githubusercontent.com/111662370/227708370-5032f8fd-6ace-43a3-a362-8cdaa8674ef0.png)
![Screenshot 2023-03-25 10 15 02](https://user-images.githubusercontent.com/111662370/227708439-9a7a2391-a615-447a-a173-13d49c950439.png)

**Comment by Apollon77** [comment]
Danke, in Weblate geändert, PR mit änderun gkommt dann bald und geht in nächste version mit rein. Danke
