### ISSUE TITLE
iobroker-out does not create objects if topic is specified in node

### ISSUE THREAD

**Issue by mickym2** [ioBroker/ioBroker.node-red#369]
The iobroker node creates not existing topics if the the topic is variable and specified in the message objekt.  Fine!!!
even if the Folder Objects are not created on each level. 

![image](https://user-images.githubusercontent.com/58858526/228686929-30ffd812-748b-4c37-ba20-c6b5892037f6.png)

So functionality is Ok, even if under userdata not all objects in the hierarchy are created: 

![image](https://user-images.githubusercontent.com/58858526/228686030-cd4ef0ca-482d-4cf9-9b71-73738011522d.png)

topic is specified in the message objekt.

However if the topic is specified in the node - the object is no longer created: 

![image](https://user-images.githubusercontent.com/58858526/228686480-561912c2-9436-49e0-845a-7c696a1a0f62.png)

![image](https://user-images.githubusercontent.com/58858526/228686583-741fa283-2551-4ccd-87ce-1e4a08a0f037.png)

If you specify a payload type - then it seems that the object is created more reliable;

![image](https://user-images.githubusercontent.com/58858526/228688037-87fdde2f-6c3a-4218-aa51-4c03262c614e.png)

**Comment by GermanBluefox** [comment]
I cannot reproduce it

**Comment by mickym2** [comment]
I cannot reproduce it anymore either.
