### ISSUE TITLE
ssh key generating not working

### ISSUE THREAD

**Issue by huibuh420** [ioBroker/ioBroker.node-red#379]
Hi,
I would like to connect my flow with github.
To connect the flow with a github repo I need to generate a SSH key.
The problem is now, that it's not showing any key after pressing "Schlüssel generieren".
![image](https://github.com/ioBroker/ioBroker.node-red/assets/46418130/b46ec57e-ff9e-4db3-b7ab-bfc89c66f0a4)
In the logs I can't find any errors.
What is the root cause?

Nodered Cersion: 3.0.2

**Comment by Apollon77** [comment]
That more sounds like a "usage question when node-reed is running in iobroker". Maybe Forum is a better place to ask because the users that might know the answer are more likely to find there.

**Comment by klein0r** [comment]
> The problem is now, that it's not showing any key after pressing "Schlüssel generieren".

Looks like this is solved in Node-RED 3.1.x

<img width="706" alt="Screenshot 2023-11-17 at 10 49 36" src="https://github.com/ioBroker/ioBroker.node-red/assets/1959049/04f2cecd-7973-45e7-8375-3c253ff27091">

Keys are stored @ `iobroker-data/node-red/projects/.sshkeys/`
