### ISSUE TITLE
Verschlüsselte Credentials nicht gefunden

### ISSUE THREAD

**Issue by RALFISBORN** [ioBroker/ioBroker.node-red#387]
Hallo,
ich habe das gleiche Problem (https://github.com/ioBroker/ioBroker.node-red/issues/32) mit der aktuellen Version:

node-red.0
	2023-06-30 16:57:00.062	warn	30 Jun 16:57:00 - [warn] Verschlüsselte Credentials nicht gefunden
node-red.0
	2023-06-30 16:56:59.952	warn	30 Jun 16:56:59 - [warn] Projekte deaktiviert: editorTheme.projects.enabled=false
node-red.0
	2023-06-30 16:56:55.505	warn	Cannot enable the dynamic object read as admin has authentication

    Betriebssystem: linux Mint
    Architektur: x64
    CPUs: 4
    Geschwindigkeit: 1496 MHz
    Modell: Intel(R) Core(TM) i3-4020Y CPU @ 1.50GHz
    RAM: 7.6 GB
    Node.js: v18.16.1
    NPM: v9.5.1
    Pfad: /opt/iobroker/

Woran liegt die Fehlermeldung?
Vielen Danke und VG
![Adaptereinstellungen](https://github.com/ioBroker/ioBroker.node-red/assets/47441243/f4ea41e5-485a-42fe-891d-e3773c0d5c8b)

_Originally posted by @RALFISBORN in https://github.com/ioBroker/ioBroker.node-red/issues/32#issuecomment-1618915801_

**Comment by Alkazar-DH** [comment]
Ich hänge mich hier mal mit ran, habe das gleiche Problem.
Details siehe auch hier: [https://forum.iobroker.net/topic/67184/encrypted-credentials-not-found](url)

**Comment by Apollon77** [comment]
Ok and whats the real effect of this warning?

**Comment by RALFISBORN** [comment]
@Apollon77 Es gibt zumindest bei mir keine Auffälligkeit im Bezug auf die Funktionen. Nur die Warnmeldung ist störend bzw. muss es ja einen Grund hierfür geben.

**Comment by Apollon77** [comment]
Also der Adapter hat diesen Text nicht also kommt er von node-red selbst ... Mal dort suchen?

**Comment by RALFISBORN** [comment]
@Apollon77 Gute Frage, wo ich da zum suchen anfangen soll :(.

**Comment by klein0r** [comment]
Die Meldung bedeutet, dass keine `flows_cred.json` gefunden wurde. Das hat mit den Benutzerdaten nichts zu tun. In dieser Datei werden sensible Informationen von Configuration Nodes usw. gespeichert. Das heißt z.B. die Verbindungsdaten von den mqtt-nodes. Wenn man keine configuration nodes verwendet, wird die Datei nicht erstellt und somit bekommt man diese Warnung.

Mit Benutzerdaten hat das nichts zu tun.

**Comment by RALFISBORN** [comment]
@klein0r Danke für die Info. Dann könnte man ja auch einfach default mäßig bei der Adapter Installation eine leere .json Datei anlegen. Somit würde die Meldung nicht mehr kommen ;)

**Comment by klein0r** [comment]
> Danke für die Info. Dann könnte man ja auch einfach default mäßig bei der Adapter Installation eine leere .json Datei anlegen. Somit würde die Meldung nicht mehr kommen ;)

Das ist das Standard-Verhalten von Node-RED. Eine native Installation, ohne ioBroker drumrum, gibt mir das gleiche aus:

```
4 Dec 22:24:38 - [info] Benutzerverzeichnis: /home/pi/.node-red
4 Dec 22:24:38 - [warn] Projekte deaktiviert: editorTheme.projects.enabled=false
4 Dec 22:24:38 - [info] Flow-Datei: /home/pi/.node-red/flows.json
4 Dec 22:24:38 - [warn] Verschlüsselte Credentials nicht gefunden
4 Dec 22:24:38 - [info] Server wird jetzt auf http://127.0.0.1:1880/ ausgeführt
```
