### ISSUE TITLE
regex Informative log message fills the log window

### ISSUE THREAD

**Issue by dilmash** [ioBroker/ioBroker.node-red#389]
The message `{node.id}: process list using regex ...` in module iobroker.js line 987 often appears unnecessarily in the IOBroker log window. This message could perhaps be changed to:
```
adapter.log.debug(`${node.id}: process list using regex ${regex.toString()}`) 
```
so that it is only issued when "debug" log level is selected

**Comment by Apollon77** [comment]
PRs welcome :-)
