### ISSUE TITLE
[Bug] node 'ioBroker get' crashes node-red with js-controller >= 5.0.14

### ISSUE THREAD

**Issue by TheRealArthurDent** [ioBroker/ioBroker.node-red#408]
When using the node 'ioBroker get' to fetch a non-existing value causes a fatal crash of node-red when using a js-controller >= 5.0.14.
Most likely this is caused by [this change](https://github.com/ioBroker/ioBroker.js-controller/commit/965d186bf003bdd825a4429a406aece31e24f56d) in the js-controller.

For a detailed description, please refer to the respective [issue raised at js-controller](https://github.com/ioBroker/ioBroker.js-controller/issues/2539) inluding a suggestion on how to fix the issue.

**Comment by GermanBluefox** [comment]
Fixed
