### ISSUE TITLE
Update von nodes nicht möglich

### ISSUE THREAD

**Issue by libertyx82** [ioBroker/ioBroker.node-red#41]
Mir werden bei zwei Nodes Updates angeboten, wenn ich dann auf update klicke erhalte ich die Meldung.

```
Failed to update: node-red-dashboard

Module not locally installed

Check the log for more information
```

![image](https://user-images.githubusercontent.com/22996350/49462878-77947180-f7f7-11e8-9960-a2f0797d4624.png)

**Comment by Apollon77** [comment]
Wie wurden die hinzugefügt? Über die Adapter Konfiguration? Dann bitte mal Adapter neu starten.

**Comment by libertyx82** [comment]
Die waren standardmäßig nach der Installation des Adapters vorhanden, also nicht nachträglich hinzugefügt.
Adapter und Raspi wurden schon neu gestartet.

**Comment by libertyx82** [comment]
Ich wollte das jetzt über CLI updaten, aber das geht auch nicht.

Das Modul (node-red-node-email) z.B. liegt in 2 Ordnern.
```
/opt/iobroker/node_modules/iobroker.node-red/node_modules/node-red-node-email
/opt/iobroker/node_modules/node-red-node-email
```
Ich habe beide mit npm update node-red-node-email aktualisiert, npm ls sagt auch, bei beiden Ordnern v1.0.7 aber im NodeRed steht noch immer v0.1.29 und hier lässt sich das Update nicht ausführen.

Das Modul wurde nicht nachträglich installiert sondern ist direkt nach der Installation des Adapters vorhanden.
