### ISSUE TITLE
confusing release notes

### ISSUE THREAD

**Issue by ChrisPrefect** [ioBroker/ioBroker.node-red#410]
The release notes for version 5.0.0 say:

`NodeJS 16.4.x is required`

So this means it won't work with my version v18.17.1?

**Comment by ChrisPrefect** [comment]
So the release notes seem to be true. It does not work after updating with V18.17.1.

I just get this when clicking on the node red tab.

![image](https://github.com/ioBroker/ioBroker.node-red/assets/3579863/1af901c8-6455-4762-8988-23a2a6a779fa)

**Comment by klein0r** [comment]
> NodeJS 16.4.x is required

That is the minimum required version. Will also work with nodejs 18.x and even 20.x

Please share a log with debug log level

**Comment by ChrisPrefect** [comment]
Ah, so the release notes were wrong and "minimum" was missing. That solves it.

After letting iobroker sit for one night without changing anything and without restarting the adapter, the errors just went away, and the node red panel is loading now...

Thanks!

**Comment by klein0r** [comment]
> Ah, so the release notes were wrong and "minimum" was missing.

Mh, okay... But: No adapter requires a specific NodeJS version.
Everything is specified as a minimum (like js-controller or admin dependencies).

**Comment by Apollon77** [comment]
fixed in readme
