### ISSUE TITLE
Changes to settings.js get overwritten on every start

### ISSUE THREAD

**Issue by Vermatic** [ioBroker/ioBroker.node-red#42]
I want to make use of ‘Persistent Context’ in Node RED, but this requires a change to settings.js as explained here:
[https://discourse.nodered.org/t/a-guide-to-understanding-persistent-context/4115](https://discourse.nodered.org/t/a-guide-to-understanding-persistent-context/4115)

I want to add the following section:
`
    contextStorage: {
        default : { module: "memory" },
        file : { module: "localfilesystem" }
    },
`

It seems that _settings.js_ is stored in _./iobroker-data/node-red/settings.js_ however this file is rewritten on every start by _main.js_.

What is the best way to add permanent changes to _settings.js_?

**Comment by Vermatic** [comment]
Hm, I noticed that ._/node_modules/iobroker.node-red/settings.js_  is used as some kind of template.

So I added the section mentioned in the original post here instead.

With this change the section ends up in _./iobroker-data/node-red/settings.js_ as well and Node RED continues to start up correctly.

I am wondering if there is a more "standard way" for the customization of _settings.js_ instead.

**Comment by Apollon77** [comment]
Yes, add the configurable items into the adapter confog and let the adapter write them into the config file. So they are easy configurable :-) This would be the "standard way"

**Comment by Vermatic** [comment]
Thank you very much for confirming that the modification of the adapter config "template" is the preferred way of modifying the config that is used for the adapter when it is run.

**Comment by Apollon77** [comment]
We are hapy to accept PRs for such changes and will also support any developer that want to try it

**Comment by SaimenSays** [comment]
There is a problem with the suggestion, adding the settings to ` ./node_modules/iobroker.node-red/settings.js `. An update of Node-Red adapter will overwrite the file and so kill your settings! So the file context is no more available after update.
