### ISSUE TITLE
Expose credential-secret for encrypted credentials in adapter config

### ISSUE THREAD

**Issue by mickym2** [ioBroker/ioBroker.node-red#423]
With the last update - the encrypted credential are lost. 
See change log for Adapter update 5.0.0
> NodeJS 16.4.x is required Please check instance configuration and re-enter your passwords (encryption has changed).

Why is it not possible to expose an own encryption-secret key in the adapter config ? - When using an own encryption key this can be part of the backup as well.  This is offered by settings.js - so it should no longer a problem to keep encrypted credentials - even after a fresh installation

    /** By default, credentials are encrypted in storage using a generated key. To
     * specify your own secret, set the following property.
     * If you want to disable encryption of credentials, set this property to false.
     * Note: once you set this property, do not change it - doing so will prevent
     * node-red from being able to decrypt your existing credentials and they will be
     * lost.
     */
    //credentialSecret: "a-secret-key",

**Comment by klein0r** [comment]
Should have the same value as in previous version 4.0.3:

https://github.com/ioBroker/ioBroker.node-red/blob/b6d11f2e9af75c39acb0a258d1fe0a4760517040/main.js#L560-L568

**Comment by mickym2** [comment]
No - when i updated the test system - I got the message that my credentials can't be read - and I had to specify new ones. But if this is fixed for the future, then this can be closed. - I will not upgrade my production system as NodeRed 3.1.1 has some bugs in validation of standard nodes.

**Comment by mickym2** [comment]
> Should have the same value as in previous version 4.0.3:
> 
> https://github.com/ioBroker/ioBroker.node-red/blob/b6d11f2e9af75c39acb0a258d1fe0a4760517040/main.js#L560-L568

In my opinion with until adapter 4.0.3 (incl.) this credentialSecret was never set in the settings.js as per default in NodeRed. Therefore as described NodeRed created internally a key - but I dont know where this key is stored. 

I can only see - IF the project function is enabled - the secrets are stored in the .config.project.json

cat .config.projects.json
{
    "projects": {
        "MWHome": {
            "credentialSecret": "41HGmm4jowbb6j???????"
        },
        "MWTest": {
            "credentialSecret": "41HGmm4jowbb6j???????"
        }
    },
    "activeProject": "MWHome"

**Comment by klein0r** [comment]
> In my opinion with until adapter 4.0.3 (incl.) this credentialSecret was never set in the settings.js as per default in NodeRed.

Just check the code of [tag 4.0.3](https://github.com/ioBroker/ioBroker.node-red/tree/v4.0.3):

https://github.com/ioBroker/ioBroker.node-red/blob/b6d11f2e9af75c39acb0a258d1fe0a4760517040/main.js#L363

https://github.com/ioBroker/ioBroker.node-red/blob/b6d11f2e9af75c39acb0a258d1fe0a4760517040/settings.js#L44

**Comment by mickym2** [comment]
Ok - but why does the upgrade not set then an existing secret? - As you see from the screen shot - the existing flows_cred.json couldn't be decrypted.

**Comment by klein0r** [comment]
Thanks, after checking everything again, the replacement of the credentials string isn't working... I will create a PR

**Comment by klein0r** [comment]
Please test 5.0.1

**Comment by mickym2** [comment]
Ok - many thanks - the credentials are accessible  and now no message appears after upgrade. Great many thanks!!!

- As I said - I will wait until NodeRed problems are fixed.

**Comment by mickym2** [comment]
Supplement: The users with version 4.0.3 can now upgrade without problems - however users who want to upgrade from 5.0.0 to 5.0.1 will lose their credentials now. Only for your information.
