### ISSUE TITLE
npm module installation fails with scoped modules

### ISSUE THREAD

**Issue by holomekc** [ioBroker/ioBroker.node-red#425]
Adding for example the following module to the instance configuration:
@node-red-contrib-themes/theme-collection

fails with:
```
Starting node-red: --max-old-space-size=512 /opt/iobroker/node_modules/node-red/red.js -v --settings /opt/iobroker/iobroker-data/node-red/settings.js
Error loading settings file: /opt/iobroker/iobroker-data/node-red/settings.js
node-red exited with 0
```

Logs are set to "All"

**Comment by klein0r** [comment]
Which adapter version is used? Please provide more information

**Comment by holomekc** [comment]
Node: 18.19.0
Npm: 10.2.3
Iobroker: 5.x (i cannot see it right now on my iPhone)
Node-red adapter: 4.0.3

**Comment by holomekc** [comment]
This seems to work:
https://github.com/ioBroker/ioBroker.node-red/blob/b6d11f2e9af75c39acb0a258d1fe0a4760517040/main.js#L313-L321

```javascript
 for (let a = 0; a < additional.length; a++) { 
     if (additional[a].startsWith('node-red-') || additional[a].startsWith('@node-red-')) { 
         continue; 
     } 
     npms += `        "${additional[a]}": require("${dir}${additional[a]}")`; 
     if (a !== additional.length - 1) { 
         npms += ', \r\n'; 
     } 
 } 
```

Not sure what implications this might have though. The code changed in 5.x, but I think logically it is the same except the linebreaks.
