### ISSUE TITLE
Update NR to 3.1.3

### ISSUE THREAD

**Issue by mickym2** [ioBroker/ioBroker.node-red#426]
Please update the current NodeRed Version. The version 3.1.1 which is included in the adapter 5.0.x is buggy and has problems with validation with standard nodes. 

https://github.com/node-red/node-red/issues/4464

This is fixed with 3.1.3

![image](https://github.com/ioBroker/ioBroker.node-red/assets/58858526/72b39427-f193-4b2e-afc2-f5ec28c94df3)

**Comment by klein0r** [comment]
3.1.3 is already defined in the package json

https://github.com/ioBroker/ioBroker.node-red/blob/75453334ae441182e8356aa587b6079e0cada3ec/package.json#L43

**Comment by mickym2** [comment]
Ok - thanks I didn't update to adapter version 5.0.2 as I haven't seen a NodeRed update in the ChangeLog. But I installed 5.0.2 and everything is fine and NodeRed 3.1.3 is included. 

Many thanks!!!!
