### ISSUE TITLE
settings.js Anpassung notwendig durch Änderungen bei dem Modul node-red-contrib-ccu

### ISSUE THREAD

**Issue by xast1211** [ioBroker/ioBroker.node-red#43]
Es fehlt in den Settings der Eintrag für das Logging. Durch eine Änderung im oben genannten Modul, stürzt Node-Red ab. Im Modul (ccu_connection.js:392 - RED.settings.logging) wird neuerdings auf die Logging Einstellungen zugegriffen.

**Comment by Apollon77** [comment]
Welche Anpassung genau müsste denn an der config gemacht werden?

**Comment by xast1211** [comment]
Es fehlen die Logging Einstellungen:

In der Datei:
/opt/ioBroker/node_modules/iobroker.node-red/settings.js

fehlen die Logging Parameter. Folgendes muss hinzugefügt werden.

` // Configure the logging output
    logging: {
        // Only console logging is currently supported
        console: {
            // Level of logging to be recorded. Options are:
            // fatal - only those errors which make the application unusable should be recorded
            // error - record errors which are deemed fatal for a particular request + fatal errors
            // warn - record problems which are non fatal + errors + fatal errors
            // info - record information about the general running of the application + warn + error + fatal errors
            // debug - record information which is more verbose than info + info + warn + error + fatal errors
            // trace - record very detailed logging + debug + info + warn + error + fatal errors
            // off - turn off all logging (doesn't affect metrics or audit)
            level: "info",
            // Whether or not to include metric events in the log output
            metrics: false,
            // Whether or not to include audit events in the log output
            audit: false
        }
    },`

Siehe Original settings.js von Node-Red.

**Comment by GermanBluefox** [comment]
Done
