### ISSUE TITLE
iobroker.list not does not evaluate correct ts when not reading values

### ISSUE THREAD

**Issue by mickym2** [ioBroker/ioBroker.node-red#432]
If the list node does not read values then the last ts in the returned objects is incorrect. (Seems as this ts contains then the creation date of the object). 

Only if the list node reads all values of the selected objects the correct timestamp (ts) is returned in the objects: 

![image](https://github.com/ioBroker/ioBroker.node-red/assets/58858526/6102e081-b804-4deb-8434-df26268f7a09)

**Comment by GermanBluefox** [comment]
Works as designed. As without values, the creation time of **object** is placed in ts. 
If the values will be read, the ts value shows when the **Value** of State was updated.
