### ISSUE TITLE
node-red-contrib-amazon-echo nicht mehr kompatibel mit v5.1.0?

### ISSUE THREAD

**Issue by nicomania** [ioBroker/ioBroker.node-red#437]
Hallo,
seit dem Update von v4.x auf v5.1.0 funktioniert mein [node-red-contrib-amazon-echo](https://flows.nodered.org/node/node-red-contrib-amazon-echo) nicht mehr. 

![image](https://github.com/ioBroker/ioBroker.node-red/assets/35151132/b26aae57-417e-44ff-a87e-98400ce2ff4b)

In der Debugausgabe bekomme ich folgende Meldungen nach einem Neustart des Flows:

![image](https://github.com/ioBroker/ioBroker.node-red/assets/35151132/0466496f-c776-4458-928a-0231bc8dfa8d)

Ist das nicht mehr kompatibel? Gibt es Abhilfe? Was kann ich tun?

Danke und VG

**Comment by klein0r** [comment]
Schau mal hier https://github.com/datech/node-red-contrib-amazon-echo/wiki/Troubleshooting

Hat ja erstmal mit dem ioBroker-Adapter nichts zu tun.

**Comment by nicomania** [comment]
ah, ok, danke. Hatte für mich gefühlt mit dem letzten Update zu tun. Gleichzeitig gab es ja einige Updates des Admin Adapter, Webserver, etc.. Gab es hier evtl. eine Beeinflussung?

Dein Link ist für mich leider so erst einmal nicht hilfreich. Ich kenne ihn auch schon aus der Vergangenheit, als ich versuchte selbiges Konstrukt mit iobroker im docker auf meiner Synology zum Laufen zu bringen. Dort hatte das Synology Webinterface Port 80 besetzt. Daher weiss ich, dass meine Versuche mit redirect und proxy leider nicht halfen. Nun war ich eigentlich froh, dass auf Proxmox mein Node lief. Bis gestern....

**Comment by klein0r** [comment]
> ah, ok, danke. Hatte für mich gefühlt mit dem letzten Update zu tun.

Naja damit wurde ja wahrscheinlich auch die Node-RED Version angehoben (auf 3.1.x). Das hängt also eher mit der Node-RED Version zusammen als mit der ioBroker-Instanz.

Der Admin-Adaper oder Web-Adapter haben damit ja gar nichts zu tun. Von der Existenz weiß Node-RED ja nicht einmal etwas...

**Comment by nicomania** [comment]
ok, verstehe. In der Changelog sehe ich tatsächlich, dass die Node-RED Version auf 3.1.0 angehoben wurde. Ein Downgrade des Adapters auf Version 4.0.3 hilft aber leider nicht. 


![image](https://github.com/ioBroker/ioBroker.node-red/assets/35151132/754a7e73-ac51-43d5-80f1-69dcb05cb79b)

**Comment by eltoro312** [comment]
Gibt es hierfür schon eine Lösung?
Oder muss man sich alternatven suchen?

**Comment by eltoro312** [comment]
Update durchgeführt und Adapter funktioniert weiterhin

**Comment by nicomania** [comment]
> Update durchgeführt und Adapter funktioniert weiterhin

Hier geht es ja auch um den [node-red-contrib-amazon-echo](https://flows.nodered.org/node/node-red-contrib-amazon-echo) und nicht um den Adapter.
