### ISSUE TITLE
Since update to 5.1 Node-RED doesn't read locally saved context files anymore

### ISSUE THREAD

**Issue by PrinzVonBillAir** [ioBroker/ioBroker.node-red#439]
I updated the ioBroker Adapter of Node-RED to version 5.1 and after the adapter restart I noticed that the locally saved file of context data (saved by previous Node-RED versions in .\ioBroker\iobroker-data\node-red\context\xxx\flow.json) isn't loaded as context data anymore. Only the context-data which is written in memory is loaded upon start. If I manually trigger a save to (local) file it will get loaded into context data but not saved in the file that was mentioned above and used by previous versions of Node-RED but somewhere else. Where? I don't know.

**Comment by PrinzVonBillAir** [comment]
Problem is solved. The issue was the file ./opt/iobroker/node_modules/iobroker.node-red/settings.js was apparently overwritten during the update so the manually added Node-RED context file options weren't active anymore.

[This post](https://forum.iobroker.net/post/206820) helped me to solve my problem.

**Comment by klein0r** [comment]
> The issue was the file .\opt\iobroker\node_modules\iobroker.node-red\settings.js was apparently overwritten

The file will be overwritten when the instance start. Let me know which config changed do you need and we can discuss to add those flags / options to the default or make them configurable.

**Comment by klein0r** [comment]
> That's not what I can confirm. As mentioned in [this post](https://forum.iobroker.net/post/206820) the file .\iobroker\node_modules\iobroker.node-red\settings.js

Ah, you edit the template. Sorry I've haven't seen that. I agree that "persistent context" should be an option.

Maybe we have to write an own module to ensure that the context will survive an update of node-red.
