### ISSUE TITLE
System Console not working anymore

### ISSUE THREAD

**Issue by holomekc** [ioBroker/ioBroker.node-red#444]
Hi, 
first of all thx for the awesome adapter.

I recently noticed that the system console logs of the debug node does not work anymore.
In earlier versions they ended up in the "Protocol" of ioBroker.

I checked the settings, but could not find an option, which would control that. Can you please check if something is broken?

Br,
Chris

**Comment by frankyboy1973** [comment]
Hi, here the same. I can only see the output in the iobroker Protocol, if the NodeRed-nstance output is on debug

**Comment by Apollon77** [comment]
Can you tell with which version of the adapter it started? maybe try to downgrade one by one and verify it? This could help a lot to find potential reasons

**Comment by klein0r** [comment]
> In earlier versions they ended up in the "Protocol" of ioBroker.

Which log level is configured in the ioBroker instance?

**Comment by frankyboy1973** [comment]
Hi, it started with Version 5.1.0.
In Version 5.0.2 the Output of the Debug Node is shown in the Iobroker Log with Node Red Instance at Log Level Info.
In Version 5.1.0 the Output of the Debug Node is only shown in the Iobroker Log with Node Red Instance at Log Level Debug.

**Comment by Apollon77** [comment]
@klein0r I think in the past we always had "iobroekr debug loglevel means iobroker-debug.logs" and "info means iobroker.info and node-red-debug"

**Comment by holomekc** [comment]
> Which log level is configured in the ioBroker instance?

Info

**Comment by mickym2** [comment]
I hope that getting the debug Node system console output will be available on info level of the adapter will be implemented soon.

**Comment by mickym2** [comment]
When this will be fixed? - In Version 5.2.0 which I installed today - still all my debug nodes are invisible in the iobroeker log on info level.

**Comment by Apollon77** [comment]
5.2.1 coming soon
