### ISSUE TITLE
Version 5.1.0 - Alexa Controller logging

### ISSUE THREAD

**Issue by hoepps2802** [ioBroker/ioBroker.node-red#445]
Hi,

ich habe gestern auf 5.1.0 geupdatet

Jetzt  logt node-red jedes Request vom Alexa Controller mit:

`<html>
<body>

node-red.0 | 2024-02-27 06:27:09.285 | info | Node-RED: 27 Feb 06:27:09 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.30-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/6fd5e8038f8de8
-- | -- | -- | --
node-red.0 | 2024-02-27 06:26:45.422 | info | Node-RED: 27 Feb 06:26:45 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.26-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/eb79140d6cff28
node-red.0 | 2024-02-27 06:26:29.933 | info | Node-RED: 27 Feb 06:26:29 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.30-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/3d47429bbe4c46
node-red.0 | 2024-02-27 06:26:21.497 | info | Node-RED: 27 Feb 06:26:21 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.135-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/6fd5e8038f8de8
node-red.0 | 2024-02-27 06:26:09.913 | info | Node-RED: 27 Feb 06:26:09 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.54-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/eb79140d6cff28
node-red.0 | 2024-02-27 06:25:51.977 | info | Node-RED: 27 Feb 06:25:51 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.27-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/3d47429bbe4c46
node-red.0 | 2024-02-27 06:24:58.005 | info | Node-RED: 27 Feb 06:24:58 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.49-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/85cdc964ee40f8
node-red.0 | 2024-02-27 06:24:25.838 | info | Node-RED: 27 Feb 06:24:25 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.54-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/3d47429bbe4c46
node-red.0 | 2024-02-27 06:24:11.780 | info | Node-RED: 27 Feb 06:24:11 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.49-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/76b4fc984e3b74
node-red.0 | 2024-02-27 06:24:06.046 | info | Node-RED: 27 Feb 06:24:06 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.135-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/f82a95499c16cce1
node-red.0 | 2024-02-27 06:23:56.789 | info | Node-RED: 27 Feb 06:23:56 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.49-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/eb79140d6cff28
node-red.0 | 2024-02-27 06:23:47.403 | info | Node-RED: 27 Feb 06:23:47 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.54-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/76b4fc984e3b74
node-red.0 | 2024-02-27 06:23:38.233 | info | Node-RED: 27 Feb 06:23:38 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.135-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/eb79140d6cff28
node-red.0 | 2024-02-27 06:23:34.948 | info | Node-RED: 27 Feb 06:23:34 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.26-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/85cdc964ee40f8
node-red.0 | 2024-02-27 06:23:22.840 | info | Node-RED: 27 Feb 06:23:22 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.49-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/6fd5e8038f8de8
node-red.0 | 2024-02-27 06:23:19.804 | info | Node-RED: 27 Feb 06:23:19 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.26-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/f82a95499c16cce1
node-red.0 | 2024-02-27 06:23:15.811 | info | Node-RED: 27 Feb 06:23:15 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.49-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/f82a95499c16cce1
node-red.0 | 2024-02-27 06:22:50.712 | info | Node-RED: 27 Feb 06:22:50 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.27-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/6fd5e8038f8de8
node-red.0 | 2024-02-27 06:22:40.400 | info | Node-RED: 27 Feb 06:22:40 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.27-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/76b4fc984e3b74
node-red.0 | 2024-02-27 06:22:30.363 | info | Node-RED: 27 Feb 06:22:30 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.27-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/eb79140d6cff28
node-red.0 | 2024-02-27 06:22:25.973 | info | Node-RED: 27 Feb 06:22:25 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.135-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/d5a046564eef28
node-red.0 | 2024-02-27 06:21:55.118 | info | Node-RED: 27 Feb 06:21:55 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.26-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/d5a046564eef28
node-red.0 | 2024-02-27 06:21:40.083 | info | Node-RED: 27 Feb 06:21:40 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.54-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/f82a95499c16cce1
node-red.0 | 2024-02-27 06:21:26.754 | info | Node-RED: 27 Feb 06:21:26 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.30-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/d5a046564eef28
node-red.0 | 2024-02-27 06:21:24.956 | info | Node-RED: 27 Feb 06:21:24 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.27-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/d5a046564eef28
node-red.0 | 2024-02-27 06:21:16.427 | info | Node-RED: 27 Feb 06:21:16 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.161-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/f82a95499c16cce1
node-red.0 | 2024-02-27 06:20:56.388 | info | Node-RED: 27 Feb 06:20:56 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.30-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/76b4fc984e3b74
node-red.0 | 2024-02-27 06:20:56.291 | info | Node-RED: 27 Feb 06:20:56 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.54-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/6fd5e8038f8de8
node-red.0 | 2024-02-27 06:19:56.862 | info | Node-RED: 27 Feb 06:19:56 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.169-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/f82a95499c16cce1
node-red.0 | 2024-02-27 06:19:56.590 | info | Node-RED: 27 Feb 06:19:56 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.135-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/3d47429bbe4c46
node-red.0 | 2024-02-27 06:19:55.914 | info | Node-RED: 27 Feb 06:19:55 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.30-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/85cdc964ee40f8
node-red.0 | 2024-02-27 06:19:46.824 | info | Node-RED: 27 Feb 06:19:46 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.26-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/3d47429bbe4c46
node-red.0 | 2024-02-27 06:19:13.042 | info | Node-RED: 27 Feb 06:19:13 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.49-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/3d47429bbe4c46
node-red.0 | 2024-02-27 06:19:11.701 | info | Node-RED: 27 Feb 06:19:11 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.135-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/76b4fc984e3b74
node-red.0 | 2024-02-27 06:19:08.017 | info | Node-RED: 27 Feb 06:19:08 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.26-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/76b4fc984e3b74
node-red.0 | 2024-02-27 06:19:07.035 | info | Node-RED: 27 Feb 06:19:07 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.26-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/6fd5e8038f8de8
node-red.0 | 2024-02-27 06:19:04.731 | info | Node-RED: 27 Feb 06:19:04 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.54-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/85cdc964ee40f8
node-red.0 | 2024-02-27 06:19:02.736 | info | Node-RED: 27 Feb 06:19:02 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.135-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/85cdc964ee40f8
node-red.0 | 2024-02-27 06:19:00.147 | info | Node-RED: 27 Feb 06:19:00 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.27-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/85cdc964ee40f8
node-red.0 | 2024-02-27 06:18:53.272 | info | Node-RED: 27 Feb 06:18:53 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.30-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/eb79140d6cff28
node-red.0 | 2024-02-27 06:18:11.338 | info | Node-RED: 27 Feb 06:18:11 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.30-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/f82a95499c16cce1
node-red.0 | 2024-02-27 06:18:01.645 | info | Node-RED: 27 Feb 06:18:01 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.49-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/d5a046564eef28
node-red.0 | 2024-02-27 06:17:54.925 | info | Node-RED: 27 Feb 06:17:54 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.27-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/f82a95499c16cce1
node-red.0 | 2024-02-27 06:17:48.243 | info | Node-RED: 27 Feb 06:17:48 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.30-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/6fd5e8038f8de8
node-red.0 | 2024-02-27 06:17:40.375 | info | Node-RED: 27 Feb 06:17:40 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.26-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/eb79140d6cff28
node-red.0 | 2024-02-27 06:17:01.877 | info | Node-RED: 27 Feb 06:17:01 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.54-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/eb79140d6cff28
node-red.0 | 2024-02-27 06:16:49.896 | info | Node-RED: 27 Feb 06:16:49 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.30-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/3d47429bbe4c46
node-red.0 | 2024-02-27 06:16:33.443 | info | Node-RED: 27 Feb 06:16:33 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.135-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/6fd5e8038f8de8
node-red.0 | 2024-02-27 06:16:13.953 | info | Node-RED: 27 Feb 06:16:13 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.27-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/3d47429bbe4c46
node-red.0 | 2024-02-27 06:15:19.811 | info | Node-RED: 27 Feb 06:15:19 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.49-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/85cdc964ee40f8
node-red.0 | 2024-02-27 06:14:42.814 | info | Node-RED: 27 Feb 06:14:42 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.54-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/3d47429bbe4c46
node-red.0 | 2024-02-27 06:14:23.738 | info | Node-RED: 27 Feb 06:14:23 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.49-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/76b4fc984e3b74
node-red.0 | 2024-02-27 06:14:11.013 | info | Node-RED: 27 Feb 06:14:11 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.135-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/f82a95499c16cce1
node-red.0 | 2024-02-27 06:14:10.748 | info | Node-RED: 27 Feb 06:14:10 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.49-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/f82a95499c16cce1
node-red.0 | 2024-02-27 06:14:07.366 | info | Node-RED: 27 Feb 06:14:07 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.54-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/76b4fc984e3b74
node-red.0 | 2024-02-27 06:14:05.811 | info | Node-RED: 27 Feb 06:14:05 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.49-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/6fd5e8038f8de8
node-red.0 | 2024-02-27 06:14:00.755 | info | Node-RED: 27 Feb 06:14:00 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.49-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/eb79140d6cff28
node-red.0 | 2024-02-27 06:13:55.214 | info | Node-RED: 27 Feb 06:13:55 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.135-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/eb79140d6cff28
node-red.0 | 2024-02-27 06:13:39.714 | info | Node-RED: 27 Feb 06:13:39 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.26-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/f82a95499c16cce1
node-red.0 | 2024-02-27 06:13:35.910 | info | Node-RED: 27 Feb 06:13:35 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.26-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/85cdc964ee40f8
node-red.0 | 2024-02-27 06:13:20.318 | info | Node-RED: 27 Feb 06:13:20 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.27-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/eb79140d6cff28
node-red.0 | 2024-02-27 06:13:18.373 | info | Node-RED: 27 Feb 06:13:18 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.27-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/76b4fc984e3b74
node-red.0 | 2024-02-27 06:13:17.916 | info | Node-RED: 27 Feb 06:13:17 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.135-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/d5a046564eef28
node-red.0 | 2024-02-27 06:13:12.685 | info | Node-RED: 27 Feb 06:13:12 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.27-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/6fd5e8038f8de8
node-red.0 | 2024-02-27 06:12:26.714 | info | Node-RED: 27 Feb 06:12:26 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.30-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/d5a046564eef28
node-red.0 | 2024-02-27 06:12:20.060 | info | Node-RED: 27 Feb 06:12:20 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.54-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/f82a95499c16cce1
node-red.0 | 2024-02-27 06:12:15.395 | info | Node-RED: 27 Feb 06:12:15 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.161-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/f82a95499c16cce1
node-red.0 | 2024-02-27 06:12:05.934 | info | Node-RED: 27 Feb 06:12:05 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.27-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/d5a046564eef28
node-red.0 | 2024-02-27 06:12:05.051 | info | Node-RED: 27 Feb 06:12:05 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.26-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/d5a046564eef28
node-red.0 | 2024-02-27 06:11:10.354 | info | Node-RED: 27 Feb 06:11:10 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.30-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/76b4fc984e3b74
node-red.0 | 2024-02-27 06:11:00.262 | info | Node-RED: 27 Feb 06:11:00 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.54-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/6fd5e8038f8de8
node-red.0 | 2024-02-27 06:10:45.797 | info | Node-RED: 27 Feb 06:10:45 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.26-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/3d47429bbe4c46
node-red.0 | 2024-02-27 06:10:31.893 | info | Node-RED: 27 Feb 06:10:31 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.30-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/85cdc964ee40f8
node-red.0 | 2024-02-27 06:10:23.833 | info | Node-RED: 27 Feb 06:10:23 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.169-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/f82a95499c16cce1
node-red.0 | 2024-02-27 06:10:00.564 | info | Node-RED: 27 Feb 06:10:00 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.135-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/3d47429bbe4c46
node-red.0 | 2024-02-27 06:09:53.008 | info | Node-RED: 27 Feb 06:09:53 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.49-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/3d47429bbe4c46
node-red.0 | 2024-02-27 06:09:48.088 | info | Node-RED: 27 Feb 06:09:48 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.27-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/85cdc964ee40f8
node-red.0 | 2024-02-27 06:09:41.655 | info | Node-RED: 27 Feb 06:09:41 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.135-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/85cdc964ee40f8
node-red.0 | 2024-02-27 06:09:36.704 | info | Node-RED: 27 Feb 06:09:36 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.54-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/85cdc964ee40f8
node-red.0 | 2024-02-27 06:09:22.238 | info | Node-RED: 27 Feb 06:09:22 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.30-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/eb79140d6cff28
node-red.0 | 2024-02-27 06:09:14.676 | info | Node-RED: 27 Feb 06:09:14 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.135-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/76b4fc984e3b74
node-red.0 | 2024-02-27 06:09:12.986 | info | Node-RED: 27 Feb 06:09:12 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.26-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/76b4fc984e3b74
node-red.0 | 2024-02-27 06:09:12.010 | info | Node-RED: 27 Feb 06:09:12 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.26-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/6fd5e8038f8de8
node-red.0 | 2024-02-27 06:09:07.311 | info | Node-RED: 27 Feb 06:09:07 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.30-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/f82a95499c16cce1
node-red.0 | 2024-02-27 06:08:40.887 | info | Node-RED: 27 Feb 06:08:40 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.27-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/f82a95499c16cce1
node-red.0 | 2024-02-27 06:08:27.212 | info | Node-RED: 27 Feb 06:08:27 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.30-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/6fd5e8038f8de8
node-red.0 | 2024-02-27 06:08:10.355 | info | Node-RED: 27 Feb 06:08:10 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.26-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/eb79140d6cff28
node-red.0 | 2024-02-27 06:08:06.603 | info | Node-RED: 27 Feb 06:08:06 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.49-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/d5a046564eef28
node-red.0 | 2024-02-27 06:07:42.849 | info | Node-RED: 27 Feb 06:07:42 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.30-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/3d47429bbe4c46
node-red.0 | 2024-02-27 06:07:25.846 | info | Node-RED: 27 Feb 06:07:25 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.54-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/eb79140d6cff28
node-red.0 | 2024-02-27 06:07:21.381 | info | Node-RED: 27 Feb 06:07:21 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.135-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/6fd5e8038f8de8
node-red.0 | 2024-02-27 06:07:03.898 | info | Node-RED: 27 Feb 06:07:03 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.27-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/3d47429bbe4c46
node-red.0 | 2024-02-27 06:05:33.745 | info | Node-RED: 27 Feb 06:05:33 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.49-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/85cdc964ee40f8
node-red.0 | 2024-02-27 06:05:27.777 | info | Node-RED: 27 Feb 06:05:27 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.54-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/3d47429bbe4c46
node-red.0 | 2024-02-27 06:05:09.711 | info | Node-RED: 27 Feb 06:05:09 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.49-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/f82a95499c16cce1
node-red.0 | 2024-02-27 06:05:09.696 | info | Node-RED: 27 Feb 06:05:09 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.49-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/76b4fc984e3b74
node-red.0 | 2024-02-27 06:05:06.315 | info | Node-RED: 27 Feb 06:05:06 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.54-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/76b4fc984e3b74
node-red.0 | 2024-02-27 06:04:49.975 | info | Node-RED: 27 Feb 06:04:49 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.135-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/f82a95499c16cce1
node-red.0 | 2024-02-27 06:04:25.749 | info | Node-RED: 27 Feb 06:04:25 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.49-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/6fd5e8038f8de8
node-red.0 | 2024-02-27 06:04:22.684 | info | Node-RED: 27 Feb 06:04:22 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.26-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/f82a95499c16cce1
node-red.0 | 2024-02-27 06:04:19.721 | info | Node-RED: 27 Feb 06:04:19 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.49-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/eb79140d6cff28
node-red.0 | 2024-02-27 06:04:17.823 | info | Node-RED: 27 Feb 06:04:17 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.135-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/d5a046564eef28
node-red.0 | 2024-02-27 06:04:16.744 | info | Node-RED: 27 Feb 06:04:16 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.135-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/eb79140d6cff28
node-red.0 | 2024-02-27 06:04:06.728 | info | Node-RED: 27 Feb 06:04:06 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.26-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/85cdc964ee40f8
node-red.0 | 2024-02-27 06:04:00.659 | info | Node-RED: 27 Feb 06:04:00 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.27-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/6fd5e8038f8de8
node-red.0 | 2024-02-27 06:03:39.328 | info | Node-RED: 27 Feb 06:03:39 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.27-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/76b4fc984e3b74
node-red.0 | 2024-02-27 06:03:31.279 | info | Node-RED: 27 Feb 06:03:31 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.27-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/eb79140d6cff28
node-red.0 | 2024-02-27 06:03:04.373 | info | Node-RED: 27 Feb 06:03:04 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.161-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/f82a95499c16cce1
node-red.0 | 2024-02-27 06:03:04.034 | info | Node-RED: 27 Feb 06:03:04 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.54-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/f82a95499c16cce1
node-red.0 | 2024-02-27 06:02:59.683 | info | Node-RED: 27 Feb 06:02:59 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.30-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/d5a046564eef28
node-red.0 | 2024-02-27 06:02:38.025 | info | Node-RED: 27 Feb 06:02:38 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.26-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/d5a046564eef28
node-red.0 | 2024-02-27 06:02:16.902 | info | Node-RED: 27 Feb 06:02:16 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.27-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/d5a046564eef28
node-red.0 | 2024-02-27 06:01:42.236 | info | Node-RED: 27 Feb 06:01:42 - [info] [alexa-home-controller:Alexa Controller] Request data: 192.168.178.54-80/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/6fd5e8038f8de8

</body>
</html>

Kann man das abschalten ?

Gruß aus Kiel

Matze`

**Comment by Apollon77** [comment]
related to #444?

**Comment by Apollon77** [comment]
yes, duplicate
