### ISSUE TITLE
Erweiterung: ioBroker Input Startup Verhalten

### ISSUE THREAD

**Issue by Marty56** [ioBroker/ioBroker.node-red#45]
Es wäre schön, wenn man das Verhalten des ioBroker Input node beim Startup definieren könnte. 
Entweder er macht nichts, oder er sendet seinen aktuellen Wert.

Use Case: Schnelles Refresh der Werte im Dashboard nach node red deployment oder Neustart.
Zur Zeit muss sich das Display immer darauf warten, dass sich der ioBroker state updatet.

**Comment by mobilutz** [comment]
Duplicate of #37
