### ISSUE TITLE
v5.20 - Error loading context store

### ISSUE THREAD

**Issue by Bernd9000** [ioBroker/ioBroker.node-red#455]
node-red V5.20

Nach Stromausfall erhalte ich folgende Fehlermeldung und node-red startet nicht mehr:

Was ist zu tun ?

iob Log:
Node-RED: 11 Mar 12:15:45 - [error] Error: Error loading context store: Error: Invalid JSON in context file 'C:\Software\iobroker\iobroker-data\node-red\context\58249c2.4f53464old\27534191197f4dc9.json' at C:\Software\iobroker\node_modules\@node-red\runtime\lib\nodes\context\index.js:180:15 

Node-RED: 11 Mar 12:15:45 - [error] Failed to start server:

**Comment by klein0r** [comment]
Zeig doch mal den Inhalt der Datei

**Comment by Bernd9000** [comment]
Habe  es erstmal zum laufen gebracht mit node-red v5.10....... Glück ghabt :-)

Der inhalt aller Datei ist leer bzw. es sind nur paar Leerzeichen vorhanden.
Vermutlich durch den Stromausfall.
Es müßte dann aber eine Möglichkeit geben das zu umgehen ?

**Comment by klein0r** [comment]
> Es müßte dann aber eine Möglichkeit geben das zu umgehen ?

Bestimmt, ist ein Thema von Node-RED nur gültiges JSON da rein zu schreiben oder zumindest fehlertolerant zu parsen. Dazu gibt es hier auch schon einen Issue: https://github.com/node-red/node-red/issues/2723

Hat mit dem Adapter hier ja erstmal nix zu tun.

**Comment by Bernd9000** [comment]
Ich ging aber davon aus, weil das gerade in der v5.20 aktuell war ?

![Unbenannt](https://github.com/ioBroker/ioBroker.node-red/assets/77005685/40f2c147-c412-4a9f-ab47-76c8e5fb1636)

**Comment by klein0r** [comment]
Na da wurde der persistent storage ja nur aktiviert - war ein Wunsch hier in den Issues.
Welches Vorgehen wünschst Du Dir jetzt?

**Comment by Bernd9000** [comment]
Es wäre nicht schlecht bei einem Fehler das laden der context Daten zu verhindern.
Also eine Option in den Adapter-Einstellung in node-red.

**Comment by klein0r** [comment]
> Es wäre nicht schlecht bei einem Fehler das laden der context Daten zu verhindern.

Ja, das muss Node-RED anpassen. Der Adapter startet ja nur den Node-RED Prozess.

**Comment by Bernd9000** [comment]
Für alle die das selbe Problem haben.
Adapter node-red stopen
Im der Datei "node_modules\iobroker.node-red\settings.js" folgende Zeilen ausklammern.
Und node-red wieder starten
Kann es selbst aber aktuell nicht mehr testen.



contextStorage: {
            default: {
                module: "localfilesystem",
                config: {
                    dir: "'%%contextDir%%'"
                }
            }
        },
