### ISSUE TITLE
Support Projects

### ISSUE THREAD

**Issue by bee-eater** [ioBroker/ioBroker.node-red#46]
The projects feature cant be enabled manually I think, because the settings.js file is regenerated if the node-red server is restarted. You could probably just add it as configuration option in the ioBroker instance?

Is there any workaround currently?

**Comment by bee-eater** [comment]
https://nodered.org/docs/user-guide/projects/

editorTheme: {
       projects: {
           enabled: true
       }
   },

**Comment by arozhankov** [comment]
+1 problem

/home/user/.node-red/settings.js - not work

**Comment by nobodyMO** [comment]
/home/user/.node-red looks like a stand alone installation of node-red. The settings.js used by the iobroker.node-red adapter is in a different directory. 
The template is in the adapter install directory (e.g. /opt/iobroker/node_modules/iobroker.node-red). The generated version of settings.js is in the working-directory of iobroker (e.g. /opt/iobroker/iobroker-data/node-red)

**Comment by Apollon77** [comment]
Please check 0.12.0 from GitHub. it is node-red 1.0 together with projects feature

**Comment by bjoernbusch** [comment]
Works like a charm. Projects can be enabled in the settings and then it just works. I think the issue can be closed?
