### ISSUE TITLE
Adapter als root ausführen möglich?

### ISSUE THREAD

**Issue by umbm** [ioBroker/ioBroker.node-red#47]
Gibt es eine Möglichkeit, den node-red-Adapter unter ioBroker als root zu starten?

Hintergrund ist der "node-red-contrib-amazon-echo"-Node, der für die Gen3 zwingend auf Port 80 lauschen muss, den er nur als root öffnen kann.
siehe:
https://flows.nodered.org/node/node-red-contrib-amazon-echo

**Comment by goyertp** [comment]
Gleiche Thematik hier. Der derzeit verwendete Node node-red-contrib-alexa-local funktioniert leider nicht mehr. Amazon hat offensichtlich zentral was geändert. 

Der Author verweist auf sein neues Projekt:

https://flows.nodered.org/node/node-red-contrib-amazon-echo

Nur dieses funktioniert noch.

**Comment by Apollon77** [comment]
Wie ist iobroker denn installiert? Der neue installer bzw Installation Fixer sollte für den nodejs Prozess automatisch per „setcap“ die nötigen Rechte geben um privilegierte ports zu öffnen. 

Bitte mal Installation Fixer probieren. Geht es danach vllt direkt?

**Comment by goyertp** [comment]
Meine Installation ist von 2017 und seit dem fleißig alle Updates ( Cents, iobroker, Module und nodes) durchgezogen.

Vielleicht ist es mal an der Zeit eine Neuinstallation zu starten ;)

**Comment by thePhilipp** [comment]
selbe Frage von mir. Wie gebe ich Node Red root Rechte? Hab gestern den amazon-echo node installiert und der Amazon Hub Knoten konnte sich nicht mit Port 80 verbinden.
@Apollon77 was ist der "installation Fixer"?

Gruß

**Comment by Apollon77** [comment]
Na dann seid Ihr beide recht outdated ... es hat sich viel getan, vor allem in Bezug auf "Sicherheit"

Siehe https://forum.iobroker.net/topic/20211/iobroker-installation-fixer-beta-verf%C3%BCgbar

Mal unabhängig davon ob Ihr Eure Installationen aktualisiert (muss keine neuinstallation sein!) könntet Ihr versuchen das auszuführen:

```
setcap 'cap_net_admin,cap_net_bind_service,cap_net_raw+eip' $(eval readlink -f `which node`)
```

**Comment by thePhilipp** [comment]
Hmm, meine ioBroker Installation ist gerade mal 2 Monate alt. Aber ich werde den Fixer trotzdem mal durchlaufen lassen. Eventuell hab ich ja was falsch gemacht bei der Installation.

**Comment by Apollon77** [comment]
Danach mal nodejs aktualisiert. Ich hatte schonmal den Fall das dadurch die Sonderrechte von "setcap" wieder verschwunden sind

**Comment by thePhilipp** [comment]
Geilo, Fixer durch laufen lassen und schon war der HUB online :)
Danke

noch ne Frage auch wenn ein wenig off topic, aber ich muss das mal ausnutzen das hier deutsch geschrieben wird :)
bevor ich den amazon-echo node installiert habe, habe ich den alexa-local node deinstalliert. Hierfür habe ich in allen flows alle alexa nodes gelöscht. Also alle Hue-Emus sollten jetzt weg sein. Danach bin ich auf die Alexa Website und habe alle Smarthomegeräte gelöscht.
Danach habe ich Alexa neue Geräte suchen lassen und zu meinem Erstaunen hat sie alle Geräte wieder gefunden obwohl ja keine mehr da waren. Hab das ganze zwei drei mal wiederholt. Sie hat die  in Node Red gelöschten Geräte immer wieder gefunden. Habe es heute noch einmal probiert. Nun findet sie nicht mehr alle Geräte aber zumindest noch ein paar. WO findet sie die? Kann mir das einer erklären? Würde das gerne sauber haben bevor ich jetzt mit dem neuen alexa-echo node neue Geräte anlege.

Gruß

**Comment by goyertp** [comment]
Das Problem hatte ich tatsächlich auch. Ich bin dann hingegangen und habe die node Alexa-local gelöscht, iobroker neu gestartet und dann hatte ich das Problem nicht mehr.

Mit dem Befehl 

netstat -tulpen

Kannst du prüfen ob der local Port 1900 tcp offen ist. Alexa-local sollte diesen nicht mehr anbieten und deshalb sollte er dann weg sein.

**Comment by thePhilipp** [comment]
Neustart etc hatte ich natürlich durch nach dem ich den alexa.local node gelöscht hatte. Seit gestern Abend ist jetzt aber alles sauber bei mir. Kann nur leider nicht genau sagen wieso. 
Hab ja nachmittags den Fixer laufen lassen, nodejs und npm aktuallisiert. Dann später habe ich alle Geräte einzeln in der Alexa App gelöscht und habe sie neu suchen lassen. Und siehe da, nur noch die neuen Geräte von dem neuen alexa_echo node drin.
Also Problem gelöst! :)
