### ISSUE TITLE
Node-red unaccessible and httpundefined running in docker

### ISSUE THREAD

**Issue by Ludacrysis** [ioBroker/ioBroker.node-red#470]
Hi,

I just got ioBroker running in docker and ran into some issues with Node-Red.

First off: The Link on the Main page is broken. It reports httpundefined.

![image](https://github.com/ioBroker/ioBroker.node-red/assets/68922221/e16f57ba-4d21-4d38-85df-d9f1458d2ac5)

Although the adapter starts without an issue and reports it's running on port 1880 (standard-config) there's no way to access it.

![image](https://github.com/ioBroker/ioBroker.node-red/assets/68922221/21826092-b1cb-4b7e-9b49-32a953eae298)
Sorry log is in german...

I'm running iobroker in host-network-mode to avoid port-publications and issues with enclosed networks. 
I might change that later but for now that won't be an issue. (still testing-environment)

Sadly when connecting to %ip%:1880 the connection get's refused, although standard config states all connections are to be accepted.

All adapters are up-to-date and freshly installed.

I've been using Node-red for some time now and it runs smooth in my live environment that's why I assume some issues with docker sadly I'm new to docker.

**Comment by Apollon77** [comment]
But you know that when running in docker that you manually need to map all the ports used to external ports? SO please adjust your Docker configuration to map Port 1880 additionally to the posrts automatically mapped from admin and such

**Comment by Ludacrysis** [comment]
Yeah I know that. I also mapped that port in order to access it, but this didn't resolve the issue.

Furthermore I tried running it in host-network-mode which should eliminate the need to configure each port separately (correct me if I'm wrong) but this didn't help either.

**Comment by Apollon77** [comment]
Hm ... no idea ... 127.0.0.1 sounds like he just binds on localhost ... no idea if you somehow need to tweak the config of node-red to be forwarded? This is maybe better a topic for the forum because I can not imagine that noone else have it running in docker
