### ISSUE TITLE
error after node-red update to v5.2.0 and node-red isn't starting

### ISSUE THREAD

**Issue by paulchen007** [ioBroker/ioBroker.node-red#471]
after i updated (from v5.1.0 to v5.2.0) my node-red, i get the following error and node-red is not starting:
Node-RED: 27 Apr 08:23:31 - [error] Error: bind EACCES 0.0.0.0:67 at node:dgram:362:20 at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
has anyone an idea?
i tried to downgrade to v5.1.0, with the same result (error).
help...

**Comment by Apollon77** [comment]
try "iob fix"

**Comment by paulchen007** [comment]
ups. that was easy. 
thank you!!!
