### ISSUE TITLE
Tibber API Connection mit node-Red: User agent bisand/tibber-api/5.1.9 is blocked

### ISSUE THREAD

**Issue by CBRocker** [ioBroker/ioBroker.node-red#475]
Hallo,
ich rufe schon lange die API-Daten von Tibber per node-red ab (Anleitung aus ioBroker Forum).
Kürlich habe ich den Adapter aktualisiert.

Nun seit ein paar Stunden bekomme ich diesen Fehler:
Node-RED: 4 Jun 15:22:10 - [error] [tibber-feed:Tibber Livedaten holen] An error ocurred while trying to check if real time consumption is enabled.{"responseMessage":"User agent bisand/tibber-api/5.1.9 is blocked. Please downgrade to the previous version or upgrade to a later version that works properly","httpCode":400,"statusCode":400,"statusMessage":"Bad Request"}

Habe nun mal auf 5.1.0 downgegradet, ohne Erfolg.

Im Adapter Tibber Link kommen die Daten an, also an der API kann es nicht liegen.

hat jemand einen Tipp?

**Comment by Eulili** [comment]
Same here!

**Comment by Eulili** [comment]
Update of the "node-red-contrib-tibber-api" to V 6.0.4 in node-red works fine!

**Comment by CBRocker** [comment]
wo gibts die V6.0.4. Mit Beta finde ich auch nur die 5.2.1

**Comment by CBRocker** [comment]
klappt, danke für die Info.
