### ISSUE TITLE
Erweiterung "Auslösebedingungen" für iobroker Input-Node

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.node-red#5]
Aktuell wird bei jeder Datenaktualisierung die Nachricht einer Input-Node ausgelöst.

Praktischer (vor allem auch wenn man vllt die Strategie hätte das node-red der "Nachfolger" der ScriptGUI sein könnte und damit mehr auf "Standards basiert) wäre es noch weitere Auslösebedingungen zu unterstützen. Mindestens mal "auf Änderung" (also nur wenn sich der Wert geändert hat) oder vllt sogar alle sinnvollen aus ScriptGUI (Equal, Non-Equal, Grßer, Kleiner Größer-gleich, Kleiner-gleich und so) ...

**Comment by Apollon77** [comment]
Auf der einen Seite wäre es cool das direkt als "Auslösebedingung" zu haben ... aber vllt fixt sich das indirekt mit node-red 0.13 in ein paar Tagen. In dem Zuge wird die Switch-Node die Möglichkeit bekommen den "previous value" zu referenzieren. Das heisst das man im einfach eine Switch_node nutzen kann ... von daher wäre dann 0.13 interessant um dieses "Feature-Loch" zu schliessen (und macht auch Sinn weil Input ist halt Inupt ohne weitere Logik)

**Comment by GermanBluefox** [comment]
Danke, wo kann man darüber nachlesen?

2016-01-15 14:08 GMT+01:00 Ingo Fischer <notifications@github.com>:

**Comment by Apollon77** [comment]
Ich kam auf die Idee das man vllt die RBE Node erweitern könnte und hab da mal einen Feature Request gemacht ...
https://github.com/node-red/node-red-nodes/issues/167

Am Ende ... https://github.com/node-red/node-red/commit/81f082825dbe25f875b46c615312c97b03051ed0

**Comment by GermanBluefox** [comment]
Fixed?
![image](https://user-images.githubusercontent.com/4582016/157119546-32a8c56b-a007-4e9f-92b1-ba606b45daac.png)

**Comment by Apollon77** [comment]
Released in 3.0.0
