### ISSUE TITLE
about node-red ui in iobroker proxy

### ISSUE THREAD

**Issue by gokturk413** [ioBroker/ioBroker.node-red#503]
I use node-red in proxy.Node-red admin interface perfect works but node-red ui (dashboard) does not load interface which i use  iobroker proxy

**Comment by gokturk413** [comment]
my node-red version 5.2.1

**Comment by gokturk413** [comment]
my proxy adapter version is 1.3.2

**Comment by GermanBluefox** [comment]
> my proxy adapter version is 1.3.2

proxy does not support socket connections. node-red uses WS socket to communicate with backend
