### ISSUE TITLE
Node-Red crashes after importing flows from external Node-Red

### ISSUE THREAD

**Issue by MeisterQ** [ioBroker/ioBroker.node-red#504]
Hi,

im running an extra Node-Red since afew years before start using iobroker. Now i wanted to import it into the node-red iobroker, but if i import all flows, do all the configurations etc and it can deploy without any warnings, it will crash and stay in a boot-loop.

i then can see this log

![grafik](https://github.com/user-attachments/assets/f16faa88-2e75-41b3-81f8-4603aa325351)

Someone has an idea how to fix it?

**Comment by Apollon77** [comment]
This is an Out Of Memory issue ... so check your free RAM on your machine (free -m) or maybe disable all flows and try to find which one is causing it

**Comment by MeisterQ** [comment]
> This is an Out Of Memory issue ... so check your free RAM on your machine (free -m) or maybe disable all flows and try to find which one is causing it

Thank you... Giving the adapter more RAM helped.. Thank you
