### ISSUE TITLE
Daten im Localfilesystem speichern

### ISSUE THREAD

**Issue by frankyboy1973** [ioBroker/ioBroker.node-red#51]
Hi, in der Original settings.js von Node Red gibt es die Möglichkeit, von Storage in memory auf Storage in Localfilesystem zu wechseln. Das habe ich in der settings unter IobrokerData/Node Red nicht gefunden. Gibt es die Möglichkeit das irgendwie anders einzustellen, oder ist das bei Node Red als Iobroker Instanz nicht möglich? Es geht darum Daten bei einem Adapter Neustart nicht zu verlieren. Wie zum Beispiel Dashboard Werte oder eingestellte Werte von bestimmten Nodes.

**Comment by petterpet** [comment]
Schau mal hier: #42
