### ISSUE TITLE
zusätzliche Module für Node Red?

### ISSUE THREAD

**Issue by thatso** [ioBroker/ioBroker.node-red#52]
Mit Referenz zu [diesem](https://github.com/ioBroker/ioBroker/issues/124) Ticket:

Ich habe ioBroker unter Raspian Stretch Lite nach [dieser Anleitung](http://www.iobroker.net/docu/?page_id=8323&lang=de) aufgesetzt und den Node Red Adapter installiert.
Obwohl [hier](http://www.iobroker.net/docu/?page_id=4284&lang=de) erklärt wird, weitere Module manuell zu ergänzen, habe ich inzwischen herausgefunden, daß stattdessen diese auf der Konfigurationsseite eingetragen werden sollen und auch nicht innerhalb der Node Red Palette installiert werden dürfen.
Die eingetragenen Module tauchen zwar im Verzeichnis
`/opt/iobroker/node_modules/iobroker.node-red/node_modules`
auf, allerdings nicht innerhalb Node Red selbst.
Neustarts des Adapters bzw. des kompletten OS haben daran nichts geändert.

**Comment by thatso** [comment]
Seltsam, daß für ein derart elementares Problem keine Antwort kommt.
Langes Suchen im Internet brachte mich ebenfalls nicht weiter - außer der Erkenntnis, daß dieses Problem wohl öfter auftritt.
Ich habe zum Vergleich nochmal eine komplett neue ioBroker Installation in einer VM mit Debian Stretch durchgeführt. Das Ergebnis ist reproduzierbar identisch: zusätzliche Module sind nur verfügbar, wenn sie direkt innerhalb Node Red über die Palette installiert werden.

**Comment by GermanBluefox** [comment]
Es liegt an der neuen NPM Version und wir hatten noch keine Zeit das anzupassen

**Comment by Coffee-lover** [comment]
Hi!
Ich habe iobroker wie auch node-red in einem Container auf meinem NAS installiert. Leider fehlt in node-red das vom Raspberry bekannte Modul "iobroker". Über die Palette finde ich es nicht. Wie heißt das zugehörige NPM Packet, damit ich es direkt im iobroker Adapter ergänzen kann?
Vg

**Comment by Apollon77** [comment]
Hast Du ein getrenntes node-red oder das vom Adapter?

**Comment by Coffee-lover** [comment]
Ein getrenntes...

**Comment by thatso** [comment]
@Coffee-lover: was soll dieses Issue Hijacking? Dein Problem hat nichts mit meiner Frage zu tun.

**Comment by nobodyMO** [comment]
Hi, 
das Installationsverzeichnis von Nodes unterhalb von Node-Red wurde geändert. Dies liegt nicht am RPM, sondern an der nun in Node-Red integrierten Verwaltung der Palette. 
Neue Nodes müssen nun relativ zum Verzeichnis der Flow-Datei installiert werden. Dies ist bei mir 
`
/opt/iobroker/iobroker-data/node-red
`
in diesem Verzeichnis das npm zum Installieren der nodes ausführen. 
In das node_modules -Verzeichnis darunter werden dann die Nodes installiert und nach dem Neustart des Node-Red-Adapters auch angezeigt.

**Comment by nobodyMO** [comment]
@Coffee-lover:
Es gibt hierfür kein eigenes NPM-Paket und es würde so auch nicht funktionieren, da der Node über die utils.js das lokale Installationsverzeichnis des Controllers ermittelt. Wenn der Controller nicht auf dem gleichen System installiert ist, funktioniert der node-red-Node nicht.

**Comment by thatso** [comment]
@nobodyMO: bei mir landen innerhalb der Node Red Palette installierte Module ebenfalls in
`/opt/iobroker/iobroker-data/node-red/node_modules/`
Heißt das nun, daß man derzeit diesen Weg beschreiten kann/darf oder wird sich diese Art der Installation künftig negativ auswirken? Die Doku ist ja wie eingangs erwähnt ziemlich konfus diesbezüglich.

**Comment by nobodyMO** [comment]
Was unter 
'/opt/iobroker/node_modules/iobroker.node-red/node_modules/' 
manuell installiert wird, wird normalerweise beim nächsten Update des node-red-Adapters automatisch geputzt. Deswegen gibt es den Weg über die Adapter-Einstellungen, da die dort eingetragenen Module automatisch wieder neu installiert werden. 
Unter /opt/iobroker/iobroker-data/node-red sollte aber nichts automatisch gelöscht werden. (Bis auf die settings.js, die bei jedem Adapter-Neustart mit der generierten Datei überschrieben wird).

**Comment by GermanBluefox** [comment]
Besteht das Problem immer noch??

**Comment by thatso** [comment]
Ich sehe gerade, daß ich immer noch bei 1.13 bin. Warum eigentlich? Wurden die zwischenzeitlichen Updates bis 1.15 nicht freigegeben?
Jedenfalls habe ich alle Module über die Palette installiert und mangels verfügbaren Updates bisher auch nichts daran geändert.

**Comment by GermanBluefox** [comment]
Please reopen if still exists

**Comment by jakolion** [comment]
Hi,

ich bin mit ioBroker-Adaptern auf dem "latest"-Repository unterwegs und habe nun Node-RED-Adapter Version 2.0.0 installiert. Mit dieser Version ist die Palette innerhalb von Node-RED entfernt worden, weil die zusätzlichen Module über die Adapter-Konfiguration eingespielt werden sollen.

> (bluefox) Hide the palette manager so all the packets must be installed via ioBroker configuration dialog

Also versuche ich nun das benötigte _node-red-node-wol_ für Node-RED über die Konfiguration hinzuzufügen, was mir aber nicht gelingen will. Nach dem Speichern der Konfiguration und dem Neustarten des Node-RED-Adapters erscheint das Modul nicht in der Liste der Nodes. Installiert wurden das Modul und dessen Abhängigkeiten nach

> /opt/iobroker/node_modules/iobroker.node-red/node_modules

Der folgende Ordner

> /opt/iobroker/iobroker-data/node-red/node_modules

ist leer.

Wenn ich nun den Inhalt von  _.../node_modules/iobroker.node-red/node_modules_ nach _.../iobroker-data/node-red/node_modules_ kopiere und den Adapter neustarte, erscheint das WOL-Modul und ich kann es erfolgreich nutzen.

Wird hier eventuell etwas in einen falschen Ordner installiert?

**Comment by cru8602** [comment]
> Hi,
> 
> ich bin mit ioBroker-Adaptern auf dem "latest"-Repository unterwegs und habe nun Node-RED-Adapter Version 2.0.0 installiert. Mit dieser Version ist die Palette innerhalb von Node-RED entfernt worden, weil die zusätzlichen Module über die Adapter-Konfiguration eingespielt werden sollen.
> 
> > (bluefox) Hide the palette manager so all the packets must be installed via ioBroker configuration dialog
> 
> Also versuche ich nun das benötigte _node-red-node-wol_ für Node-RED über die Konfiguration hinzuzufügen, was mir aber nicht gelingen will. Nach dem Speichern der Konfiguration und dem Neustarten des Node-RED-Adapters erscheint das Modul nicht in der Liste der Nodes. Installiert wurden das Modul und dessen Abhängigkeiten nach
> 
> > /opt/iobroker/node_modules/iobroker.node-red/node_modules
> 
> Der folgende Ordner
> 
> > /opt/iobroker/iobroker-data/node-red/node_modules
> 
> ist leer.
> 
> Wenn ich nun den Inhalt von ".../node_modules/iobroker.node-red/node_modules" nach ".../iobroker-data/node-red/node_modules" kopiere und den Adapter neustarte, erscheint das WOL-Modul und ich kann es erfolgreich nutzen.
> 
> Dieser Fehler ist aus meiner Sicht noch existent und noch nicht behoben.
> 
> Werden die Node-RED Module eventuell in einen falschen Ordner installiert?

Bei mir ist's das gleiche. Das Paket wird in den erstgenannten Ordner kopiert. Nachdem ich es nun in den zweitgenannten kopiert habe wird es mir zumindest in NR angezeigt, weil ich aber wahrscheinlich irgendwelche Abhängigkeiten nicht mit erwischt habe funktioniert es nicht richtig... (...-contrib-fritz in meinen Fall).
Da können nur jetzt nochmal zwei Fragen auf: wie Update ich jetzt eigentlich Module über die iobroker config and write deinstalliere ich die wieder? Das Entfernen des Paketnamens hatte bei einem Neustart zumindest im Log keine Auswirkungen. 🤷🏻‍♂️

**Comment by kailausberg** [comment]
Habe das gleiche Problem gehabt mit dem Node-Red Adapter v2.01.  Nur das manuelle Kopieren des Orderinhalts 
von  `/opt/iobroker/node_modules/iobroker.node-red/node_modules`
nach `/opt/iobroker/iobroker-data/node-red/node_modules`
hat dazu geführt, dass iobroker das neue Node gefunden hat (in meinem Fall das mysql Node) und verfügbar ist.

Seit dem Update des Adapters auf die 2.0 (und Umstellung auf https) funktioniert übrigens der Link links auf der iobroker Startseite nicht mehr > 
https://xxx.xxx.xxx.xxx:8081/#tab-node-red-0
Der Node-Red Adapterlink selbst ruft die Seite aber erfolgreich auf > http://xxx.xxx.xxx.xxx:1880 


PS: @cru8602 :  Soweit ich weiß funktionieren die Nodes mit dem Namenszusatz `-contrib-` nicht mit der Node-Red Dashboard Version, sondern nur mit der alten.

**Comment by Tobi-BPi** [comment]
HI! 
kurzes Statement:
-IOBROKER BUSTER IMAGE komplett neu und up to date 
-Admin 4.0.10
- node / nodejs 10.23.0
-npm 6.14.8
-Test mit NODE-RED aus IOBROKER 1.17.2 - keine Nodes nach der Modul Installation
-Test mit NODE-RED aus GitHub 2.0.1 - keine Nodes nach der Modul Installation

Erst nach manueller Kopie der Module 
von /opt/iobroker/node_modules/iobroker.node-red/node_modules
nach /opt/iobroker/iobroker-data/node-red/node_modules
wurden die Nodes aktuallisiert. 

Kurz um, fehler besteht immer noch.
Danke an die Dev's und bleibt GESUND
Tobi

**Comment by GottZ** [comment]
node 10?

kannst eigentlich schon safe auf node 12 wechseln.

OP Problem +1
