### ISSUE TITLE
email-node hat probleme

### ISSUE THREAD

**Issue by liv-in-sky** [ioBroker/ioBroker.node-red#55]
hallo,
ich habe iobroker auf einen neuen stand gebracht -  Node 10.15.3 - NPM 6.4.1 - Js-cont. 1.5.7 -

seitdem hat die node-red-email node ein problem

![Image 3](https://user-images.githubusercontent.com/18462890/56306318-6ca50280-6142-11e9-8a1b-3b66ddff1d2e.png)
 

kennt man den fehler schon - vielleicht habe ich zuviel upgedatet ?

**Comment by Apollon77** [comment]
vllt node-red-email nochmal neu installieren? Gibt es da vllt eine neuere Version?

**Comment by liv-in-sky** [comment]
hallo ingo,

es scheint eine neue version zu geben 1.4.0 ich habe 1.29. wie genau installiert man diese node neu - bin da immer etwas vorsichtig, da diese node eine standard node ist und diese wiederum von iobroker installiert wird. unter manage palettes wird ein update angeboten, aber dieses ist nicht aufrufbar. ich nehme an das geht über die console - wenn ja, in welchen verzeichnis müßte ich das ausführen

**Comment by libertyx82** [comment]
Das Modul lässt sich leider nicht Updaten

https://github.com/ioBroker/ioBroker.node-red/issues/41

**Comment by GermanBluefox** [comment]
Gibt es noch das Problem? Bitte NIE packet Manager von node-red benutzen, sondern nur über die ConfigurationsDialog im ioBroker die Pakete definieren.
