### ISSUE TITLE
ioBroker node on a separate NodeRed System

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.node-red#56]
Is it possible to install the ioBroker input/output nodes on another NodeRed installation which is not managed by ioBroker? Can you provide a separate package via npm for that usecase?

**Comment by Apollon77** [comment]
This is not that easy because the whole Database connection client and handling logic also would be needed to "cut out" of js-controller ... so at least a challenge and needs time to figure it out
Easies would be to install a iobroker slave system and only have node-red running there as adapter

**Comment by klein0r** [comment]
Okay in that case a connection via MQTT would be the easiest way (instead of having an additional ioBroker instance). Thanks for your quick response
