### ISSUE TITLE
Warnungen im LOG

### ISSUE THREAD

**Issue by ihavenonick** [ioBroker/ioBroker.node-red#57]
Was sind das für Warnungen?
`node-red.0    2019-06-08 10:47:29.008    warn    8 Jun 10:47:29 - [warn] Projekte inaktiviert: setze editorTheme.projects.enabled=true zum Aktivieren
node-red.0    2019-06-08 10:47:28.321    warn    8 Jun 10:47:28 - [warn] rpi-gpio : Pi RPi.GPIO-Python-Bibliothek nicht gefunden
node-red.0    2019-06-08 10:47:28.319    warn    8 Jun 10:47:28 - [warn] rpi-gpio : Raspberry Pi-spezifischer Knotenset inaktiv `

Scheint was Raspi spezifisches zu sein, da bei mir das ganze unter Debian 10 auf einem Beelink läuft. Hat keine ersichtlichen Auswirkungen, ist allerdings verwirrend und unschön.

**Comment by GermanBluefox** [comment]
Wenn node-red auf RasPi gestartet wird, dann versucht node-red die Knoten für GPIO automatisch zu laden, findet aber kein rpi-gpio packet.

**Comment by ihavenonick** [comment]
Ja das sind ja auch genau die Erkenntnisse die ich habe. Die eigentliche Frage dazu ist aber macht das was, muss ich was nachinstallieren, wird das angepasst, oder kann man das einfach ignorieren?
