### ISSUE TITLE
split authentication in admin and dashboard username/password

### ISSUE THREAD

**Issue by fennsen64** [ioBroker/ioBroker.node-red#58]
in the node-red admin-page in iobroker, only the general option to secure the whole UI environment is possible.

To distribute a specific dashboard for guests, a authentication spilitting of the node-red admin page and the dashboard-ui will be necessary (adminAuth and httpNodeAuth)
See: https://nodered.org/docs/security
or
http://www.steves-internet-guide.com/securing-node-red-ssl/

**Comment by fennsen64** [comment]
Hmmm.. I tried to adjust this manually in the settings.js file.
Something doesn't work like expected:

    // You can protect the user interface with a userid and password by using the following property.
    // The password must be an md5 hash  eg.. 5f4dcc3b5aa765d61d8327deb882cf99 ('password')

**originaler Eintrag: Variable aus ioBroker node-red settings page; wird aus dem template in die finale settings.js ersetzt.**
    httpAdminAuth: '%%auth%%',
**Test: nutze die Variable fuer die /ui/ Seite (Gastzugang etc) unten in httpNodeAuth und setze hier eine manuelle Authorisierung (MD5 Hash Code online erzeugt)
-> das funktioniert nicht wenn man das mit httpNodeAuth tauscht (siehe unten bei httpNodeAuth)**
//      httpAdminAuth:  {"user":"admin","pass":"irgendeinMD5hascode"},

    // To password protect the node-defined HTTP endpoints, the following property
    // can be used.
    // The password must be an md5 hash  eg.. 5f4dcc3b5aa765d61d8327deb882cf99 ('password')
    //httpNodeAuth: {user:"user",pass:"5f4dcc3b5aa765d61d8327deb882cf99"},
//
**das funktioniert irgendwie generell nicht wenn man das httpNodeAuth zusaetzlich zum httpAdminAuth setzt, bzw. die Variable aus iobroker admin-page hierhin tauscht.
Beim Aufruf der Dashboard-Seite wird zwar separat User und Kennwort abgefragt, aber weder die in AdminAuth, noch in NodeAuth gesetzte Kombination funktioniert.
Das AdminAuth password funktioniert hingegen auf der Editor-Page, aber selbst da eingeloggt funktiniert die Password-Abfrage auf der Dashboard-Seite nicht**
**// Test: flip variable to here**
//    httpNodeAuth: '%%auth%%',

**Comment by jwiesel** [comment]
See also #98

**Comment by jwiesel** [comment]
Hi @fennsen64,
I updated the authentication settings according to the Node-Red Security Guide in #99.
With that your Node-Red editor (flow administration) will be password protected while the dashboard ( url with /ui/) will be open for everyone. Is that what you are looking for?
You can try it out by going to ioBroker administration on tab "Adapters" click on the Github icon in the top-navigation > install custom > url: https://github.com/jwiesel/ioBroker.node-red/tarball/master 
Note: The idea is to integrate the functionality into a new version of the ioBroker.node-red adapter. Until this is done you can test using the installation above, if you want. ;-)

**Comment by jwiesel** [comment]
Hi @fennsen64 ,
version 2.0.0 is available now containing the solution I mentioned in my post above. please have a look.

**Comment by Apollon77** [comment]
Released in 3.0.0
