### ISSUE TITLE
can this be bumped to nodered 20.7?

### ISSUE THREAD

**Issue by MattL0** [ioBroker/ioBroker.node-red#59]

**Comment by Apollon77** [comment]
GitHub is updated to 0.20.7 (including some other dependecies als updated) Please check and give feedback

**Comment by MattL0** [comment]
Thanks ! This works perfectly

**Comment by Apollon77** [comment]
Super, will release tomorrow to npm then.

**Comment by MattL0** [comment]
Just wanted to let you know that NR 20.8 is out .

**Comment by Apollon77** [comment]
Best would be to create a new issue for this in the future. GitHub updted, Please test and report back

**Comment by MattL0** [comment]
ok will do. It works perfect!
