### ISSUE TITLE
node red Adapter: "crash loop" direkt beim Start

### ISSUE THREAD

**Issue by ikemuc** [ioBroker/ioBroker.node-red#61]
Hallo,
ich habe vor einigen Tagen den Node Red Adapter im ioBroker installiert und einen Flow entwickelt, der auch ganz gut lief. Der Adapter hat die aktuellste Version.
Nach einer Änderung am Flow kam plötzlich eine Browser-Fehlermeldung, dass er die Seite nicht findet. Seitdem ist Node Red quasi tot.

Im ioBroker Log ist zu sehen, dass Node Red gestartet wird, dann kommen 3 Warnings, dann eine Fehlermeldung aus meinem Flow, der u.A. node-red-contrib-teslams verwendet, und dann gibt es einen Exit mit code 1. Das Ganze läuft endlos.
Die Node Red Webseite ist nicht erreichbar, entweder kein connect möglich oder man bekommt Bruchstücke, aber dann kommt der Exit dazwischen.

node-red.0	2019-07-23 12:18:37.415	info	node-red exited with 1
node-red.0	2019-07-23 12:18:36.659	error	23 Jul 12:18:36 - [error] [function:IsTeslaAtHome] TypeError: Cannot read property 'latitude' of undefined
node-red.0	2019-07-23 12:18:36.474	warn	23 Jul 12:18:36 - [warn] Projekte inaktiviert: setze editorTheme.projects.enabled=true zum Aktivieren
node-red.0	2019-07-23 12:18:35.773	warn	23 Jul 12:18:35 - [warn] rpi-gpio : Pi RPi.GPIO-Python-Bibliothek nicht gefunden
node-red.0	2019-07-23 12:18:35.772	warn	23 Jul 12:18:35 - [warn] rpi-gpio : Raspberry Pi-spezifische Nodes inaktiv
node-red.0	2019-07-23 12:18:35.064	info	Starting node-red: --max-old-space-size=256 /opt/iobroker/node_modules/iobroker.node-red/node_modules/node-red/red.js -v --settings /opt/iobroker/iobroker-data/node-red/settings.js
node-red.0

Eine Änderung, die ich vorher am Code gemacht hatte, war die Erzeugung eines weiteren Flows und ein Ausschneiden einiger Nodes aus dem einen Flow und Einsetzen im neuen Flow.

Ich habe inzwischen bereits den Node Red Adapter deinstalliert und neu installiert, kein Unterschied.

Wie kann ich den Crash verhindern und wieder an meinen Flow kommen? 🙂
Kann ich evtl. meinen Flow sichern und danach entfernen? Wo liegt der?

Zusatzfrage: Wie kann ich die Parameter beim Start des Adapters ändern. Es gibt wohl im node red Adapter einen Parameter --safe, der verhindert, dass der Crash passiert...

Hilfe wäre toll! 🙂

**Comment by Apollon77** [comment]
Bitte stelle solche "nicht Adapter Fehler" als Frage im ioBroker Forum, da dort mehr Nutzer unterwegs sind als hier auf GitHub
