### ISSUE TITLE
debug Log: node-red exited with 1

### ISSUE THREAD

**Issue by ConBeeUser** [ioBroker/ioBroker.node-red#62]
Hi, und vielen Dank an die Developer des Adapters :-)

ich habe derzeit große Probleme mit Node-Updates (über die Palette).
Ich habe mir schon mehrfach den Adapter zerschossen, indem ich jeweils die Nodes "huemagic", "Alexa-Home" und "eztimer" aktualisiert habe.

Der Fehler hat im Log (debug) zu folgendem Verhalten geführt:
```
-node-red Adapter wird gestartet
-"node-red exited with 1"
```

Wäre es möglich, in den Adapter eine Option einzubauen, mit der man den Node Red **Adapter im "--safe" Mode startet**? bei einer externen Installation lässt sich Node Red so mit gestoppten Flows starten, was bspw. die Behebung eines Zirkelbezuges ermöglicht. Ansonsten hat man bei einem Zirkelbezug häufig wegen Überlastung des Systems gar keine Chance, in die Bearbeitungsansicht zu gelangen, um dort Änderungen einzupflegen und zu implementieren.

Ob das bei meinem derzeitigen Problem hilft wage ich jedoch zu bezweifeln, da nicht die Flows, sondern scheinbar die installieren Nodes das Problem sein dürften.

Falls jemand andere Ideen zur Lokalisierung des **"node-red exited with 1"**-Problems und/oder Lösungsvorschläge hat, würde ich mich darüber sehr freuen :-)

Viele Grüße!

EDIT: das korrekte Flag scheint "--safe" zu sein. Ich hbae dies oben korrigiert.
Siehe:
[https://discourse.nodered.org/t/node-red-continually-fails-and-restarts/7360/18](https://discourse.nodered.org/t/node-red-continually-fails-and-restarts/7360/18)

**Comment by GermanBluefox** [comment]
Implemented (actually only on github)
