### ISSUE TITLE
Node red is out 

### ISSUE THREAD

**Issue by MattL0** [ioBroker/ioBroker.node-red#64]
Is it possible to update this package to nodered 1.0? 

Thanks

**Comment by Apollon77** [comment]
Are there braking changes?

**Comment by nob0dy80** [comment]
yes there are.
https://nodered.org/blog/2019/09/30/version-1-0-released

**Comment by Apollon77** [comment]
Ok, but from have a very quick look not too much.

I can try to update GitHub tomorrow and you test it?

**Comment by nob0dy80** [comment]
@Apollon77 
alone the "asynchonous message passing" would be a reason for me to upgrade ;)

Feel free to put it in a developer branch

**Comment by Apollon77** [comment]
Ok, install 1.11.0 from Github and give Feedback please

**Comment by Apollon77** [comment]
check 0.12.0 from GitHub, also allows to eable projects feature via admin

**Comment by nob0dy80** [comment]
will do so at the weekend.
