### ISSUE TITLE
Dasboard funktioniert bei Nutzung von Reverse Proxy nicht wenn Version > 2.11.0

### ISSUE THREAD

**Issue by SBorg2014** [ioBroker/ioBroker.node-red#65]
Bei Nutzung eines Reverse Proxys funktioniert das Dashboard nicht wenn die Dashboard-Version größer als 2.11.0 ist (aktuell mit der 2.17.0 geht es auch nicht). Man erhält nur einen blank Screen.
siehe auch: https://forum.iobroker.net/post/309148

work around: downgrade des Dashboardes auf Version 2.11.0

```
cd /opt/iobroker/node_modules/iobroker.node-red/
npm install node-red-dashboard@2.11.0
```

**Comment by GermanBluefox** [comment]
Ist das nicht das Problem von node-red-dashboard ??

**Comment by Apollon77** [comment]
Am Ende ja. Aber wir installieren das als dependency direkt mit.

**Comment by SBorg2014** [comment]
Kann aber eigentlich geschlossen werden, denn es funktioniert jetzt. Da der Support für nodejs 8.x am 31.12.2019 offiziell endete und es keine größeren Versionen mehr für 32Bit gibt, habe ich die Tage auf 64Bit und nodejs 10.x geupgraded. Problem behoben. Scheint also am 32Bit gelegen zu haben.
... und wie viele Nutzer werden 32Bit, Nodejs 8.x und einen Reverse Proxy einsetzen, denn nur da tritt das Problem auch auf?
