### ISSUE TITLE
States under folders not working (Topics with ".")

### ISSUE THREAD

**Issue by RustyThePropellerHead** [ioBroker/ioBroker.node-red#66]
Hello,
When I send a new payload via the out-node (with no topic defined in the out-node) with a "." in the topic (e.g. Temperature.Room) this results in a folder (Temperature) with the state (Room) being created in the Object explorer 👍, but the values are never propagated 👎

If I set the topic to "node-red.0.Temperature.Room", the value is updated (...my current work-around).

Please find a fix as this would greatly help me keep my variables organised.

Cheers,
Rusty

**Comment by jwiesel** [comment]
Hi there,
I have the same issue as @RustyThePropellerHead.

## Steps to reproduce the issue:
* Create an inject node (e.g. to set the timestamp)
* Create an iobroker out node (Topic: node-red.0.mydevice.state ; Type: "value"; AutoCreate: "Create states if not exist")
* Connect both nodes, deploy and run

## Result (in ioBroker Object Explorer)
* new folder "mydevice" is created under instance "node-red.0" --> OK
* new state "node-red.0.mydevice.state" is created in folder "mydevice" --> not good

## Workaround
* rename state "node-red.0.mydevice.state" to "mydevice.state" in folder "mydevice"

## Lessons learned
* Apparently, when I include the instance name into the topic for a new out-node, propagating the value seems to work, but then I need to rename the state to avoid losing overview of my objects.

**Comment by Apollon77** [comment]
> new state "node-red.0.mydevice.state" is created in folder "mydevice" --> not good

Can you please show a screenshort of what you see in admin or explorer?

**Comment by Apollon77** [comment]
PS Which version you tried?

**Comment by Apollon77** [comment]
there should be a log line in iobroker log when the object is created. please provide this

**Comment by Apollon77** [comment]
And please try 0.17.0 from Github

**Comment by jwiesel** [comment]
Just tested scenario 1 (described by @RustyThePropellerHead ) on 1.17.1
This seems to work now: 
When pressing refresh in the ioBroker Admin I see updates coming in (timestamp)
![1 17 1-scenario1](https://user-images.githubusercontent.com/11034083/80453789-3e4b2d00-8929-11ea-8e46-7e8ea18ca2b4.png)

Regarding scenario 2 (my original post)
One thing you can also see in the screenshot above is, that although the state is in the correct folder, the "name" column always shows the full hierarchy. It's not a technical issue, but you might loose the overview with too many states per folder.
I can rename the entry and updates on that entry still work.
Screenshot after renaming: 
![Scenario2-After-Rename](https://user-images.githubusercontent.com/11034083/80454182-f1b42180-8929-11ea-952e-0b18b45c5e5b.png)

**Comment by Apollon77** [comment]
The name is compiled as follows:

node.objectPreDefinedName   || msg.stateName || id

Whatever first is set. So the first should be a setting of the outnode and allowed to be set by you, second would be from the message incoming, last option is the id .. so as expected

So we can close here?

**Comment by jwiesel** [comment]
Thanks @Apollon77!
I just realized the name field which appears when selecting "Create a new object if doesn't exist". That did the trick for me. From my point of view we can close the issue
@RustyThePropellerHead : What do you think?

**Comment by RustyThePropellerHead** [comment]
I'm fine with using my work around posted in my original post, I'll close this out...
