### ISSUE TITLE
Feature Request: Logging Node

### ISSUE THREAD

**Issue by RustyThePropellerHead** [ioBroker/ioBroker.node-red#68]
Hello,
It would be nice to have an ioBroker node in node-red that puts entries in the ioBroker log, a assume this should be posable as Programming failures in Node-Red are logged in ioBroker.

Please think it over :-)

Cheers,
Rusty

**Comment by Apollon77** [comment]
Good idea ... can you provide an PR?

**Comment by RustyThePropellerHead** [comment]
Trying to work on it...
stdout:
```
22 Oct 22:59:30 - [info] [debug:739a8b5a.1fd9e4] 1571777970176
22 Oct 23:05:16 - [info] [debug:739a8b5a.1fd9e4] { _msgid: '44259088.e3aca', topic: '', payload: 1571778316382 }
22 Oct 23:05:20 - [error] [function:c3780201.3c607] ReferenceError: dummy is not defined (line 1, col 1)
```
When the debug node has the system console enabled then in terminal comes "[info] [debug:" 22:59:30 is a debug with msg.paylod, 23:05:16 is a debug with the complete msg.

The error @23:05:20 is logged in ioBroker...

Shouldn't [main.js Line 211](https://github.com/ioBroker/ioBroker.node-red/blob/a0e1072ca981f8016be08a8f8bf6b6ca7a1dbca1/main.js#L211) be logging the info stdouts?

**Comment by Apollon77** [comment]
Yes but as debug. You should see them when you set your instance to debug loglevel

**Comment by RustyThePropellerHead** [comment]
Palm meet face, I realised that while you where commenting...
main.js modified, check out my [PR](https://github.com/ioBroker/ioBroker.node-red/pull/69).
