### ISSUE TITLE
new node "ioBroker get list"

### ISSUE THREAD

**Issue by jobe451** [ioBroker/ioBroker.node-red#73]
I have 3 use cases which I can't fulfill with node-red for iobroker currently:
a) send me an email for battery devices, that have a battery state lower than x
b) switch of lights that are running for more than x hours
c) switch off lights that come on per default after a blackout

All of these use-cases have in common that they should do some action for each device that match a certain pattern. 

For instance for a) I would like do this:
1. the list of all nodes that match zigbee\.0\.[0-9a-f]+\.battery
2. use "split" the split node to check those devices individually (ioBroker get, switch, ...)
3. use "join" to agregate the devices with low battery power
4. use email to send out notifications

so therefore my proposal, please add an "iobroker get list" node that outputs all the devices matching a certain pattern so that this list can be worked on using the split-node.

**Comment by GermanBluefox** [comment]
Implemented (actually only github version)
