### ISSUE TITLE
iobroker-input-node: True/False wird als String gesendet

### ISSUE THREAD

**Issue by ploebb** [ioBroker/ioBroker.node-red#8]
In Zeile 163 der /nodes/ioBroker.js steht
`payload: (node.payloadType == 'object') ? obj : (obj.val === null || obj.val === undefined) ? '' : obj.val.toString(),`

Dadurch wird ein Boolscher Wert auch als String gesendet und kann dann nicht mit einem "is true/is false" abgefragt werden sondern nur mit einem " contains 'true' ".

Geht natürlich auch, aber was ist der Grund des .toString()? Könnte man das nicht einfach weglassen?

**Comment by ploebb** [comment]
Ich habe das `.toString()` aus dem Input und dem Get-node jetzt einfach mal entfernt und jetzt stimmt auch der Variablentyp. Getestet mit Bool und Number. 

Bisher keine Probleme, aber ich schätze das stand da nicht nur zum Spaß?

**Comment by GermanBluefox** [comment]
Muss ehrlich sagen: ganz gut errinern kann ich auch nicht. Aber ausser
number, string und BOOL gibt es noch Objekte. Vermutlich war das Schutz
dagegen. Vor allem vor ein Jahr konnte node-red nichts ausser strings, mqtt
bedingt. Das konnte auch die Ursache sein.

Ich schaue an
11 Апр 2016 г. 18:21 пользователь "ploebb" <notifications@github.com>
написал:

**Comment by ploebb** [comment]
Okay. 
Dann werde ich jetzt erst mal meine angepasste Version so weiter nutzen und wenn ich ein Problem damit finde, melde ich das hier :-)

**Comment by mobilutz** [comment]
Shouldn't this be closed already?
