### ISSUE TITLE
Warn msg in the log

### ISSUE THREAD

**Issue by timae146** [ioBroker/ioBroker.node-red#82]
![log](https://user-images.githubusercontent.com/42387818/74368575-396be800-4dd4-11ea-9b63-9dbf4aef5aac.PNG)

there appeard a warn msg in my log, after system update
(
Node.js -> v10.19.0
NPM -> 6.13.4
js-controller -> 2.2.8
)

my alexa node dont work anymore since then.
![Unbenannt](https://user-images.githubusercontent.com/42387818/74369181-3a514980-4dd5-11ea-907b-92c62a292147.PNG)

is there a relation?

**Comment by Apollon77** [comment]
The error says that the server can not listen on port 80. try running installation fixer to allow listening to port80. And check if pot other processes are running in parallel

**Comment by timae146** [comment]
wow. the iobroker fixer has done its work. Sometimes it´s too easy. sry for the issue and ty for the fast help. 
seems it can be closed here. *thumps up*
