### ISSUE TITLE
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 101 stateChange listeners added. Use emitter.setMaxListeners() to increase limit

### ISSUE THREAD

**Issue by mickym2** [ioBroker/ioBroker.node-red#84]
`

node-red.0 | 2020-02-20 14:38:03.129 | warn | (8105) (node:8126) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 101 stateChange listeners added. Use emitter.setMaxListeners() to increase limit
-- | -- | -- | --

`
Since a few weeks - i got this warning in my log. As I didn't write any new code and just use node-red for my logical flows - I have no idea - what I should do. 
I decreased the number of mqtt input nodes - but when I restart the number of stateChange listeners remain constant.

Ich habe keine Idee - wie oder was ich mit dieser Warnung anstellen soll. Ich habe keinen neuen Code geschrieben und meine Flows werden ausschließlich mit node-red verarbeitet. Ich habe mal die mqtt Nodes reduziert - aber gibt immer noch die gleiche Anzahl an listeners added.

**Comment by mickym2** [comment]
This error happens all times if I restart all flows in node-red.

Diese Fehlermeldung erhalte ich sobald ich alle Flows neustarte.

**Comment by Apollon77** [comment]
Please try 1.16.1 from GitHub. Limit increased to 1000 before warning is displayed :-)

**Comment by easybeat** [comment]
I still get this message:

![image](https://user-images.githubusercontent.com/37217887/97111729-cc3d8000-16e0-11eb-86d2-8dbfbbed8fbe.png)

and I'm on version 1.17.2.

What could be the problem?

**Comment by Apollon77** [comment]
The process id in brackets ... do they belong to the adapter process or to the node-red process?
