### ISSUE TITLE
Node red 1.04 is out

### ISSUE THREAD

**Issue by MattL0** [ioBroker/ioBroker.node-red#86]
Just a reminder when you have time to update it.

**Comment by Apollon77** [comment]
please try 1.16.0 from github and give feedbck

**Comment by MattL0** [comment]
Thanks !! Will give it a go today

**Comment by MattL0** [comment]
I have this error ( and I remember last time i tried 1.15.0 i had the same error) 

node-red.0 | 2020-03-11 21:58:02.570 | info | (10753) node-red exited with 0
-- | -- | -- | --
node-red.0 | 2020-03-11 21:58:02.345 | info | (10753) Starting node-red: --max-old-space-size=128 /opt/iobroker/node_modules/node-red/red.js -v --settings /opt/iobroker/iobroker-data/node-red/settings.js
node-red.0 | 2020-03-11 21:57:57.344 | info | (10753) node-red exited with 0
node-red.0 | 2020-03-11 21:57:57.114 | info | (10753) Starting node-red: --max-old-space-size=128 /opt/iobroker/node_modules/node-red/red.js -v --settings /opt/iobroker/iobroker-data/node-red/settings.js
node-red.0 | 2020-03-11 21:57:52.114 | info | (10753) node-red exited with 0
node-red.0 | 2020-03-11 21:57:51.894 | info | (10753) Starting node-red: --max-old-space-size=128 /opt/iobroker/node_modules/node-red/red.js -v --settings /opt/iobroker/iobroker-data/node-red/settings.js
node-red.0 | 2020-03-11 21:57:46.892 | info | (10753) node-red exited with 0
node-red.0 | 2020-03-11 21:57:46.673 | info | (10753) Starting node-red: --max-old-space-size=128 /opt/iobroker/node_modules/node-red/red.js -v --settings /opt/iobroker/iobroker-data/node-red/settings.js
node-red.0 | 2020-03-11 21:57:41.672 | info | (10753) node-red exited with 0
node-red.0 | 2020-03-11 21:57:41.449 | info | (10753) Starting node-red: --max-old-space-size=128 /opt/iobroker/node_modules/node-red/red.js -v --settings /opt/iobroker/iobroker-data/node-red/settings.js
node-red.0 | 2020-03-11 21:57:36.449 | info | (10753) node-red exited with 0
node-red.0 | 2020-03-11 21:57:36.230 | info | (10753) Starting node-red: --max-old-space-size=128 /opt/iobroker/node_modules/node-red/red.js -v --settings /opt/iobroker/iobroker-data/node-red/settings.js
node-red.0 | 2020-03-11 21:57:31.230 | info | (10753) node-red exited with 0
node-red.0 | 2020-03-11 21:57:31.007 | info | (10753) Starting node-red: --max-old-space-size=128 /opt/iobroker/node_modules/node-red/red.js -v --settings /opt/iobroker/iobroker-data/node-red/settings.js
node-red.0 | 2020-03-11 21:57:26.005 | info | (10753) node-red exited with 0

**Comment by Apollon77** [comment]
And how you solved it? ;-)

**Comment by Apollon77** [comment]
In this case the node -red process just ends. Can you try running the command on command line to see if maybe something is written to console about reason?

**Comment by MattL0** [comment]
By reinstalling 1.13.0

**Comment by MattL0** [comment]
What command should in run in console?

**Comment by Apollon77** [comment]
```
node --max-old-space-size=128 /opt/iobroker/node_modules/node-red/red.js -v --settings /opt/iobroker/iobroker-data/node-red/settings.js
```

**Comment by MattL0** [comment]
I got  node --max-old-space-size=128 /opt/iobroker/node_modules/node-red/red.js -v --settings /opt/iobroker/iobroker-data/node-red/settings.js
Error loading settings file: /opt/iobroker/iobroker-data/node-red/settings.js/opt/iobroker/iobroker-data/node-red/settings.js:32
    allowCreationOfForeignObjects: ,
                                   ^

SyntaxError: Unexpected token ,
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/opt/iobroker/node_modules/node-red/red.js:119:20)    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

**Comment by Apollon77** [comment]
hm ... interesting, then configfile is generated wrong. can you please open admin, save settings and start once via admin?

**Comment by MattL0** [comment]
not sure what to do here. it is the first time i do this.

![Capture](https://user-images.githubusercontent.com/27497561/76523563-018daa00-643f-11ea-915f-7ed982c75e9e.PNG)
![1](https://user-images.githubusercontent.com/27497561/76523574-05b9c780-643f-11ea-8bb1-1473442999f0.PNG)

**Comment by MattL0** [comment]
i can't go out out of admin

**Comment by Apollon77** [comment]
You mesan because buttons are grey? Then type in somewhere and delete it again ...then save button should be active

**Comment by MattL0** [comment]
when i type in chrome ''iobroker_IP:port'' i only see this now 
![Capture](https://user-images.githubusercontent.com/27497561/76524915-44508180-6441-11ea-9341-4d8d9c5d39c6.PNG)

**Comment by MattL0** [comment]
will load my backup. I think i selected the wrong thing in admin the first time?

**Comment by MattL0** [comment]
This is what i get in the log if I only select node red 


  |   |   |  
-- | -- | -- | --
node-red.0 | 2020-03-12 09:28:59.927 | info | (4900) node-red exited with 0
node-red.0 | 2020-03-12 09:28:59.707 | info | (4900) Starting node-red: --max-old-space-size=256 /opt/iobroker/node_modules/node-red/red.js -v --settings /opt/iobroker/iobroker-data/node-red/settings.js
node-red.0 | 2020-03-12 09:28:54.706 | info | (4900) node-red exited with 0
node-red.0 | 2020-03-12 09:28:54.489 | info | (4900) Starting node-red: --max-old-space-size=256 /opt/iobroker/node_modules/node-red/red.js -v --settings /opt/iobroker/iobroker-data/node-red/settings.js
node-red.0 | 2020-03-12 09:28:49.488 | info | (4900) node-red exited with 0
node-red.0 | 2020-03-12 09:28:49.265 | info | (4900) Starting node-red: --max-old-space-size=256 /opt/iobroker/node_modules/node-red/red.js -v --settings /opt/iobroker/iobroker-data/node-red/settings.js
node-red.0 | 2020-03-12 09:28:44.265 | info | (4900) node-red exited with 0
node-red.0 | 2020-03-12 09:28:44.046 | info | (4900) Starting node-red: --max-old-space-size=256 /opt/iobroker/node_modules/node-red/red.js -v --settings /opt/iobroker/iobroker-data/node-red/settings.js
node-red.0 | 2020-03-12 09:28:39.045 | info | (4900) node-red exited with 0
node-red.0 | 2020-03-12 09:28:38.814 | info | (4900) Starting node-red: --max-old-space-size=256 /opt/iobroker/node_modules/node-red/red.js -v --settings /opt/iobroker/iobroker-data/node-red/settings.js
node-red.0 | 2020-03-12 09:28:33.812 | info | (4900) node-red exited with 0
node-red.0 | 2020-03-12 09:28:33.585 | info | (4900) Starting node-red: --max-old-space-size=256 /opt/iobroker/node_modules/node-red/red.js -v --settings /opt/iobroker/iobroker-data/node-red/settings.js
node-red.0 | 2020-03-12 09:28:28.584 | info | (4900) node-red exited with 0
node-red.0 | 2020-03-12 09:28:28.354 | info | (4900) Starting node-red: --max-old-space-size=256 /opt/iobroker/node_modules/node-red/red.js -v --settings /opt/iobroker/iobroker-data/node-red/settings.js
node-red.0 | 2020-03-12 09:28:23.354 | info | (4900) node-red exited with 0
node-red.0 | 2020-03-12 09:28:23.132 | info | (4900) Starting node-red: --max-old-space-size=256 /opt/iobroker/node_modules/node-red/red.js -v --settings /opt/iobroker/iobroker-data/node-red/settings.js
node-red.0 | 2020-03-12 09:28:22.995 | info | (4900) starting. Version 1.16.1 in /opt/iobroker/node_modules/iobroker.node-red, node: v10.19.0
node-red.0 | 2020-03-12 09:26:30.699 | info | (3781) Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason
node-red.0 | 2020-03-12 09:26:30.697 | info | (3781) node-red exited with null
node-red.0 | 2020-03-12 09:26:30.697 | warn | (3781) adapter.getMessage is deprecated and will be removed in js-controller 3.0. Please report this warning to the developer of this adapter!
node-red.0 | 2020-03-12 09:26:30.693 | info | (3781) kill node-red task
node-red.0 | 2020-03-12 09:25:49.128 | warn | (3781) 12 Mar 09:25:49 - [warn] Projects disabled : editorTheme.projects.enabled=false
node-red.0 | 2020-03-12 09:25:47.980 | info | (3781) Starting node-red: --max-old-space-size=256 /opt/iobroker/node_modules/node-red/red.js -v --settings /opt/iobroker/iobroker-data/node-red/settings.js
node-red.0 | 2020-03-12 09:25:42.979 | info | (3781) node-red exited with 1
node-red.0 | 2020-03-12 09:25:42.975 | error | (3781) 12 Mar 09:25:42 - [error] Error: port in use
node-red.0 | 2020-03-12 09:25:42.975 | error | (3781) 12 Mar 09:25:42 - [error] Unable to listen on http://127.0.0.1:1889/
node-red.0 | 2020-03-12 09:25:42.916 | warn | (3781) 12 Mar 09:25:42 - [warn] Projects disabled : editorTheme.projects.enabled=false
node-red.0 | 2020-03-12 09:25:42.837 | info | (2424) Terminated (NO_ERROR): Without reason
node-red.0 | 2020-03-12 09:25:41.760 | info | (3781) Starting node-red: --max-old-space-size=256 /opt/iobroker/node_modules/node-red/red.js -v --settings /opt/iobroker/iobroker-data/node-red/settings.js
node-red.0 | 2020-03-12 09:25:41.630 | info | (3781) starting. Version 1.13.0 in /opt/iobroker/node_modules/iobroker.node-red, node: v10.19.0
node-red.0 | 2020-03-12 09:25:41.334 | warn | (2424) Got terminate signal. Checking desired PID: 3781 vs own PID 2424
node-red.0 | 2020-03-12 09:25:41.333 | warn | (2424) Got terminate signal. Checking desired PID: 0 vs own PID 2424
node-red.0 | 2020-03-12 09:25:39.750 | warn | (3769) Terminated (NO_ADAPTER_CONFIG_FOUND): Without reason
node-red.0 | 2020-03-12 09:25:39.747 | error | (3769) adapter disabled
node-red.0 | 2020-03-12 09:25:39.456 | warn | (2424) Got terminate signal. Checking desired PID: 3769 vs own PID 2424
node-red.0 | 2020-03-12 09:25:39.455 | warn | (2424) Got terminate signal. Checking desired PID: 0 vs own PID 2424
node-red.0 | 2020-03-12 09:25:38.834 | info | (2424) Adapter is disabled => stop
node-red.0 | 2020-03-12 09:25:36.952 | info | (2346) Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason
node-red.0 | 2020-03-12 09:25:35.952 | warn | (2346) adapter.getMessage is deprecated and will be removed in js-controller 3.0. Please report this warning to the developer of this adapter!
node-red.0 | 2020-03-12 09:25:35.950 | info | (2346) kill node-red task
node-red.0 | 2020-03-12 09:22:43.773 | warn | (2346) 12 Mar 09:22:43 - [warn] Projects disabled : editorTheme.projects.enabled=false
node-red.0 | 2020-03-12 09:22:42.551 | info | (2346) Starting node-red: --max-old-space-size=128 /opt/iobroker/node_modules/node-red/red.js -v --settings /opt/iobroker/iobroker-data/node-red/settings.js
node-red.0 | 2020-03-12 09:22:42.415 | info | (2346) starting. Version 1.13.0 in /opt/iobroker/node_modules/iobroker.node-red, node: v10.19.0

**Comment by MattL0** [comment]
saving via admin do not change anything

**Comment by Apollon77** [comment]
Two questions:
* how you install these updated? Via Admin and custom install?
* Please try if "iobroker upload node-red" on command line solves it
* Which js-controller version is installed?

**Comment by Apollon77** [comment]
So I also set a new version to GitHub. Please install via Admin Custom Install

**Comment by MattL0** [comment]
I didn’t know i could install from github via admin. I was using the console.

It is working now . Thanks for the update.

I am using version 2.2.9 of js controler

**Comment by Apollon77** [comment]
Aaahhhh ok. Then most likely you only used npm correct? If doing this you always need to execute „iobroker upload adaptername“ afterwards!!!

**Comment by MattL0** [comment]
thanks ! didn't know because i didn't have to do this before :P

**Comment by Apollon77** [comment]
Lets say it that way: This is needed anytime, else the adapter meta data are not updated and such strrange things could happen as you described.

Best always use admin and do not do stuff via npm directly

**Comment by MattL0** [comment]
Understood , thanks again :)
