### ISSUE TITLE
NodeRed 1.16.2 -> Alexa devices not working

### ISSUE THREAD

**Issue by atifan** [ioBroker/ioBroker.node-red#87]
Hi my Alexa controlled devices are not working with the new Version 1.16.2
I get some errors in IoBroker Log (see screenshots).
I went back to Version 1.13.0 and all works fine.
Must be a bug in the new Version of NodeRed.

Additional installed this: node-red-contrib-amazon-echo

![image](https://user-images.githubusercontent.com/58658412/76689828-3a45a300-663a-11ea-9de4-9de41a027b34.png)

![image](https://user-images.githubusercontent.com/58658412/76689823-33b72b80-663a-11ea-97c2-f8c3c46f1800.png)

**Comment by Apollon77** [comment]
Please check 1.16.3 from GitHub and give Feedback

**Comment by atifan** [comment]
Wow nice, yeah it seems to be fixed. Works fine with 1.16.3
Thanks :)
