### ISSUE TITLE
msg.topic is immer null seit 1.16.2

### ISSUE THREAD

**Issue by jobe451** [ioBroker/ioBroker.node-red#88]
Habe heute auf 1.16.2/1.16.3 gewechselt. Seither ist die msg.topic immer null. 

Das bedeutet, dass die meisten meiner Lichtschalter nicht mehr funktionieren.

Ich konnte auf 1.16.2 zurückgehen aber nicht auf 1.15.0. Beim Revert auf 1.15.0 bekam ich:
```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for iobroker.node-red@1.15.0.
npm ERR! notarget In most cases you or one of your dependencies are requestingnpm ERR! notarget a package version that doesn't exist.
```

**Comment by Apollon77** [comment]
Das scheint ein bug in node-red zu sein. Kannst du bitte mal dort recherchieren? Die letzte npm Version davor war die 1.13. über Admin ist ein downgrade möglich. Ich schau nachher einmal ob ich eine 1.15 veröffentlichen kann.

**Comment by Apollon77** [comment]
Can you tell me exactly please where it is missing? get Node or input node?

**Comment by jobe451** [comment]
Danke, der downgrade auf 1.13.0 hat funktioniert, msg.topic ist wieder present und die Schalter funktionieren wieder. Da scheint tatsächlich etwas kaputt zu sein.

Das Problem tritt mit Sicherheit bei "iobroker in" auf. Bei "iobroker get" weiss ichs nicht.

**Comment by Apollon77** [comment]
ok, danke

**Comment by Apollon77** [comment]
Hast Du mal einen Namen eines genutzten States im in?

**Comment by Apollon77** [comment]
@GermanBluefox Please also check!

**Comment by jobe451** [comment]
Zum Beispiel:
![image](https://user-images.githubusercontent.com/910027/76711786-1013e400-6713-11ea-82f3-fbefc115589c.png)

**Comment by guenter-ohne-h** [comment]
Alles was unter "0_userdata.0.xxx" geändert wird funkioniert. in Iobroker-in-Node und Iobroker-get-Node.
Bei z.B. "User.0.xxx" kommt beim Iobroker-in-Node nichts an, Iobroker-get-Node lässt Node-red mit einem Fehler neu starten, siehe auch Auschnitt vom LOG.. (Iobroker-get-Node)
`

node-red.0 | 2020-03-16 12:55:27.336 | info | (10970) Save /opt/iobroker/iobroker-data/node-red/flows.json
-- | -- | -- | --
node-red.0 | 2020-03-16 12:54:53.999 | warn | (10970) 16 Mar 12:54:53 - [warn] Projekte inaktiviert: editorTheme.projects.enabled=false
node-red.0 | 2020-03-16 12:54:50.090 | info | (10970) Starting node-red: --max-old-space-size=128  /opt/iobroker/node_modules/node-red/red.js -v --settings  /opt/iobroker/iobroker-data/node-red/settings.js
node-red.0 | 2020-03-16 12:54:45.089 | info | (10970) node-red exited with 1

`

**Comment by Apollon77** [comment]
Ok, dann hab ich ne Idee :-) vllt ist es nur das ... versuch mal die gitHub Version bitte

**Comment by Apollon77** [comment]
1.16.4 on GitHub

**Comment by guenter-ohne-h** [comment]
Läuft, zumindest der obige Testflow
