### ISSUE TITLE
Warnungen im Log

### ISSUE THREAD

**Issue by ihavenonick** [ioBroker/ioBroker.node-red#89]
sollte diese Warnung nicht mit der aktuellen Version gefixt sein?
`

node-red.0 | 2020-03-15 08:22:05.159 | warn | (11977) 15 Mar 08:22:05 - [warn] Projekte inaktiviert: editorTheme.projects.enabled=false
-- | -- | -- | --

`

**Comment by Apollon77** [comment]
Nein. Wenn das Feature aus geschaltet ist kommt diese Meldung.
