### ISSUE TITLE
crash when read value

### ISSUE THREAD

**Issue by Samuel-0-0** [ioBroker/ioBroker.node-red#90]
crash when read value if topic is non-existent , use ioBroker-get node,
return error msg is recommend

**Comment by Apollon77** [comment]
Sorry I do not understand your issue. Please post logs when you see a crash. What error is shown? Which version you use?

**Comment by GermanBluefox** [comment]
Please test 1.16.5

**Comment by Samuel-0-0** [comment]
not working,
try this for non-existent state
`[
    {
        "id": "3b1f8d35.da3c22",
        "type": "inject",
        "z": "ccf03ab3.fc74a8",
        "name": "",
        "topic": "node-red/0/test/test1",
        "payload": "",
        "payloadType": "date",
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "x": 410,
        "y": 1480,
        "wires": [
            [
                "e79060e2.784ea"
            ]
        ]
    },
    {
        "id": "e79060e2.784ea",
        "type": "ioBroker get",
        "z": "ccf03ab3.fc74a8",
        "name": "",
        "topic": "",
        "attrname": "value",
        "payloadType": "value",
        "x": 580,
        "y": 1480,
        "wires": [
            [
                "f3f4d1ac.1f6cb"
            ]
        ]
    },
    {
        "id": "f3f4d1ac.1f6cb",
        "type": "debug",
        "z": "ccf03ab3.fc74a8",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "x": 750,
        "y": 1480,
        "wires": []
    }
]`

then the node-red restart.

logs here 
`

node-red.0 | 2020-03-18 01:10:03.195 | info | (4111) node-red exited with 1
-- | -- | -- | --
node-red.0 | 2020-03-18 01:10:03.173 | debug | at process._tickCallback (internal/process/next_tick.js:189:7)
node-red.0 | 2020-03-18 01:10:03.173 | debug | at <anonymous>
node-red.0 | 2020-03-18 01:10:03.173 | debug | at promise.then (/opt/iobroker/node_modules/standard-as-callback/built/index.js:19:49)
node-red.0 | 2020-03-18 01:10:03.173 | debug | at tryCatcher (/opt/iobroker/node_modules/standard-as-callback/built/utils.js:11:23)
node-red.0 | 2020-03-18 01:10:03.173 | debug | at client.get (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInRedis.js:572:33)
node-red.0 | 2020-03-18 01:10:03.173 | debug | at /opt/iobroker/node_modules/iobroker.node-red/nodes/ioBroker.js:504:37
node-red.0 | 2020-03-18 01:10:03.173 | debug | 18 Mar 01:10:03 - ReferenceError: id is not defined
node-red.0 | 2020-03-18 01:10:03.173 | debug | (4111) 18 Mar 01:10:03 - [red] Uncaught Exception:

`

**Comment by Apollon77** [comment]
please check 1.16.5

**Comment by Apollon77** [comment]
hm ... its crashing because it wants to log that the state is not existing

**Comment by Samuel-0-0** [comment]
so is that normal ?

**Comment by Apollon77** [comment]
will be fixed in 0.17.0 soon
