### ISSUE TITLE
iobroker out: msg.topic wird ignoriert

### ISSUE THREAD

**Issue by jobe451** [ioBroker/ioBroker.node-red#91]
Das ist ein Follow-up zu #88. Stellt sich heraus, das war nur die halbe Miete. Am anderen Ende gibt's auch ein Problem.

Ich habe zu 1.16.4 upgegraded, die Grundproblematik bleibt dieselbe. Lichtschalter funktionieren nicht.
 
Das msg.topic wird zwar wieder übergeben, allerdings scheint dies nun von "iobroker out" nicht mehr korrekt interpretiert zu werden. Ich habe einen bestehenden flow stark vereinfacht zur Demo. Meine "produktiven" Flows benutzen Subflows damit ich gewisse Funktionen wiederverwenden kann. Über die topics mappe ich Schalter zu Enddevices (für Funktionen, die rein über Gruppen nicht zu bewerkstelligen sind):
![image](https://user-images.githubusercontent.com/910027/76909747-5d778900-68ac-11ea-9bbb-e4f7e5b5dc68.png)

Der Effekt hier ist, dass das Enddevice nicht angeht, obschon das richtige Topic gesetzt ist.

Bei Versionen 1.13 und früher, gab es übrigens eine kleine Inkonsistenz. "iobroker in" notierte topics in der mit forward-slash z.B. "zigbee/0/00158d000205a133/click". "iobroker out" hingegen verlangte einen Punkt als Trenner z.B. "zigbee.0.14b457fffe4591aa.state". Ich habe in 1.16.4 beide Variationen erfolglos getestet. Die Punkt-Notation wäre aus Usersicht wohl verständlicher, denn so werden die Objekte auch in der Objekte-Liste bezeichnet.

**Comment by WolfspiritM** [comment]
Ich hab das hier gerade gefunden. Ich vermute das hängt mit #95 zusammen?!
Wenn "topic" in der iobroker get object node leer ist um "msg.topic" zu verwenden wird "msg.topic" durch "null" ersetzt.

**Comment by Apollon77** [comment]
Please re check with 0.17.0 in Github

**Comment by jobe451** [comment]
Grossartig, funktioniert wieder! Vielen Dank!
