### ISSUE TITLE
Alexa Fehlermeldung 

### ISSUE THREAD

**Issue by PapaH1** [ioBroker/ioBroker.node-red#93]
Hallo zusammen,
ich nutze node.red bisher ausschließlich zur Weiterleitung von Alexa-Befehlen an den iobroker.
Seit einiger Zeit habe ich das Problem, dass Alexa die Fehlermeldung "ich weiß nicht, was schief gelaufen ist" ausgibt, den Befehl aber trotzdem leicht verzögert ausführt. 
Woran könnte das liegen?
System: Raspberry4, 4 GB RAM 
ca 70 Status werden über node.red gesteuert

Wegen meiner Behinderung nutze ich das Smart-Home über iobroker nahezu ausschließlich per Sprachsteuerung. 

Danke für eure Hilfe
Heinz-Jürgen

**Comment by Apollon77** [comment]
Ist die Frage nicht besser in dem Projekt zu stellen welches Du verwendest um das zu tun? ioBroker stellen einen "Blanken" node-red zur verfügung ...

**Comment by PapaH1** [comment]
Danke für den Hinweis, mach ich direkt!
