### ISSUE TITLE
msg.topic is overwritten by null

### ISSUE THREAD

**Issue by WolfspiritM** [ioBroker/ioBroker.node-red#95]
Hi,

I updated node red after a while now and noticed a bug.

I'm using msg.topic to define the device that I want to get. I'm also using that device via msg.topic further on.
If node.topic is left empty to make it use msg.topic however the change in https://github.com/ioBroker/ioBroker.node-red/commit/3171285f5e5bea2bedff1fdb419d3663f220d140 will overwirte msg.topic with "null". I think there should be a check for null or empty before overwriting the topic or if a msg.topic is set it shouldn't overwrite it at all.

**Comment by Apollon77** [comment]
Please try 0.1.7.0 from Github soon
