### ISSUE TITLE
Feature Request: Enable HTTPS via ioBroker Instance Settings

### ISSUE THREAD

**Issue by jwiesel** [ioBroker/ioBroker.node-red#97]
## Idea
* Add options in the Node-RED instance settings in ioBroker to enable HTTPS encryption of Node-RED

## Approach
* Use similar options like web web adapter of iobroker - maybe even code-snippets can be reused
  * "Encryption (HTTPS)" - checkbox
  * "Public Certificate" - dropdown of public certificates
  * "Private Certificate" - dropdown of private certificates
  * "Chain Certificate" - dropdown of chain certificates (CAs)
* The settings would be injected into settings.js of Node-RED (I assume that is what is done with the port setting (1880)

## Benefits
* Better usability of iobroker.node-red due to web-based configuration
* Increased security of smart home installations using ioBroker.Node-RED
* Error proof approach (avoids that Node-Red does not start due to errors in settings.js)
* By avoiding user changes in settings.js, iobroker.node-red gets update-proof (user changes don't get lost on updates)

**Comment by jwiesel** [comment]
implemented via PR #103. Issue can be closed after merge.

**Comment by WolfspiritM** [comment]
@jwiesel I think something went wrong as it seems like the change for the links is not included. Can you probably take a look at that again?

```
        "adminTab": {
            "link": "http://%ip%:%port%%httpRoot%",
            "fa-icon": "settings_input_composite"
        }
```

should be 
```
        "adminTab": {
            "link": "http%s%://%ip%:%port%%httpRoot%",
            "fa-icon": "settings_input_composite"
        }
```
right?

**Comment by jwiesel** [comment]
@WolfspiritM thanks for pointing that out! I just reproduced the issue. It seems like some indentation issue with file io-package.json caused the loss of that change. The merge dialog in that case showed that the entire file was changed and thereby I guess the code change got lost. I just created PR #112 to fix the issue with the admin link. In case you need the functionality, just install an adapter update in ioBroker from "https://github.com/jwiesel/ioBroker.node-red/tarball/adminlink"
